import { buildQuiz } from '../utils.js';

const G = 'grade_6';

/** Easy + medium tiers for Grade 6 adaptive routing. */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_6_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 6 Math Easy: Number Sense Foundations',
    description: 'Whole numbers, fractions, and basic operations review.',
    questions: [
      { text: 'What is 36 + 27?', options: ['63', '53', '73', '62'], correctIndex: 0, topic: 'Addition' },
      { text: 'What is 84 ÷ 7?', options: ['12', '14', '11', '13'], correctIndex: 0, topic: 'Division' },
      { text: 'Which fraction is equal to 1/2?', options: ['3/6', '2/5', '4/10', '5/12'], correctIndex: 0, topic: 'Equivalent fractions' },
      { text: 'Round 4,267 to the nearest hundred.', options: ['4,300', '4,200', '4,270', '4,000'], correctIndex: 0, topic: 'Rounding' },
      { text: 'What is 9 x 8?', options: ['72', '64', '81', '79'], correctIndex: 0, topic: 'Multiplication' },
      { text: 'Which is greater?', options: ['0.75', '0.57', 'They are equal', 'Cannot tell'], correctIndex: 0, topic: 'Decimal comparison' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 6 Math Medium: Ratios & Integers',
    description: 'Ratios, integer operations, and one-step equations.',
    questions: [
      { text: 'Simplify 12:18.', options: ['2:3', '3:2', '6:9', '4:6'], correctIndex: 0, topic: 'Ratio' },
      { text: 'What is -4 + 9?', options: ['5', '-5', '13', '-13'], correctIndex: 0, topic: 'Integers' },
      { text: 'Solve x - 5 = 13.', options: ['18', '8', '-18', '13'], correctIndex: 0, topic: 'Equation' },
      { text: 'What is 3/4 of 20?', options: ['15', '12', '16', '10'], correctIndex: 0, topic: 'Fraction of a quantity' },
      { text: 'Area of rectangle: length 9, width 4.', options: ['36', '26', '13', '18'], correctIndex: 0, topic: 'Area' },
      { text: 'What is 2^3 + 5?', options: ['13', '11', '16', '10'], correctIndex: 0, topic: 'Exponents' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 6 Science Easy: Basics of Life & Earth',
    description: 'Cells, energy, weather, and simple physical changes.',
    questions: [
      { text: 'What is the basic unit of life?', options: ['Cell', 'Atom', 'Organ', 'Planet'], correctIndex: 0, topic: 'Cells' },
      { text: 'Plants make food using sunlight through ___', options: ['photosynthesis', 'evaporation', 'condensation', 'digestion'], correctIndex: 0, topic: 'Plants' },
      { text: 'Water freezing is a ___ change.', options: ['physical', 'chemical', 'permanent', 'biological'], correctIndex: 0, topic: 'Matter' },
      { text: 'Which planet do we live on?', options: ['Earth', 'Mars', 'Venus', 'Jupiter'], correctIndex: 0, topic: 'Earth science' },
      { text: 'A thermometer measures ___', options: ['temperature', 'mass', 'speed', 'volume'], correctIndex: 0, topic: 'Measurement' },
      { text: 'The main source of energy for Earth is the ___', options: ['Sun', 'Moon', 'windmill', 'soil'], correctIndex: 0, topic: 'Energy source' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Grade 6 Science Medium: Systems & Interactions',
    description: 'Food webs, Earth layers, and scientific investigation.',
    questions: [
      { text: 'In a food chain, an herbivore is usually a ___', options: ['primary consumer', 'producer', 'decomposer', 'apex predator'], correctIndex: 0, topic: 'Food chains' },
      { text: 'Which layer is below Earths crust?', options: ['mantle', 'outer core', 'inner core', 'troposphere'], correctIndex: 0, topic: 'Earth structure' },
      { text: 'Condensation is when water vapor turns into ___', options: ['liquid water', 'ice vapor', 'salt', 'oxygen'], correctIndex: 0, topic: 'Water cycle' },
      { text: 'A fair test changes only one ___ at a time.', options: ['variable', 'hypothesis', 'result', 'table'], correctIndex: 0, topic: 'Scientific method' },
      { text: 'Which organ pumps blood through the body?', options: ['Heart', 'Lung', 'Liver', 'Stomach'], correctIndex: 0, topic: 'Body systems' },
      { text: 'Objects speed up when an unbalanced ___ acts on them.', options: ['force', 'temperature', 'mass', 'color'], correctIndex: 0, topic: 'Forces' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 6 Patterns Easy: Sequences & Tables',
    description: 'Simple number patterns and input-output rules.',
    questions: [
      { text: 'Complete: 5, 10, 15, 20, ___', options: ['25', '24', '30', '22'], correctIndex: 0, topic: 'Arithmetic sequence' },
      { text: 'Complete: 2, 4, 8, 16, ___', options: ['32', '24', '18', '30'], correctIndex: 0, topic: 'Doubling' },
      { text: 'If rule is +3, what comes after 14?', options: ['17', '16', '18', '15'], correctIndex: 0, topic: 'Rule application' },
      { text: 'Input 6 -> Output 12 follows rule ___', options: ['x2', '+2', '-2', 'x3'], correctIndex: 0, topic: 'Function rule' },
      { text: 'Find next: 30, 27, 24, 21, ___', options: ['18', '19', '17', '16'], correctIndex: 0, topic: 'Decreasing pattern' },
      { text: 'Which is an even-number pattern?', options: ['2, 4, 6, 8', '1, 3, 5, 8', '5, 10, 11, 20', '9, 7, 5, 6'], correctIndex: 0, topic: 'Parity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Grade 6 Patterns Medium: Expressions & Relations',
    description: 'Pattern rules with variables, tables, and coordinates.',
    questions: [
      { text: 'For y = x + 4, if x = 7 then y = ?', options: ['11', '3', '28', '10'], correctIndex: 0, topic: 'Linear relation' },
      { text: 'Sequence: 3, 7, 11, 15. Rule is ___', options: ['+4', '+3', 'x2', '-4'], correctIndex: 0, topic: 'Common difference' },
      { text: 'Given 2, 6, 18, 54, next term is ___', options: ['162', '108', '72', '216'], correctIndex: 0, topic: 'Geometric sequence' },
      { text: 'If nth term is 2n + 1, term at n=5 is ___', options: ['11', '10', '9', '12'], correctIndex: 0, topic: 'Nth term' },
      { text: 'Table x:1,2,3 gives y:4,7,10. y when x=4?', options: ['13', '12', '14', '11'], correctIndex: 0, topic: 'Table pattern' },
      { text: 'Point pattern adds (+2, +1): from (3,4) to ___', options: ['(5,5)', '(1,5)', '(5,3)', '(4,6)'], correctIndex: 0, topic: 'Coordinate pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 6 Memory Easy: Recall Foundations',
    description: 'Remember short facts, orders, and formulas.',
    questions: [
      { text: 'Which comes first in PEMDAS?', options: ['Parentheses', 'Multiplication', 'Addition', 'Division'], correctIndex: 0, topic: 'Math order' },
      { text: 'State of matter with fixed shape is ___', options: ['solid', 'liquid', 'gas', 'plasma only'], correctIndex: 0, topic: 'Science facts' },
      { text: 'There are ___ minutes in an hour.', options: ['60', '30', '24', '100'], correctIndex: 0, topic: 'Time facts' },
      { text: 'Remember this order: red, blue, green. Third color?', options: ['green', 'blue', 'red', 'yellow'], correctIndex: 0, topic: 'Order recall' },
      { text: 'Perimeter means distance around a ___', options: ['shape', 'number line', 'fraction', 'equation'], correctIndex: 0, topic: 'Vocabulary' },
      { text: 'The largest ocean is the ___ Ocean.', options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], correctIndex: 0, topic: 'Geography' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Grade 6 Memory Medium: Multi-Step Recall',
    description: 'Retain ordered information and academic definitions.',
    questions: [
      { text: 'Formula for area of triangle is 1/2 x ___ x height.', options: ['base', 'side', 'radius', 'perimeter'], correctIndex: 0, topic: 'Formula recall' },
      { text: 'Order remembered: 12, 7, 19, 4. Second number?', options: ['7', '12', '19', '4'], correctIndex: 0, topic: 'Sequence memory' },
      { text: 'Prime numbers are numbers with exactly ___ factors.', options: ['two', 'three', 'four', 'one'], correctIndex: 0, topic: 'Definition recall' },
      { text: 'Water cycle order starts with evaporation, then ___', options: ['condensation', 'collection', 'freezing', 'filtration'], correctIndex: 0, topic: 'Process recall' },
      { text: 'If speed = distance/time, distance = speed x ___', options: ['time', 'mass', 'force', 'area'], correctIndex: 0, topic: 'Formula transform' },
      { text: 'Remember map key: triangle=school, circle=park. Circle means ___', options: ['park', 'school', 'hospital', 'library'], correctIndex: 0, topic: 'Symbol recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 6 Problem Solving Easy: Practical Math',
    description: 'One-step reasoning with money, time, and measurement.',
    questions: [
      { text: 'A notebook costs $5. Three notebooks cost ___', options: ['$15', '$10', '$20', '$8'], correctIndex: 0, topic: 'Multiplication word problem' },
      { text: 'If class starts at 9:00 and lasts 45 minutes, it ends at ___', options: ['9:45', '9:30', '10:00', '8:45'], correctIndex: 0, topic: 'Elapsed time' },
      { text: 'A rope is 12 m long. Cut 4 m off. Remaining length?', options: ['8 m', '16 m', '6 m', '10 m'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Recipe needs 2 cups flour per batch. For 3 batches, cups needed?', options: ['6', '5', '4', '8'], correctIndex: 0, topic: 'Scaling' },
      { text: 'A bus has 24 seats and 19 are filled. Empty seats?', options: ['5', '6', '4', '3'], correctIndex: 0, topic: 'Difference' },
      { text: 'A 2 km walk plus 3 km walk equals ___ km total.', options: ['5', '6', '4', '3'], correctIndex: 0, topic: 'Add distances' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Grade 6 Problem Solving Medium: Ratios & Percent',
    description: 'Multi-step word problems using percent and proportions.',
    questions: [
      { text: 'A shirt is $40 with 20% discount. New price?', options: ['$32', '$30', '$36', '$28'], correctIndex: 0, topic: 'Percent discount' },
      { text: 'Ratio of red to blue marbles is 3:5. If red is 12, blue is ___', options: ['20', '15', '18', '24'], correctIndex: 0, topic: 'Proportion' },
      { text: 'A runner goes 6 km in 1.5 hours. Average speed?', options: ['4 km/h', '3 km/h', '5 km/h', '9 km/h'], correctIndex: 0, topic: 'Rate' },
      { text: 'Class has 30 students; 40% are girls. Number of girls?', options: ['12', '18', '10', '15'], correctIndex: 0, topic: 'Percent of quantity' },
      { text: 'Rectangle length 12, width 5. Perimeter is ___', options: ['34', '60', '17', '24'], correctIndex: 0, topic: 'Perimeter' },
      { text: 'Map scale 1 cm = 4 km. A 7 cm road is ___ km.', options: ['28', '21', '14', '11'], correctIndex: 0, topic: 'Scale factor' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 6 Critical Thinking Easy: Evidence & Choices',
    description: 'Differentiate facts from opinions and choose better evidence.',
    questions: [
      { text: 'Which is a fact?', options: ['Water boils at a specific temperature', 'Summer is the best season', 'Pizza is healthier than salad', 'Blue is the nicest color'], correctIndex: 0, topic: 'Fact vs opinion' },
      { text: 'Best tool to measure room length is a ___', options: ['measuring tape', 'thermometer', 'stopwatch', 'scale'], correctIndex: 0, topic: 'Tool selection' },
      { text: 'A claim without data is usually ___', options: ['weaker', 'always true', 'stronger', 'scientific proof'], correctIndex: 0, topic: 'Claims' },
      { text: 'If the sky is dark and clouds are heavy, rain is ___', options: ['more likely', 'impossible', 'guaranteed sunny', 'unrelated'], correctIndex: 0, topic: 'Inference' },
      { text: 'Which source is most reliable for weather?', options: ['official weather service', 'a random guess', 'a meme post', 'a comic strip'], correctIndex: 0, topic: 'Source quality' },
      { text: 'To solve a problem fairly in class, you should first ___', options: ['listen to both sides', 'pick a friend', 'ignore details', 'vote without discussion'], correctIndex: 0, topic: 'Decision making' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Grade 6 Critical Thinking Medium: Logic & Evaluation',
    description: 'Evaluate arguments, bias, and experimental evidence.',
    questions: [
      { text: 'A study with only 3 people is often less reliable because ___', options: ['sample is too small', 'graphs are colorful', 'title is short', 'it uses numbers'], correctIndex: 0, topic: 'Sample size' },
      { text: 'If all squares are rectangles and shape A is a square, then A is a ___', options: ['rectangle', 'triangle', 'circle', 'rhombus only'], correctIndex: 0, topic: 'Deductive logic' },
      { text: 'A biased survey question usually ___', options: ['pushes one answer', 'has numbers', 'is multiple choice', 'uses punctuation'], correctIndex: 0, topic: 'Bias' },
      { text: 'Best way to check a surprising result is to ___', options: ['repeat the experiment', 'ignore it', 'change all variables', 'post it immediately'], correctIndex: 0, topic: 'Verification' },
      { text: 'Correlation between A and B means ___', options: ['they change together, not necessarily cause', 'A always causes B', 'B always causes A', 'there is no relationship'], correctIndex: 0, topic: 'Data interpretation' },
      { text: 'Strong arguments include evidence and also address ___', options: ['counterarguments', 'font style', 'speaker height', 'room color'], correctIndex: 0, topic: 'Argument analysis' },
    ],
  }),
];
