import { buildQuiz } from '../utils.js';

const G = 'grade_3';

/** Easy + hard tiers for Grade 3 adaptive ladder (medium is in grade_3.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_3_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 3 Math Easy: Facts & Fractions Basics',
    description: 'Simple multiplication facts and unit-fraction understanding.',
    questions: [
      { text: '3 × 4 = ?', options: ['12', '7', '16', '10'], correctIndex: 0, topic: 'Multiplication facts' },
      { text: '2 × 6 = ?', options: ['12', '8', '14', '10'], correctIndex: 0, topic: 'Multiplication facts' },
      { text: '1/2 of 10 = ?', options: ['5', '2', '10', '8'], correctIndex: 0, topic: 'Fractions' },
      { text: 'Which is a unit fraction?', options: ['1/4', '2/4', '3/5', '4/4'], correctIndex: 0, topic: 'Unit fractions' },
      { text: '4 × 5 = ?', options: ['20', '18', '25', '9'], correctIndex: 0, topic: 'Multiplication facts' },
      { text: '1/3 of 12 = ?', options: ['4', '3', '6', '9'], correctIndex: 0, topic: 'Fractions' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 3 Math Hard: Multi-Step Multiplication & Fractions',
    description: 'Two-step operations, area/perimeter reasoning, and fraction comparison.',
    questions: [
      { text: '(6 × 4) + 8 = ?', options: ['32', '30', '28', '34'], correctIndex: 0, topic: 'Two-step operations' },
      { text: 'A rectangle is 7 by 3. Area is ___', options: ['21', '10', '24', '14'], correctIndex: 0, topic: 'Area' },
      { text: 'A rectangle is 7 by 3. Perimeter is ___', options: ['20', '21', '14', '10'], correctIndex: 0, topic: 'Perimeter' },
      { text: 'Which is greater?', options: ['3/4', '2/3', 'They are equal', '1/2'], correctIndex: 0, topic: 'Fraction comparison' },
      { text: '48 ÷ 6 + 9 = ?', options: ['17', '16', '15', '18'], correctIndex: 0, topic: 'Division then addition' },
      { text: 'Nina has 5 packs of 8 stickers and gives away 9. Left?', options: ['31', '29', '33', '40'], correctIndex: 0, topic: 'Word problem' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 3 Science Easy: Forces & Life Cycles',
    description: 'Core ideas about pushes, pulls, and living things.',
    questions: [
      { text: 'Opening a drawer is mostly a ___', options: ['pull', 'push', 'magnet', 'float'], correctIndex: 0, topic: 'Forces' },
      { text: 'Pushing a swing forward is a ___', options: ['push', 'pull', 'friction', 'freeze'], correctIndex: 0, topic: 'Forces' },
      { text: 'A butterfly starts as a ___', options: ['egg', 'frog', 'seed', 'rock'], correctIndex: 0, topic: 'Life cycle' },
      { text: 'Plants make food mostly in the ___', options: ['leaves', 'roots', 'flowers only', 'soil'], correctIndex: 0, topic: 'Plant parts' },
      { text: 'The skeleton helps your body by ___', options: ['supporting it', 'making rain', 'cooling food', 'changing weather'], correctIndex: 0, topic: 'Body systems' },
      { text: 'Friction usually makes moving objects ___', options: ['slow down', 'speed up forever', 'float', 'disappear'], correctIndex: 0, topic: 'Friction' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 3 Science Hard: Systems, Evidence & Experiments',
    description: 'Multi-step cause/effect and fair-test reasoning.',
    questions: [
      { text: 'In a fair plant test, what should you change?', options: ['only one variable', 'every variable', 'no measurements', 'the hypothesis only'], correctIndex: 0, topic: 'Fair tests' },
      { text: 'If two toy cars roll down ramps, what best shows which is faster?', options: ['time each run', 'car color', 'car name', 'driver opinion'], correctIndex: 0, topic: 'Evidence' },
      { text: 'Food gives muscles energy through the ___ system first', options: ['digestive', 'skeletal', 'weather', 'solar'], correctIndex: 0, topic: 'Body systems' },
      { text: 'If soil lacks water, most seeds will ___', options: ['grow poorly', 'grow faster', 'turn to rocks', 'multiply instantly'], correctIndex: 0, topic: 'Plant needs' },
      { text: 'Which setup best tests friction?', options: ['same toy on rough vs smooth surface', 'different toys on different ramps', 'same toy with no measuring', 'guessing by sight'], correctIndex: 0, topic: 'Experiment design' },
      { text: 'A longer shadow at noon usually means the light source is ___', options: ['at a lower angle', 'inside the object', 'stronger wind', 'colder air'], correctIndex: 0, topic: 'Light and shadows' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 3 Pattern Recognition Easy: Skip & Rule Basics',
    description: 'Identify simple number and input-output patterns.',
    questions: [
      { text: '4, 8, 12, 16, ___', options: ['20', '18', '22', '24'], correctIndex: 0, topic: 'Skip counting by 4' },
      { text: '2, 5, 8, 11, ___', options: ['14', '13', '15', '16'], correctIndex: 0, topic: '+3 pattern' },
      { text: 'Rule: +2. Input 7, output ___', options: ['9', '14', '5', '10'], correctIndex: 0, topic: 'Function rule' },
      { text: '1/4, 2/4, 3/4, ___', options: ['4/4', '5/4', '1/2', '2/3'], correctIndex: 0, topic: 'Fraction sequence' },
      { text: '30, 25, 20, 15, ___', options: ['10', '12', '5', '18'], correctIndex: 0, topic: '-5 pattern' },
      { text: '6, 12, 18, ___', options: ['24', '20', '30', '22'], correctIndex: 0, topic: 'Multiples of 6' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 3 Pattern Recognition Hard: Multi-Rule Sequences',
    description: 'Analyze alternating, multiplicative, and function-machine patterns.',
    questions: [
      { text: '2, 6, 3, 9, 4, 12, ___, ___', options: ['5, 15', '5, 14', '6, 18', '4, 16'], correctIndex: 0, topic: 'Alternating related pattern' },
      { text: 'Rule: ×2 then +1. Input 7 gives ___', options: ['15', '14', '16', '13'], correctIndex: 0, topic: 'Two-step function' },
      { text: '81, 27, 9, 3, ___', options: ['1', '0', '6', '12'], correctIndex: 0, topic: 'Divide by 3' },
      { text: '1/2, 2/3, 3/4, 4/5, ___', options: ['5/6', '4/6', '6/5', '1'], correctIndex: 0, topic: 'Fraction numerator/denominator rule' },
      { text: '5, 8, 14, 23, ___', options: ['35', '32', '34', '30'], correctIndex: 0, topic: 'Increasing differences' },
      { text: 'Input 3 -> 11 and input 5 -> 17. Rule is ___', options: ['×3 + 2', '×2 + 5', '×4 - 1', '+8'], correctIndex: 0, topic: 'Infer function rule' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 3 Memory Easy: Steps, Facts & Sequences',
    description: 'Recall short ordered information and learned facts.',
    questions: [
      { text: 'Morning steps: wake, brush, eat, pack. Third step?', options: ['eat', 'brush', 'pack', 'wake'], correctIndex: 0, topic: 'Order recall' },
      { text: 'Remember: 4, 9, 2. Which number was in the middle?', options: ['9', '4', '2', '6'], correctIndex: 0, topic: 'Short-term memory' },
      { text: '7 × 6 = ?', options: ['42', '36', '48', '56'], correctIndex: 0, topic: 'Fact recall' },
      { text: 'Water cycle order starts with evaporation, then ___', options: ['condensation', 'collection', 'freezing', 'melting'], correctIndex: 0, topic: 'Science sequence' },
      { text: 'Days: Monday, Tuesday, Wednesday, ___', options: ['Thursday', 'Friday', 'Sunday', 'Saturday'], correctIndex: 0, topic: 'Sequence memory' },
      { text: 'Code shown once: B-7-K. Last character?', options: ['K', 'B', '7', 'BK'], correctIndex: 0, topic: 'Symbol recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 3 Memory Hard: Chunking & Multi-Step Recall',
    description: 'Hold and manipulate longer sequences and linked facts.',
    questions: [
      { text: 'Remember 3-8-1-9. Which came right after 8?', options: ['1', '9', '3', '8'], correctIndex: 0, topic: 'Sequential recall' },
      { text: 'Science steps: question -> hypothesis -> test -> data. Step before data?', options: ['test', 'question', 'hypothesis', 'conclusion'], correctIndex: 0, topic: 'Process memory' },
      { text: 'Chunk this number: 458732 as ___', options: ['458-732', '45-87-32', '4-5-8-7-3-2', '4587-32'], correctIndex: 0, topic: 'Chunking strategy' },
      { text: 'Map key says triangle=park, circle=school. Circle means ___', options: ['school', 'park', 'road', 'river'], correctIndex: 0, topic: 'Symbol mapping' },
      { text: 'List heard once: apple, pear, grape, mango. Second fruit?', options: ['pear', 'apple', 'grape', 'mango'], correctIndex: 0, topic: 'List recall' },
      { text: 'If 6×7=42 and 42-5=37, final result remembered is ___', options: ['37', '42', '35', '47'], correctIndex: 0, topic: 'Working memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 3 Problem Solving Easy: One-to-Two Step Stories',
    description: 'Use simple multiplication and subtraction in story contexts.',
    questions: [
      { text: '3 boxes with 5 pencils each. Total pencils?', options: ['15', '8', '10', '35'], correctIndex: 0, topic: 'Equal groups' },
      { text: 'There are 18 apples. 6 are eaten. Left?', options: ['12', '10', '14', '24'], correctIndex: 0, topic: 'Subtraction story' },
      { text: 'A ribbon is 20 cm. You cut off 7 cm. Remaining length?', options: ['13 cm', '12 cm', '27 cm', '7 cm'], correctIndex: 0, topic: 'Measurement' },
      { text: '4 rows of 3 chairs means ___ chairs', options: ['12', '7', '8', '43'], correctIndex: 0, topic: 'Arrays' },
      { text: 'You have $9 and spend $4. Money left?', options: ['$5', '$4', '$13', '$6'], correctIndex: 0, topic: 'Money' },
      { text: 'What do you measure to find around a shape?', options: ['perimeter', 'area', 'volume', 'mass'], correctIndex: 0, topic: 'Math vocabulary' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 3 Problem Solving Hard: Plan, Compute, Check',
    description: 'Solve multi-step situations with operation choice and verification.',
    questions: [
      { text: '7 packs of 6 markers are shared equally among 3 classes. How many markers per class?', options: ['14', '13', '12', '42'], correctIndex: 0, topic: 'Multi-step division' },
      { text: 'A 9x4 garden has area ___ and perimeter ___', options: ['36 and 26', '13 and 36', '26 and 36', '36 and 18'], correctIndex: 0, topic: 'Area and perimeter' },
      { text: 'Bus A has 24 students, Bus B has 18. 9 students leave total. Remaining?', options: ['33', '42', '31', '27'], correctIndex: 0, topic: 'Combine then subtract' },
      { text: 'A book costs $7. Mia buys 3 books and a $4 notebook. Total cost?', options: ['$25', '$21', '$24', '$18'], correctIndex: 0, topic: 'Mixed operations' },
      { text: 'A tank is filled 5 liters each hour for 6 hours, then 8 liters are used. Liters left?', options: ['22', '30', '28', '18'], correctIndex: 0, topic: 'Rate and subtraction' },
      { text: 'Which check best confirms 56 ÷ 8 = 7?', options: ['7 × 8 = 56', '56 - 8 = 48', '8 + 7 = 15', '56 + 8 = 64'], correctIndex: 0, topic: 'Reasonableness check' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 3 Critical Thinking Easy: Claims & Evidence Basics',
    description: 'Distinguish facts from opinions and choose better evidence.',
    questions: [
      { text: '"Cats are the best pets" is a ___', options: ['opinion', 'fact', 'measurement', 'graph'], correctIndex: 0, topic: 'Fact vs opinion' },
      { text: 'Best evidence that a plant grew is ___', options: ['measured height over days', 'it looks nice', 'someone guessed', 'a cartoon'], correctIndex: 0, topic: 'Evidence' },
      { text: 'A website with author and date is usually ___ than one without', options: ['more reliable', 'less reliable', 'always fake', 'exactly equal'], correctIndex: 0, topic: 'Source quality' },
      { text: 'If all squares are rectangles, then a square is a ___', options: ['rectangle', 'triangle', 'circle', 'line'], correctIndex: 0, topic: 'Logic' },
      { text: 'To compare two objects fairly, use the same ___', options: ['conditions', 'colors only', 'names', 'guesses'], correctIndex: 0, topic: 'Fair comparison' },
      { text: 'A bar graph is useful because it makes data ___', options: ['easy to compare', 'invisible', 'random', 'unnecessary'], correctIndex: 0, topic: 'Data interpretation' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 3 Critical Thinking Hard: Analyze, Infer & Justify',
    description: 'Evaluate claims, identify weak reasoning, and infer from data.',
    questions: [
      { text: 'A student says, "My plant grew because I sang to it." What is missing?', options: ['controlled evidence', 'a louder voice', 'more opinions', 'a drawing'], correctIndex: 0, topic: 'Causation vs evidence' },
      { text: 'If class data shows 18 prefer apples and 6 prefer pears, best conclusion is ___', options: ['more students prefer apples', 'pears are healthier', 'everyone likes apples', 'data is wrong'], correctIndex: 0, topic: 'Data-based inference' },
      { text: 'Which source is strongest for "Today\'s temperature"?', options: ['thermometer reading', 'friend\'s guess', 'yesterday\'s weather', 'a storybook'], correctIndex: 0, topic: 'Source strength' },
      { text: 'If A > B and B = C, then A compared with C is ___', options: ['greater than', 'equal to', 'less than', 'unknown always'], correctIndex: 0, topic: 'Logical transitivity' },
      { text: 'An ad says "100% best toy ever!" This is mainly ___', options: ['persuasive language', 'scientific proof', 'numerical data', 'a controlled trial'], correctIndex: 0, topic: 'Bias and persuasion' },
      { text: 'To test paper towel brands fairly, you should keep all but one thing ___', options: ['the same', 'different', 'unmeasured', 'randomly ignored'], correctIndex: 0, topic: 'Experiment design' },
    ],
  }),
];
