import { buildQuiz } from '../utils.js';

const G = 'grade_6';

/** Easy + medium tiers for Grade 6 adaptive routing. */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_6_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 6 Math Easy: Number Sense Foundations',
    description: 'Whole numbers, fractions, and basic operations review.',
    questions: [
      { text: 'What is 36 + 27?', options: ['53', '73', '63', '62'], correctIndex: 2, topic: 'Addition' },
      { text: 'What is 84 ÷ 7?', options: ['12', '11', '14', '13'], correctIndex: 0, topic: 'Division' },
      { text: 'Which fraction is equal to 1/2?', options: ['5/12', '3/6', '4/10', '2/5'], correctIndex: 1, topic: 'Equivalent fractions' },
      { text: 'Round 4,267 to the nearest hundred.', options: ['4,300', '4,200', '4,000', '4,270'], correctIndex: 0, topic: 'Rounding' },
      { text: 'What is 9 x 8?', options: ['79', '72', '64', '81'], correctIndex: 1, topic: 'Multiplication' },
      { text: 'Which is greater?', options: ['They are equal', '0.75', '0.57', 'Cannot tell'], correctIndex: 1, topic: 'Decimal comparison' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 6 Math Medium: Ratios & Integers',
    description: 'Ratios, integer operations, and one-step equations.',
    questions: [
      { text: 'Simplify 12:18.', options: ['3:2', '2:3', '4:6', '6:9'], correctIndex: 1, topic: 'Ratio' },
      { text: 'What is -4 + 9?', options: ['5', '-13', '13', '-5'], correctIndex: 0, topic: 'Integers' },
      { text: 'Solve x - 5 = 13.', options: ['-18', '13', '8', '18'], correctIndex: 3, topic: 'Equation' },
      { text: 'What is 3/4 of 20?', options: ['12', '15', '16', '10'], correctIndex: 1, topic: 'Fraction of a quantity' },
      { text: 'Area of rectangle: length 9, width 4.', options: ['18', '36', '13', '26'], correctIndex: 1, topic: 'Area' },
      { text: 'What is 2^3 + 5?', options: ['13', '16', '10', '11'], correctIndex: 0, topic: 'Exponents' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 6 Science Easy: Basics of Life & Earth',
    description: 'Cells, energy, weather, and simple physical changes.',
    questions: [
      { text: 'What is the basic unit of life?', options: ['Atom', 'Planet', 'Organ', 'Cell'], correctIndex: 3, topic: 'Cells' },
      { text: 'Plants make food using sunlight through ___', options: ['evaporation', 'condensation', 'photosynthesis', 'digestion'], correctIndex: 2, topic: 'Plants' },
      { text: 'Water freezing is a ___ change.', options: ['biological', 'permanent', 'chemical', 'physical'], correctIndex: 3, topic: 'Matter' },
      { text: 'Which planet do we live on?', options: ['Jupiter', 'Earth', 'Venus', 'Mars'], correctIndex: 1, topic: 'Earth science' },
      { text: 'A thermometer measures ___', options: ['speed', 'volume', 'mass', 'temperature'], correctIndex: 3, topic: 'Measurement' },
      { text: 'The main source of energy for Earth is the ___', options: ['soil', 'windmill', 'Moon', 'Sun'], correctIndex: 3, topic: 'Energy source' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Grade 6 Science Medium: Systems & Interactions',
    description: 'Food webs, Earth layers, and scientific investigation.',
    questions: [
      { text: 'In a food chain, an herbivore is usually a ___', options: ['producer', 'decomposer', 'apex predator', 'primary consumer'], correctIndex: 3, topic: 'Food chains' },
      { text: 'Which layer is below Earths crust?', options: ['troposphere', 'inner core', 'outer core', 'mantle'], correctIndex: 3, topic: 'Earth structure' },
      { text: 'Condensation is when water vapor turns into ___', options: ['ice vapor', 'liquid water', 'salt', 'oxygen'], correctIndex: 1, topic: 'Water cycle' },
      { text: 'A fair test changes only one ___ at a time.', options: ['result', 'variable', 'table', 'hypothesis'], correctIndex: 1, topic: 'Scientific method' },
      { text: 'Which organ pumps blood through the body?', options: ['Stomach', 'Heart', 'Liver', 'Lung'], correctIndex: 1, topic: 'Body systems' },
      { text: 'Objects speed up when an unbalanced ___ acts on them.', options: ['force', 'color', 'temperature', 'mass'], correctIndex: 0, topic: 'Forces' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 6 Patterns Easy: Sequences & Tables',
    description: 'Simple number patterns and input-output rules.',
    questions: [
      { text: 'Complete: 5, 10, 15, 20, ___', options: ['24', '30', '25', '22'], correctIndex: 2, topic: 'Arithmetic sequence' },
      { text: 'Complete: 2, 4, 8, 16, ___', options: ['24', '18', '30', '32'], correctIndex: 3, topic: 'Doubling' },
      { text: 'If rule is +3, what comes after 14?', options: ['18', '16', '15', '17'], correctIndex: 3, topic: 'Rule application' },
      { text: 'Input 6 -> Output 12 follows rule ___', options: ['x3', '-2', '+2', 'x2'], correctIndex: 3, topic: 'Function rule' },
      { text: 'Find next: 30, 27, 24, 21, ___', options: ['18', '17', '16', '19'], correctIndex: 0, topic: 'Decreasing pattern' },
      { text: 'Which is an even-number pattern?', options: ['9, 7, 5, 6', '2, 4, 6, 8', '1, 3, 5, 8', '5, 10, 11, 20'], correctIndex: 1, topic: 'Parity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Grade 6 Patterns Medium: Expressions & Relations',
    description: 'Pattern rules with variables, tables, and coordinates.',
    questions: [
      { text: 'For y = x + 4, if x = 7 then y = ?', options: ['10', '28', '11', '3'], correctIndex: 2, topic: 'Linear relation' },
      { text: 'Sequence: 3, 7, 11, 15. Rule is ___', options: ['-4', '+3', '+4', 'x2'], correctIndex: 2, topic: 'Common difference' },
      { text: 'Given 2, 6, 18, 54, next term is ___', options: ['216', '162', '72', '108'], correctIndex: 1, topic: 'Geometric sequence' },
      { text: 'If nth term is 2n + 1, term at n=5 is ___', options: ['10', '12', '9', '11'], correctIndex: 3, topic: 'Nth term' },
      { text: 'Table x:1,2,3 gives y:4,7,10. y when x=4?', options: ['11', '14', '13', '12'], correctIndex: 2, topic: 'Table pattern' },
      { text: 'Point pattern adds (+2, +1): from (3,4) to ___', options: ['(5,3)', '(5,5)', '(1,5)', '(4,6)'], correctIndex: 1, topic: 'Coordinate pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 6 Memory Easy: Recall Foundations',
    description: 'Remember short facts, orders, and formulas.',
    questions: [
      { text: 'Which comes first in PEMDAS?', options: ['Parentheses', 'Multiplication', 'Addition', 'Division'], correctIndex: 0, topic: 'Math order' },
      { text: 'State of matter with fixed shape is ___', options: ['gas', 'solid', 'liquid', 'plasma only'], correctIndex: 1, topic: 'Science facts' },
      { text: 'There are ___ minutes in an hour.', options: ['24', '100', '30', '60'], correctIndex: 3, topic: 'Time facts' },
      { text: 'Remember this order: red, blue, green. Third color?', options: ['blue', 'yellow', 'green', 'red'], correctIndex: 2, topic: 'Order recall' },
      { text: 'Perimeter means distance around a ___', options: ['fraction', 'shape', 'number line', 'equation'], correctIndex: 1, topic: 'Vocabulary' },
      { text: 'The largest ocean is the ___ Ocean.', options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], correctIndex: 0, topic: 'Geography' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Grade 6 Memory Medium: Multi-Step Recall',
    description: 'Retain ordered information and academic definitions.',
    questions: [
      { text: 'Formula for area of triangle is 1/2 x ___ x height.', options: ['perimeter', 'side', 'base', 'radius'], correctIndex: 2, topic: 'Formula recall' },
      { text: 'Order remembered: 12, 7, 19, 4. Second number?', options: ['12', '4', '19', '7'], correctIndex: 3, topic: 'Sequence memory' },
      { text: 'Prime numbers are numbers with exactly ___ factors.', options: ['one', 'three', 'four', 'two'], correctIndex: 3, topic: 'Definition recall' },
      { text: 'Water cycle order starts with evaporation, then ___', options: ['collection', 'condensation', 'filtration', 'freezing'], correctIndex: 1, topic: 'Process recall' },
      { text: 'If speed = distance/time, distance = speed x ___', options: ['time', 'mass', 'area', 'force'], correctIndex: 0, topic: 'Formula transform' },
      { text: 'Remember map key: triangle=school, circle=park. Circle means ___', options: ['school', 'park', 'library', 'hospital'], correctIndex: 1, topic: 'Symbol recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 6 Problem Solving Easy: Practical Math',
    description: 'One-step reasoning with money, time, and measurement.',
    questions: [
      { text: 'A notebook costs $5. Three notebooks cost ___', options: ['$8', '$10', '$15', '$20'], correctIndex: 2, topic: 'Multiplication word problem' },
      { text: 'If class starts at 9:00 and lasts 45 minutes, it ends at ___', options: ['10:00', '8:45', '9:30', '9:45'], correctIndex: 3, topic: 'Elapsed time' },
      { text: 'A rope is 12 m long. Cut 4 m off. Remaining length?', options: ['16 m', '10 m', '8 m', '6 m'], correctIndex: 2, topic: 'Subtraction' },
      { text: 'Recipe needs 2 cups flour per batch. For 3 batches, cups needed?', options: ['6', '4', '5', '8'], correctIndex: 0, topic: 'Scaling' },
      { text: 'A bus has 24 seats and 19 are filled. Empty seats?', options: ['4', '3', '5', '6'], correctIndex: 2, topic: 'Difference' },
      { text: 'A 2 km walk plus 3 km walk equals ___ km total.', options: ['6', '3', '5', '4'], correctIndex: 2, topic: 'Add distances' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Grade 6 Problem Solving Medium: Ratios & Percent',
    description: 'Multi-step word problems using percent and proportions.',
    questions: [
      { text: 'A shirt is $40 with 20% discount. New price?', options: ['$32', '$28', '$30', '$36'], correctIndex: 0, topic: 'Percent discount' },
      { text: 'Ratio of red to blue marbles is 3:5. If red is 12, blue is ___', options: ['18', '15', '24', '20'], correctIndex: 3, topic: 'Proportion' },
      { text: 'A runner goes 6 km in 1.5 hours. Average speed?', options: ['5 km/h', '9 km/h', '3 km/h', '4 km/h'], correctIndex: 3, topic: 'Rate' },
      { text: 'Class has 30 students; 40% are girls. Number of girls?', options: ['12', '15', '10', '18'], correctIndex: 0, topic: 'Percent of quantity' },
      { text: 'Rectangle length 12, width 5. Perimeter is ___', options: ['60', '34', '24', '17'], correctIndex: 1, topic: 'Perimeter' },
      { text: 'Map scale 1 cm = 4 km. A 7 cm road is ___ km.', options: ['28', '11', '21', '14'], correctIndex: 0, topic: 'Scale factor' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 6 Critical Thinking Easy: Evidence & Choices',
    description: 'Differentiate facts from opinions and choose better evidence.',
    questions: [
      { text: 'Which is a fact?', options: ['Pizza is healthier than salad', 'Summer is the best season', 'Blue is the nicest color', 'Water boils at a specific temperature'], correctIndex: 3, topic: 'Fact vs opinion' },
      { text: 'Best tool to measure room length is a ___', options: ['scale', 'stopwatch', 'thermometer', 'measuring tape'], correctIndex: 3, topic: 'Tool selection' },
      { text: 'A claim without data is usually ___', options: ['scientific proof', 'weaker', 'always true', 'stronger'], correctIndex: 1, topic: 'Claims' },
      { text: 'If the sky is dark and clouds are heavy, rain is ___', options: ['guaranteed sunny', 'impossible', 'unrelated', 'more likely'], correctIndex: 3, topic: 'Inference' },
      { text: 'Which source is most reliable for weather?', options: ['a meme post', 'a random guess', 'a comic strip', 'official weather service'], correctIndex: 3, topic: 'Source quality' },
      { text: 'To solve a problem fairly in class, you should first ___', options: ['vote without discussion', 'listen to both sides', 'pick a friend', 'ignore details'], correctIndex: 1, topic: 'Decision making' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Grade 6 Critical Thinking Medium: Logic & Evaluation',
    description: 'Evaluate arguments, bias, and experimental evidence.',
    questions: [
      { text: 'A study with only 3 people is often less reliable because ___', options: ['sample is too small', 'it uses numbers', 'graphs are colorful', 'title is short'], correctIndex: 0, topic: 'Sample size' },
      { text: 'If all squares are rectangles and shape A is a square, then A is a ___', options: ['rectangle', 'rhombus only', 'triangle', 'circle'], correctIndex: 0, topic: 'Deductive logic' },
      { text: 'A biased survey question usually ___', options: ['is multiple choice', 'uses punctuation', 'has numbers', 'pushes one answer'], correctIndex: 3, topic: 'Bias' },
      { text: 'Best way to check a surprising result is to ___', options: ['repeat the experiment', 'change all variables', 'ignore it', 'post it immediately'], correctIndex: 0, topic: 'Verification' },
      { text: 'Correlation between A and B means ___', options: ['they change together, not necessarily cause', 'there is no relationship', 'B always causes A', 'A always causes B'], correctIndex: 0, topic: 'Data interpretation' },
      { text: 'Strong arguments include evidence and also address ___', options: ['room color', 'counterarguments', 'speaker height', 'font style'], correctIndex: 1, topic: 'Argument analysis' },
    ],
  }),
];
