import { buildQuiz } from '../utils.js';

const G = 'grade_5';

/** Easy + medium tiers for Grade 5 adaptive ladder (hard lives in grade_5.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_5_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 5 Math Easy: Fraction Basics',
    description: 'Core fraction, decimal, and whole-number skills.',
    questions: [
      { text: '3/5 + 1/5 = ?', options: ['2/5', '4/10', '4/5', '3/10'], correctIndex: 2, topic: 'Fractions' },
      { text: '0.7 + 0.2 = ?', options: ['0.72', '0.9', '0.8', '0.5'], correctIndex: 1, topic: 'Decimals' },
      { text: '6 x 7 = ?', options: ['48', '42', '56', '36'], correctIndex: 1, topic: 'Multiplication' },
      { text: 'Which is greater: 0.45 or 0.4?', options: ['0.4', 'They are equal', 'Cannot tell', '0.45'], correctIndex: 3, topic: 'Compare decimals' },
      { text: '35 / 5 = ?', options: ['6', '8', '5', '7'], correctIndex: 3, topic: 'Division' },
      { text: 'Perimeter of a rectangle 8 cm by 3 cm?', options: ['11 cm', '24 cm', '22 cm', '16 cm'], correctIndex: 2, topic: 'Perimeter' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 5 Math Medium: Decimals & Volume Prep',
    description: 'Multi-step fraction/decimal work and volume setup.',
    questions: [
      { text: '2.4 + 1.35 = ?', options: ['2.59', '3.75', '3.59', '3.15'], correctIndex: 1, topic: 'Decimal addition' },
      { text: '5/6 - 1/6 = ?', options: ['2/3', '5/12', '4/12', '1/3'], correctIndex: 0, topic: 'Fraction subtraction' },
      { text: 'A box is 4 cm x 3 cm x 2 cm. Volume?', options: ['18 cm^3', '12 cm^2', '9 cm^3', '24 cm^3'], correctIndex: 3, topic: 'Volume' },
      { text: '0.8 x 5 = ?', options: ['4', '3.5', '0.4', '13'], correctIndex: 0, topic: 'Decimal multiplication' },
      { text: 'What is 30% of 50?', options: ['25', '15', '20', '10'], correctIndex: 1, topic: 'Percent' },
      { text: '2 + 6 x 3 = ?', options: ['24', '26', '20', '18'], correctIndex: 2, topic: 'Order of operations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 5 Science Easy: Matter & Life',
    description: 'Foundational ideas in mixtures, cells, and ecosystems.',
    questions: [
      { text: 'Water changing to ice is a ___ change.', options: ['biological', 'chemical', 'permanent', 'physical'], correctIndex: 3, topic: 'Matter changes' },
      { text: 'The nucleus is found in a ___', options: ['cloud', 'rock', 'cell', 'planet'], correctIndex: 2, topic: 'Cells' },
      { text: 'Plants make food by ___', options: ['erosion', 'photosynthesis', 'condensation', 'evaporation'], correctIndex: 1, topic: 'Plants' },
      { text: 'A rabbit is most likely a ___ in a food chain.', options: ['decomposer', 'producer', 'mineral', 'consumer'], correctIndex: 3, topic: 'Ecosystems' },
      { text: 'Earth takes about ___ to orbit the Sun.', options: ['10 years', '1 year', '1 month', '1 day'], correctIndex: 1, topic: 'Space' },
      { text: 'Which material is usually an electrical conductor?', options: ['rubber', 'copper', 'wood', 'plastic'], correctIndex: 1, topic: 'Electricity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Grade 5 Science Medium: Systems & Evidence',
    description: 'Apply science ideas to processes and observations.',
    questions: [
      { text: 'In photosynthesis, plants use light, water, and ___.', options: ['soil only', 'carbon dioxide', 'oxygen only', 'salt'], correctIndex: 1, topic: 'Photosynthesis' },
      { text: 'When vinegar reacts with baking soda, gas forms. This is a ___ change.', options: ['chemical', 'reversible-only', 'shape-only', 'physical'], correctIndex: 0, topic: 'Chemical change' },
      { text: 'The heart is part of which body system?', options: ['nervous system', 'skeletal system', 'circulatory system', 'digestive system'], correctIndex: 2, topic: 'Human body' },
      { text: 'A food chain starts with energy from the ___.', options: ['Moon', 'soil', 'wind', 'Sun'], correctIndex: 3, topic: 'Energy flow' },
      { text: 'Why do we see different moon phases?', options: ['Earth glows differently each week', 'Clouds cover parts permanently', 'Different sunlit portions are visible', 'The Moon changes size'], correctIndex: 2, topic: 'Moon phases' },
      { text: 'Best way to test if fertilizer helps growth is to change only ___.', options: ['everything at once', 'plant type and water', 'soil and light together', 'fertilizer amount'], correctIndex: 3, topic: 'Fair test' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 5 Patterns Easy: Number Rules',
    description: 'Recognize and continue arithmetic and visual patterns.',
    questions: [
      { text: '4, 8, 12, 16, ___', options: ['24', '22', '18', '20'], correctIndex: 3, topic: 'Add 4' },
      { text: '2, 4, 8, 16, ___', options: ['18', '24', '32', '20'], correctIndex: 2, topic: 'Multiply by 2' },
      { text: 'A, C, E, G, ___', options: ['I', 'H', 'J', 'F'], correctIndex: 0, topic: 'Letter skip' },
      { text: '0.1, 0.2, 0.3, ___', options: ['0.4', '0.45', '0.35', '0.5'], correctIndex: 0, topic: 'Decimal sequence' },
      { text: '5, 10, 15, 20, ___', options: ['25', '22', '24', '30'], correctIndex: 0, topic: 'Skip counting' },
      { text: 'Square, circle, square, circle, ___', options: ['circle', 'triangle', 'rectangle', 'square'], correctIndex: 3, topic: 'Alternating pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Grade 5 Patterns Medium: Expressions & Coordinates',
    description: 'Infer deeper rules from tables, pairs, and formulas.',
    questions: [
      { text: '3, 6, 11, 18, ___', options: ['27', '25', '24', '29'], correctIndex: 0, topic: 'Increasing differences' },
      { text: 'If rule is y = 2x + 1, when x = 4, y = ___', options: ['8', '9', '10', '7'], correctIndex: 1, topic: 'Algebraic rule' },
      { text: '(1,3), (2,6), (3,9), (4,___)', options: ['13', '11', '10', '12'], correctIndex: 3, topic: 'Coordinate pattern' },
      { text: '1, 4, 9, 16, 25, ___', options: ['49', '36', '35', '30'], correctIndex: 1, topic: 'Square numbers' },
      { text: 'Pattern: start at 100, subtract 7 each step. Third term is ___', options: ['86', '93', '84', '79'], correctIndex: 0, topic: 'Rule application' },
      { text: '2, -2, 2, -2, ___', options: ['-4', '2', '0', '-2'], correctIndex: 1, topic: 'Alternating signs' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 5 Memory Easy: Facts & Sequences',
    description: 'Recall key facts, ordered steps, and basic mnemonics.',
    questions: [
      { text: '8 x 9 = ?', options: ['79', '72', '81', '63'], correctIndex: 1, topic: 'Math facts' },
      { text: 'Planets near the Sun start Mercury, Venus, ___.', options: ['Mars', 'Jupiter', 'Earth', 'Saturn'], correctIndex: 2, topic: 'Space facts' },
      { text: 'Scientific method begins with ___.', options: ['observation/question', 'final conclusion', 'publishing', 'deleting data'], correctIndex: 0, topic: 'Science process' },
      { text: 'Metric prefix kilo- means ___', options: ['100', '1000', '10', '1/10'], correctIndex: 1, topic: 'Units' },
      { text: 'In a sequence: wash, cut, cook, serve. Step before serve?', options: ['cook', 'wash', 'cut', 'mix'], correctIndex: 0, topic: 'Order recall' },
      { text: 'Synonym pair: rapid = ___', options: ['quiet', 'tiny', 'fast', 'slow'], correctIndex: 2, topic: 'Vocabulary memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Grade 5 Memory Medium: Multi-Step Recall',
    description: 'Hold and retrieve linked details and ordered information.',
    questions: [
      { text: 'Remember code 4-9-2-7. What is the third digit?', options: ['2', '9', '4', '7'], correctIndex: 0, topic: 'Digit recall' },
      { text: 'Order of operations: parentheses, exponents, multiply/divide, then ___.', options: ['add/subtract', 'square roots', 'fractions only', 'rounding'], correctIndex: 0, topic: 'Math sequence' },
      { text: 'Water cycle order: evaporation, condensation, ___.', options: ['precipitation', 'photosynthesis', 'erosion', 'combustion'], correctIndex: 0, topic: 'Science cycle' },
      { text: 'If states of matter listed are solid, liquid, gas, what was second?', options: ['plasma', 'gas', 'solid', 'liquid'], correctIndex: 3, topic: 'Ordered list' },
      { text: 'Chunk memory: 305-812. Last chunk is ___.', options: ['312', '508', '812', '305'], correctIndex: 2, topic: 'Chunking' },
      { text: 'Pair recall: author-book, pilot-plane, chef-___.', options: ['kitchen', 'hospital', 'stadium', 'garage'], correctIndex: 0, topic: 'Association' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 5 Problem Solving Easy: One to Two Steps',
    description: 'Solve everyday word problems with clear operations.',
    questions: [
      { text: 'A class has 24 students in 3 equal groups. Students per group?', options: ['7', '9', '6', '8'], correctIndex: 3, topic: 'Division' },
      { text: 'A notebook costs $3. Buy 4 notebooks. Total cost?', options: ['$16', '$12', '$7', '$9'], correctIndex: 1, topic: 'Multiplication' },
      { text: 'A tank holds 50 L and currently has 18 L. Liters needed to fill?', options: ['32', '28', '22', '30'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Run 2 km each day for 5 days. Total distance?', options: ['8 km', '7 km', '10 km', '12 km'], correctIndex: 2, topic: 'Repeated addition' },
      { text: 'Recipe uses 2 cups flour for 1 batch. Flour for 3 batches?', options: ['4 cups', '5 cups', '6 cups', '3 cups'], correctIndex: 2, topic: 'Scaling' },
      { text: 'Start with 45 marbles, lose 19. Marbles left?', options: ['24', '28', '30', '26'], correctIndex: 3, topic: 'Difference' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Grade 5 Problem Solving Medium: Rates & Percents',
    description: 'Use ratio, average, and percent in multistep contexts.',
    questions: [
      { text: 'A car travels 150 miles in 3 hours. Average speed?', options: ['45 mph', '50 mph', '500 mph', '55 mph'], correctIndex: 1, topic: 'Rate' },
      { text: 'A shirt is $40 with 25% discount. Discount amount?', options: ['$8', '$10', '$15', '$12'], correctIndex: 1, topic: 'Percent discount' },
      { text: 'Scores are 18, 22, and 26. Mean score?', options: ['22', '20', '24', '66'], correctIndex: 0, topic: 'Average' },
      { text: 'Ratio of red to blue beads is 2:3. If blue is 12, red is ___', options: ['18', '8', '6', '10'], correctIndex: 1, topic: 'Ratio' },
      { text: 'A box has 60 apples. 15 are spoiled. What percent spoiled?', options: ['35%', '15%', '25%', '20%'], correctIndex: 2, topic: 'Percent' },
      { text: 'Temperature is 4 deg C and drops by 9 deg C. New temperature?', options: ['5 deg C', '-5 deg C', '-13 deg C', '13 deg C'], correctIndex: 1, topic: 'Integers' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 5 Critical Thinking Easy: Evidence Basics',
    description: 'Choose stronger evidence and clearer reasoning.',
    questions: [
      { text: 'Which is stronger evidence: measured data or a random guess?', options: ['rumor', 'measured data', 'either one', 'random guess'], correctIndex: 1, topic: 'Evidence' },
      { text: 'If only 3 people are surveyed, the sample is often ___', options: ['nationally representative', 'always perfect', 'proof of causation', 'too small'], correctIndex: 3, topic: 'Sampling' },
      { text: 'An ad uses a famous athlete to sell cereal. This is appeal to ___', options: ['fame/authority', 'scientific proof', 'math law', 'experiment control'], correctIndex: 0, topic: 'Persuasion' },
      { text: 'If statement says "all birds fly," penguins show the statement is ___', options: ['not always true', 'a measurement', 'always true', 'a math fact'], correctIndex: 0, topic: 'Counterexample' },
      { text: 'Best way to compare two plant foods is to keep everything same except ___.', options: ['sunlight and water both', 'plant food type', 'pot size and species', 'soil and light and water'], correctIndex: 1, topic: 'Fair comparison' },
      { text: 'A chart rises for 2 months. Claiming it will rise forever is ___', options: ['certainly correct', 'an overgeneralization', 'a direct measurement', 'a theorem'], correctIndex: 1, topic: 'Claims' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Grade 5 Critical Thinking Medium: Arguments & Data',
    description: 'Analyze claims, bias, and logic with structured evidence.',
    questions: [
      { text: 'Two variables move together. This proves ___', options: ['correlation, not causation', 'causation always', 'no relationship', 'theory is final'], correctIndex: 0, topic: 'Statistics reasoning' },
      { text: 'A website selling a product may be biased because it ___', options: ['uses words', 'is on the internet', 'has pictures', 'profits from your choice'], correctIndex: 3, topic: 'Source bias' },
      { text: 'Best rebuttal to "my friend liked it so it works for all" is ___', options: ['liking equals proof', 'friends are always correct', 'all users are identical', 'one example is not enough evidence'], correctIndex: 3, topic: 'Generalization' },
      { text: 'Which conclusion fits data best: test scores rose after tutoring in a large matched group?', options: ['tutoring never helps', 'tutoring likely helped', 'scores rose by luck only', 'no data was collected'], correctIndex: 1, topic: 'Inference' },
      { text: 'If an argument attacks the person instead of idea, it is ___', options: ['controlled variable method', 'strong evidence', 'statistical certainty', 'ad hominem style reasoning'], correctIndex: 3, topic: 'Argument quality' },
      { text: 'When new reliable evidence conflicts with your claim, best action is ___', options: ['hide data', 'ignore evidence', 'revise the claim', 'repeat claim louder'], correctIndex: 2, topic: 'Intellectual honesty' },
    ],
  }),
];
