import { buildQuiz } from '../utils.js';

const G = 'grade_2';

/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_2_PILOT_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 2 Science Easy: My World',
    description: 'Simple solids, liquids, and what plants need.',
    questions: [
      { text: 'Water at room temperature is a ___', options: ['rock', 'gas', 'solid', 'liquid'], correctIndex: 3, topic: 'States' },
      { text: 'A rock is a ___', options: ['liquid', 'solid', 'gas', 'sound'], correctIndex: 1, topic: 'States' },
      { text: 'Plants need sunlight and ___', options: ['candy', 'paint', 'water', 'shoes'], correctIndex: 2, topic: 'Plants' },
      { text: 'Daytime sky is often ___', options: ['underground', 'always green', 'made of metal', 'bright'], correctIndex: 3, topic: 'Sky' },
      { text: 'Fish live in ___', options: ['sand only', 'ice only', 'clouds', 'water'], correctIndex: 3, topic: 'Habitats' },
      { text: 'We use eyes to ___', options: ['dig', 'smell', 'see', 'hop'], correctIndex: 2, topic: 'Senses' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 2 Science Hard: Matter & Systems',
    description: 'Food chains, magnets, and the water cycle.',
    questions: [
      { text: 'Grass → rabbit → fox. Fox is a ___', options: ['producer', 'soil', 'sun', 'consumer'], correctIndex: 3, topic: 'Food chain' },
      { text: 'Evaporation then ___ forms clouds', options: ['gravity only', 'condensation', 'burning', 'magnetism'], correctIndex: 1, topic: 'Water cycle' },
      { text: 'Which is attracted to a magnet?', options: ['Plastic spoon', 'Iron nail', 'Paper cup', 'Wooden block'], correctIndex: 1, topic: 'Magnets' },
      { text: 'Sunlight is ___ energy for plants', options: ['light', 'plastic', 'sound', 'magnetic'], correctIndex: 0, topic: 'Energy' },
      { text: 'Ice melting to water is a ___ change', options: ['physical', 'sleeping', 'eating', 'counting'], correctIndex: 0, topic: 'Change' },
      { text: 'A fair test changes ___ variable', options: ['all at once', 'zero', 'ten', 'one'], correctIndex: 3, topic: 'Investigation' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 2 Math Medium: Add & Subtract',
    description: 'Two-digit addition and subtraction within 100.',
    questions: [
      { text: '45 + 23 = ?', options: ['78', '58', '48', '68'], correctIndex: 3, topic: 'Addition' },
      { text: '70 − 28 = ?', options: ['42', '98', '52', '32'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Which equals 100?', options: ['10 tens', '2 tens', '5 tens', '100 ones only wrong'], correctIndex: 0, topic: 'Place value' },
      { text: '4 × 5 = ?', options: ['15', '20', '45', '9'], correctIndex: 1, topic: 'Multiply' },
      { text: 'Half of 24 is ___', options: ['10', '48', '12', '14'], correctIndex: 2, topic: 'Equal parts' },
      { text: 'Compare: 56 ___ 65', options: ['=', '≠ only', '<', '>'], correctIndex: 2, topic: 'Compare' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 2 Math Hard: Stretch to 100',
    description: 'Regrouping, equal groups, and two-step problems.',
    questions: [
      { text: '58 + 37 = ?', options: ['75', '91', '95', '85'], correctIndex: 2, topic: 'Regrouping' },
      { text: '100 − 46 = ?', options: ['64', '146', '44', '54'], correctIndex: 3, topic: 'Subtract' },
      { text: '7 × 3 = ?', options: ['73', '10', '18', '21'], correctIndex: 3, topic: 'Multiply' },
      { text: '36 stickers shared by 4 friends. Each gets ___', options: ['9', '40', '10', '8'], correctIndex: 0, topic: 'Division' },
      { text: 'Had 50, spent 18, earned 5. Now ___', options: ['47', '37', '27', '33'], correctIndex: 1, topic: 'Two-step' },
      { text: 'Quarter + quarter + dime = ___ cents', options: ['25', '35', '60', '50'], correctIndex: 2, topic: 'Money' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 2 Patterns Easy: What Comes Next?',
    description: 'Simple repeating and growing patterns.',
    questions: [
      { text: '2, 4, 6, 8, ___', options: ['12', '10', '7', '9'], correctIndex: 1, topic: '+2' },
      { text: '🔴 🟢 🔴 🟢 ___', options: ['🟢', '🔴', '🟡', '⬛'], correctIndex: 1, topic: 'Repeat' },
      { text: '5, 10, 15, ___', options: ['16', '20', '25', '18'], correctIndex: 1, topic: 'Skip 5' },
      { text: 'A, B, C, D, ___', options: ['B', 'F', 'E', 'A'], correctIndex: 2, topic: 'Letters' },
      { text: '10, 9, 8, ___', options: ['11', '6', '7', '9'], correctIndex: 2, topic: 'Count back' },
      { text: 'Rule +1: 3, 4, 5, ___', options: ['4', '6', '5', '7'], correctIndex: 1, topic: 'Growing' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 2 Patterns Hard: Rules & Tables',
    description: '×2, +10, and two-rule patterns.',
    questions: [
      { text: '12, 22, 32, ___', options: ['33', '40', '52', '42'], correctIndex: 3, topic: '+10' },
      { text: '×2: 5, 10, 20, ___', options: ['25', '30', '15', '40'], correctIndex: 3, topic: 'Double' },
      { text: '3, 7, 11, 15, ___ (+4)', options: ['17', '18', '16', '19'], correctIndex: 3, topic: 'Rule' },
      { text: '100, 90, 80, 70, ___', options: ['85', '60', '50', '110'], correctIndex: 1, topic: 'Decrease' },
      { text: '2, 6, 18, ___ (×3 each step)', options: ['54', '20', '24', '36'], correctIndex: 0, topic: 'Multiply pattern' },
      { text: '🔵🔵🔴 🔵🔵🔴 ___', options: ['🔵🔵🔴', '🟢', '⬛', '🔴🔴🔵'], correctIndex: 0, topic: 'Block repeat' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 2 Memory Easy: Remember & Match',
    description: 'Short lists, pairs, and what comes next.',
    questions: [
      { text: 'Cat, dog, bird. Which is a pet bird?', options: ['Bird', 'Desk', 'Rock', 'Car'], correctIndex: 0, topic: 'Recall' },
      { text: 'Red, blue, red, blue, ___', options: ['Yellow', 'Black', 'Green', 'Red'], correctIndex: 3, topic: 'Pattern' },
      { text: 'Monday, Tuesday, ___', options: ['Friday', 'Sunday', 'March', 'Wednesday'], correctIndex: 3, topic: 'Days' },
      { text: '1, 2, 3 — number after 3 is ___', options: ['2', '1', '5', '4'], correctIndex: 3, topic: 'Count' },
      { text: 'Hat goes with ___', options: ['Head', 'Foot', 'Water', 'Sky'], correctIndex: 0, topic: 'Pairs' },
      { text: 'First, second, third. Next is ___', options: ['Last', 'Fourth', 'Zero', 'First'], correctIndex: 1, topic: 'Order' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 2 Memory Hard: Chunks & Sequences',
    description: 'Phone chunks, symbols, and multi-step recall.',
    questions: [
      { text: 'Phone 55-12-90 — middle chunk?', options: ['12', '90', '551', '55'], correctIndex: 0, topic: 'Chunking' },
      { text: '🔺=3, 🔺🔺=___', options: ['2', '6', '9', '3'], correctIndex: 1, topic: 'Symbols' },
      { text: 'Plan: mix → bake → cool. Third step?', options: ['Eat', 'Bake', 'Mix', 'Cool'], correctIndex: 3, topic: 'Procedure' },
      { text: '9, 7, 5, 3, ___', options: ['5', '4', '2', '1'], correctIndex: 3, topic: 'Count back' },
      { text: 'Saw A, B, C, B, A. Letter in middle?', options: ['D', 'A', 'C', 'B'], correctIndex: 2, topic: 'Scan' },
      { text: 'Zip code 20-45 — second part?', options: ['25', '45', '204', '20'], correctIndex: 1, topic: 'Chunks' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 2 Problems Easy: Stories & Drawings',
    description: 'Join, take apart, and compare within 20.',
    questions: [
      { text: '5 apples + 3 apples = ___', options: ['7', '2', '8', '9'], correctIndex: 2, topic: 'Join' },
      { text: '10 − 4 = ?', options: ['14', '6', '7', '5'], correctIndex: 1, topic: 'Take apart' },
      { text: 'Which has more: 7 or 4?', options: ['7', '4', '0', 'Same'], correctIndex: 0, topic: 'Compare' },
      { text: '2 groups of 3 stickers = ___', options: ['3', '6', '7', '5'], correctIndex: 1, topic: 'Groups' },
      { text: 'Sam has 9, gives 2. Left?', options: ['8', '6', '7', '11'], correctIndex: 2, topic: 'Give' },
      { text: 'Need 12, have 8. More needed?', options: ['20', '5', '3', '4'], correctIndex: 3, topic: 'Missing' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 2 Problems Hard: Multi-Step',
    description: 'Money, time, perimeter, and two-step logic.',
    questions: [
      { text: 'Had 45, spent 18, got 10. Now?', options: ['27', '73', '37', '47'], correctIndex: 2, topic: 'Two-step' },
      { text: 'Rectangle 6×4 — perimeter?', options: ['10', '24', '20', '8'], correctIndex: 2, topic: 'Perimeter' },
      { text: '72 − 28 = ?', options: ['46', '54', '44', '100'], correctIndex: 2, topic: 'Subtract' },
      { text: '30 ÷ 5 = ?', options: ['6', '7', '35', '5'], correctIndex: 0, topic: 'Divide' },
      { text: '3 dimes = ___ cents', options: ['20', '3', '30', '15'], correctIndex: 2, topic: 'Money' },
      { text: 'Start 1:15, wait 45 min. Time ___', options: ['1:30', '2:00', '2:15', '1:45'], correctIndex: 1, topic: 'Time' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 2 Thinking Easy: Ask Why',
    description: 'Compare choices, notice clues, and fair questions.',
    questions: [
      { text: 'Rainy day — best clue is ___', options: ['Hot sun only', 'Snow only', 'Clouds and rain', 'Wind only'], correctIndex: 2, topic: 'Clues' },
      { text: 'Which helps you decide: guess or measure?', options: ['Skip', 'Close eyes', 'Guess only', 'Measure'], correctIndex: 3, topic: 'Evidence' },
      { text: 'All dogs are animals. A puppy is a ___', options: ['Rock', 'Plant', 'Dog', 'Car'], correctIndex: 2, topic: 'Logic' },
      { text: 'Two answers — pick the one with a ___', options: ['Color only', 'Reason', 'Song', 'Joke'], correctIndex: 1, topic: 'Reason' },
      { text: 'Test plants with same water but different ___', options: ['Names', 'Shoes', 'Music', 'Light'], correctIndex: 3, topic: 'Fair test' },
      { text: 'Story says hero was brave. Brave means ___', options: ['Very loud', 'Not afraid to try', 'Tiny', 'Always sleeping'], correctIndex: 1, topic: 'Words' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 2 Thinking Hard: Evidence & Logic',
    description: 'Sources, if-then reasoning, and fair tests.',
    questions: [
      { text: 'Measured length beats a ___', options: ['Ruler', 'Wild guess', 'Desk', 'Pencil'], correctIndex: 1, topic: 'Evidence' },
      { text: 'Fair test changes ___ thing at a time', options: ['All', 'Ten', 'One', 'Zero'], correctIndex: 2, topic: 'Fair test' },
      { text: 'All squares are rectangles. Every rectangle a square?', options: ['No', 'Always', 'Never', 'Yes'], correctIndex: 0, topic: 'Logic' },
      { text: 'Dark sky at 8 pm suggests ___', options: ['Night', 'Morning', 'Lunch', 'Noon'], correctIndex: 0, topic: 'Infer' },
      { text: 'Strongest weather fact comes from ___', options: ['Station data', 'A cartoon', 'A guess', 'A dream'], correctIndex: 0, topic: 'Sources' },
      { text: 'If A > B and B > C, then A ___ C', options: ['≠', '=', '<', '>'], correctIndex: 3, topic: 'Chain' },
    ],
  }),
];
