import { buildQuiz } from '../utils.js';

const G = 'grade_4';

/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_4_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 4 Math Easy: Core Operations',
    description: 'Basic multiplication, fractions, and place value review.',
    questions: [
      { text: '6 x 7 = ?', options: ['42', '36', '48', '56'], correctIndex: 0, topic: 'Multiply' },
      { text: 'Which fraction is equal to 1/2?', options: ['2/4', '2/3', '3/4', '1/3'], correctIndex: 0, topic: 'Fractions' },
      { text: '900 + 80 + 6 = ?', options: ['986', '896', '968', '980'], correctIndex: 0, topic: 'Place value' },
      { text: '48 - 19 = ?', options: ['29', '31', '27', '39'], correctIndex: 0, topic: 'Subtract' },
      { text: 'Which is greater?', options: ['0.7', '0.6', 'They are equal', '0.06'], correctIndex: 0, topic: 'Decimals' },
      { text: 'Perimeter of a square with side 5 is ___', options: ['20', '25', '10', '15'], correctIndex: 0, topic: 'Perimeter' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 4 Math Hard: Multi-Step Reasoning',
    description: 'Advanced fraction and multi-step number challenges.',
    questions: [
      { text: '3/4 + 2/8 = ?', options: ['1', '5/8', '7/8', '3/8'], correctIndex: 0, topic: 'Fraction addition' },
      { text: 'A number is 6 times 9, then minus 17. Result?', options: ['37', '41', '45', '29'], correctIndex: 0, topic: 'Order of operations' },
      { text: '1.25 + 0.8 = ?', options: ['2.05', '2.5', '1.33', '2.13'], correctIndex: 0, topic: 'Decimal sum' },
      { text: 'LCM of 6 and 8 is ___', options: ['24', '12', '18', '48'], correctIndex: 0, topic: 'Multiples' },
      { text: 'A rectangle has area 54 and width 6. Length?', options: ['9', '8', '7', '10'], correctIndex: 0, topic: 'Area inverse' },
      { text: 'Round 4,786 to nearest hundred.', options: ['4,800', '4,700', '4,790', '5,000'], correctIndex: 0, topic: 'Rounding' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 4 Science Easy: Earth Basics',
    description: 'Simple concepts in energy, matter, and Earth systems.',
    questions: [
      { text: 'The Sun is our main source of ___', options: ['light and heat', 'plastic', 'wind only', 'soil'], correctIndex: 0, topic: 'Energy' },
      { text: 'Water vapor is water in ___ state', options: ['gas', 'solid', 'liquid', 'metal'], correctIndex: 0, topic: 'States of matter' },
      { text: 'Plants make food using sunlight in ___', options: ['photosynthesis', 'erosion', 'condensation', 'friction'], correctIndex: 0, topic: 'Plants' },
      { text: 'Rocks broken into smaller pieces by wind is ___', options: ['weathering', 'melting', 'evaporation', 'orbiting'], correctIndex: 0, topic: 'Earth changes' },
      { text: 'An animal that eats plants and animals is an ___', options: ['omnivore', 'herbivore', 'producer', 'decomposer only'], correctIndex: 0, topic: 'Food relationships' },
      { text: 'A closed electric path is called a ___', options: ['circuit', 'battery', 'magnet', 'switch'], correctIndex: 0, topic: 'Electricity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 4 Science Hard: Systems & Evidence',
    description: 'Apply scientific ideas to cycles, forces, and experiments.',
    questions: [
      { text: 'In the water cycle, vapor cools into clouds by ___', options: ['condensation', 'evaporation', 'precipitation', 'collection'], correctIndex: 0, topic: 'Water cycle' },
      { text: 'If two objects have equal mass, stronger force gives ___ acceleration', options: ['greater', 'less', 'no', 'negative'], correctIndex: 0, topic: 'Forces' },
      { text: 'A producer in a forest food web is likely a ___', options: ['tree', 'owl', 'wolf', 'fungus'], correctIndex: 0, topic: 'Ecosystems' },
      { text: 'Best way to test fertilizer effect is to change only the ___', options: ['fertilizer amount', 'pot size, seed type, and water too', 'weather outside', 'measurement tool each day'], correctIndex: 0, topic: 'Fair test' },
      { text: 'The Moon appears to change shape because of ___', options: ['its position with Earth and Sun', 'Earth shadow every night', 'cloud shapes', 'Moon spinning faster'], correctIndex: 0, topic: 'Moon phases' },
      { text: 'A material that is attracted to magnets is often ___', options: ['iron', 'rubber', 'glass', 'wood'], correctIndex: 0, topic: 'Magnetism' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 4 Patterns Easy: Number Rules',
    description: 'Identify simple arithmetic and geometric patterns.',
    questions: [
      { text: '7, 12, 17, 22, ___', options: ['27', '26', '28', '25'], correctIndex: 0, topic: '+5' },
      { text: '3, 6, 12, 24, ___', options: ['48', '36', '30', '42'], correctIndex: 0, topic: 'x2' },
      { text: '0.1, 0.2, 0.3, ___', options: ['0.4', '0.5', '0.13', '1.0'], correctIndex: 0, topic: 'Decimals' },
      { text: '25, 20, 15, 10, ___', options: ['5', '0', '8', '12'], correctIndex: 0, topic: '-5' },
      { text: 'Input 2 -> 6 and input 5 -> 15. Rule is ___', options: ['multiply by 3', 'add 3', 'subtract 3', 'square'], correctIndex: 0, topic: 'Function rule' },
      { text: '4, 9, 16, 25, ___', options: ['36', '30', '35', '49'], correctIndex: 0, topic: 'Square numbers' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 4 Patterns Hard: Multi-Rule Sequences',
    description: 'Analyze alternating and structured sequence behavior.',
    questions: [
      { text: '2, 5, 11, 23, ___', options: ['47', '35', '46', '44'], correctIndex: 0, topic: 'x2 +1' },
      { text: '1, 4, 9, 16, 25, ___', options: ['36', '30', '49', '35'], correctIndex: 0, topic: 'Square sequence' },
      { text: '64, 32, 16, 8, ___', options: ['4', '2', '6', '12'], correctIndex: 0, topic: 'Halving' },
      { text: 'Term rule: 3n + 2. For n=6, term is ___', options: ['20', '18', '24', '14'], correctIndex: 0, topic: 'Algebraic pattern' },
      { text: 'Alternating pattern 10, 7, 14, 11, 22, 19, ___', options: ['38', '26', '21', '30'], correctIndex: 0, topic: 'Alternate operations' },
      { text: 'A shape adds 3 sides each step: 4, 7, 10, ___', options: ['13', '12', '14', '11'], correctIndex: 0, topic: 'Geometric growth' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 4 Memory Easy: Facts & Order',
    description: 'Recall lists, definitions, and simple ordered information.',
    questions: [
      { text: 'Order the water cycle: evaporation, condensation, ___', options: ['precipitation', 'photosynthesis', 'erosion', 'rotation'], correctIndex: 0, topic: 'Cycle order' },
      { text: 'A right angle measures ___ degrees', options: ['90', '45', '180', '60'], correctIndex: 0, topic: 'Math fact' },
      { text: 'The largest planet in our solar system is ___', options: ['Jupiter', 'Mars', 'Earth', 'Venus'], correctIndex: 0, topic: 'Space facts' },
      { text: 'In a food chain, plants are called ___', options: ['producers', 'consumers', 'predators', 'prey'], correctIndex: 0, topic: 'Vocabulary' },
      { text: 'Compass directions go N, E, S, ___', options: ['W', 'N', 'E', 'S'], correctIndex: 0, topic: 'Geography recall' },
      { text: 'Mean of 4 and 8 is ___', options: ['6', '4', '8', '12'], correctIndex: 0, topic: 'Data recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 4 Memory Hard: Multi-Part Recall',
    description: 'Remember precise facts, sequences, and linked details.',
    questions: [
      { text: 'Prime numbers under 10 are 2, 3, 5, and ___', options: ['7', '9', '11', '1'], correctIndex: 0, topic: 'Number facts' },
      { text: 'Order planets from Sun starts Mercury, Venus, ___', options: ['Earth', 'Mars', 'Jupiter', 'Saturn'], correctIndex: 0, topic: 'Space order' },
      { text: 'A triangle has angle sum of ___ degrees', options: ['180', '90', '360', '270'], correctIndex: 0, topic: 'Geometry recall' },
      { text: '1 kilometer equals ___ meters', options: ['1,000', '100', '10,000', '100,000'], correctIndex: 0, topic: 'Measurement facts' },
      { text: 'In place value, digit 6 in 36,482 is worth ___', options: ['6,000', '600', '60', '6'], correctIndex: 0, topic: 'Place value memory' },
      { text: 'A sentence with a command ends with ___ most often', options: ['a period', 'a question mark', 'a comma', 'quotation marks'], correctIndex: 0, topic: 'Language recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 4 Problem Solving Easy: One- and Two-Step',
    description: 'Solve practical arithmetic and measurement situations.',
    questions: [
      { text: 'A box has 24 pencils. 8 are used. How many left?', options: ['16', '18', '14', '12'], correctIndex: 0, topic: 'Subtract in context' },
      { text: '3 bags with 6 apples each means ___ apples total', options: ['18', '9', '12', '24'], correctIndex: 0, topic: 'Equal groups' },
      { text: 'A rope is 15 m. Cut off 4 m. Remaining?', options: ['11 m', '9 m', '19 m', '10 m'], correctIndex: 0, topic: 'Measurement' },
      { text: 'A movie starts 2:30 PM and lasts 1 hour. Ends at ___', options: ['3:30 PM', '3:00 PM', '4:30 PM', '2:31 PM'], correctIndex: 0, topic: 'Elapsed time' },
      { text: '$20 buys 4 notebooks equally. One notebook costs ___', options: ['$5', '$4', '$6', '$8'], correctIndex: 0, topic: 'Unit rate' },
      { text: 'Rectangle 7 by 3 has area ___', options: ['21', '10', '28', '14'], correctIndex: 0, topic: 'Area' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 4 Problem Solving Hard: Strategy Challenges',
    description: 'Tackle multi-step, ratio-like, and logical word problems.',
    questions: [
      { text: 'A store sells 3 pens for $6. Cost of 8 pens?', options: ['$16', '$12', '$18', '$14'], correctIndex: 0, topic: 'Proportional reasoning' },
      { text: 'A runner does 250 m per lap. How far in 7 laps?', options: ['1,750 m', '1,500 m', '1,250 m', '2,000 m'], correctIndex: 0, topic: 'Multiply and convert' },
      { text: 'Class has 28 students. 3/4 are present. Present students?', options: ['21', '20', '24', '18'], correctIndex: 0, topic: 'Fraction of set' },
      { text: 'A tank holds 90 L. It is filled at 15 L/hour. Time to fill?', options: ['6 hours', '5 hours', '7 hours', '4 hours'], correctIndex: 0, topic: 'Rate' },
      { text: 'Perimeter 30 with width 6. Rectangle length?', options: ['9', '12', '15', '6'], correctIndex: 0, topic: 'Perimeter equation' },
      { text: 'Number puzzle: think of 8, double it, subtract 5, divide by 3. Result?', options: ['11/3', '7', '9', '5'], correctIndex: 0, topic: 'Multi-step operations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 4 Critical Thinking Easy: Claims & Clues',
    description: 'Distinguish facts, opinions, and stronger evidence.',
    questions: [
      { text: '"This backpack weighs 2 kg" is a ___', options: ['fact', 'opinion', 'question', 'guess'], correctIndex: 0, topic: 'Fact vs opinion' },
      { text: 'Best evidence for rainfall yesterday is ___', options: ['weather record', 'a friend guessing', 'a drawing', 'a joke'], correctIndex: 0, topic: 'Evidence sources' },
      { text: 'If all squares have 4 sides, a square has ___ sides', options: ['4', '3', '5', '6'], correctIndex: 0, topic: 'Deduction' },
      { text: 'In an experiment, changing one thing at a time makes it ___', options: ['fair', 'unfair', 'random', 'impossible'], correctIndex: 0, topic: 'Fair test' },
      { text: 'Which question is strongest for research?', options: ['What evidence supports this?', 'Do I like this?', 'Who is louder?', 'Is it colorful?'], correctIndex: 0, topic: 'Question quality' },
      { text: 'A map with scale helps estimate real ___', options: ['distance', 'temperature', 'taste', 'smell'], correctIndex: 0, topic: 'Tool use' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 4 Critical Thinking Hard: Logic & Evaluation',
    description: 'Evaluate arguments, detect weak reasoning, and infer correctly.',
    questions: [
      { text: 'Claim: "Plants grow faster with light." Best support is ___', options: ['data from controlled experiments', 'one photo', 'a single guess', 'a story without measurements'], correctIndex: 0, topic: 'Argument strength' },
      { text: 'If A > B and B > C, then ___', options: ['A > C', 'A < C', 'A = C', 'cannot tell'], correctIndex: 0, topic: 'Transitive logic' },
      { text: 'A survey asks only basketball fans about best sport. This is ___', options: ['biased sampling', 'random sampling', 'double checking', 'fair testing'], correctIndex: 0, topic: 'Bias' },
      { text: 'Which conclusion is valid? "All mammals breathe air. Whales are mammals."', options: ['Whales breathe air', 'Whales are fish', 'All air breathers are whales', 'Mammals live only on land'], correctIndex: 0, topic: 'Syllogism' },
      { text: 'When two explanations fit, choose the one with ___', options: ['more reliable evidence', 'louder voice', 'shorter sentence', 'more colors'], correctIndex: 0, topic: 'Evidence weighting' },
      { text: 'A graph axis starts at 90 instead of 0 and exaggerates change. This is ___', options: ['misleading presentation', 'exactly neutral display', 'invalid graph type', 'perfectly random'], correctIndex: 0, topic: 'Data interpretation' },
    ],
  }),
];
