import { buildQuiz } from '../utils.js';

const G = 'grade_5';

/** Easy + medium tiers for Grade 5 adaptive ladder (hard lives in grade_5.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_5_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 5 Math Easy: Fraction Basics',
    description: 'Core fraction, decimal, and whole-number skills.',
    questions: [
      { text: '3/5 + 1/5 = ?', options: ['4/5', '4/10', '3/10', '2/5'], correctIndex: 0, topic: 'Fractions' },
      { text: '0.7 + 0.2 = ?', options: ['0.9', '0.72', '0.5', '0.8'], correctIndex: 0, topic: 'Decimals' },
      { text: '6 x 7 = ?', options: ['42', '36', '48', '56'], correctIndex: 0, topic: 'Multiplication' },
      { text: 'Which is greater: 0.45 or 0.4?', options: ['0.45', '0.4', 'They are equal', 'Cannot tell'], correctIndex: 0, topic: 'Compare decimals' },
      { text: '35 / 5 = ?', options: ['7', '5', '6', '8'], correctIndex: 0, topic: 'Division' },
      { text: 'Perimeter of a rectangle 8 cm by 3 cm?', options: ['22 cm', '24 cm', '11 cm', '16 cm'], correctIndex: 0, topic: 'Perimeter' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 5 Math Medium: Decimals & Volume Prep',
    description: 'Multi-step fraction/decimal work and volume setup.',
    questions: [
      { text: '2.4 + 1.35 = ?', options: ['3.75', '3.59', '2.59', '3.15'], correctIndex: 0, topic: 'Decimal addition' },
      { text: '5/6 - 1/6 = ?', options: ['2/3', '4/12', '5/12', '1/3'], correctIndex: 0, topic: 'Fraction subtraction' },
      { text: 'A box is 4 cm x 3 cm x 2 cm. Volume?', options: ['24 cm^3', '12 cm^2', '18 cm^3', '9 cm^3'], correctIndex: 0, topic: 'Volume' },
      { text: '0.8 x 5 = ?', options: ['4', '0.4', '13', '3.5'], correctIndex: 0, topic: 'Decimal multiplication' },
      { text: 'What is 30% of 50?', options: ['15', '20', '10', '25'], correctIndex: 0, topic: 'Percent' },
      { text: '2 + 6 x 3 = ?', options: ['20', '24', '26', '18'], correctIndex: 0, topic: 'Order of operations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 5 Science Easy: Matter & Life',
    description: 'Foundational ideas in mixtures, cells, and ecosystems.',
    questions: [
      { text: 'Water changing to ice is a ___ change.', options: ['physical', 'chemical', 'permanent', 'biological'], correctIndex: 0, topic: 'Matter changes' },
      { text: 'The nucleus is found in a ___', options: ['cell', 'planet', 'cloud', 'rock'], correctIndex: 0, topic: 'Cells' },
      { text: 'Plants make food by ___', options: ['photosynthesis', 'evaporation', 'erosion', 'condensation'], correctIndex: 0, topic: 'Plants' },
      { text: 'A rabbit is most likely a ___ in a food chain.', options: ['consumer', 'producer', 'decomposer', 'mineral'], correctIndex: 0, topic: 'Ecosystems' },
      { text: 'Earth takes about ___ to orbit the Sun.', options: ['1 year', '1 month', '1 day', '10 years'], correctIndex: 0, topic: 'Space' },
      { text: 'Which material is usually an electrical conductor?', options: ['copper', 'rubber', 'plastic', 'wood'], correctIndex: 0, topic: 'Electricity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Grade 5 Science Medium: Systems & Evidence',
    description: 'Apply science ideas to processes and observations.',
    questions: [
      { text: 'In photosynthesis, plants use light, water, and ___.', options: ['carbon dioxide', 'oxygen only', 'salt', 'soil only'], correctIndex: 0, topic: 'Photosynthesis' },
      { text: 'When vinegar reacts with baking soda, gas forms. This is a ___ change.', options: ['chemical', 'physical', 'shape-only', 'reversible-only'], correctIndex: 0, topic: 'Chemical change' },
      { text: 'The heart is part of which body system?', options: ['circulatory system', 'digestive system', 'skeletal system', 'nervous system'], correctIndex: 0, topic: 'Human body' },
      { text: 'A food chain starts with energy from the ___.', options: ['Sun', 'Moon', 'soil', 'wind'], correctIndex: 0, topic: 'Energy flow' },
      { text: 'Why do we see different moon phases?', options: ['Different sunlit portions are visible', 'The Moon changes size', 'Clouds cover parts permanently', 'Earth glows differently each week'], correctIndex: 0, topic: 'Moon phases' },
      { text: 'Best way to test if fertilizer helps growth is to change only ___.', options: ['fertilizer amount', 'plant type and water', 'soil and light together', 'everything at once'], correctIndex: 0, topic: 'Fair test' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 5 Patterns Easy: Number Rules',
    description: 'Recognize and continue arithmetic and visual patterns.',
    questions: [
      { text: '4, 8, 12, 16, ___', options: ['20', '18', '22', '24'], correctIndex: 0, topic: 'Add 4' },
      { text: '2, 4, 8, 16, ___', options: ['32', '24', '20', '18'], correctIndex: 0, topic: 'Multiply by 2' },
      { text: 'A, C, E, G, ___', options: ['I', 'H', 'J', 'F'], correctIndex: 0, topic: 'Letter skip' },
      { text: '0.1, 0.2, 0.3, ___', options: ['0.4', '0.5', '0.35', '0.45'], correctIndex: 0, topic: 'Decimal sequence' },
      { text: '5, 10, 15, 20, ___', options: ['25', '22', '30', '24'], correctIndex: 0, topic: 'Skip counting' },
      { text: 'Square, circle, square, circle, ___', options: ['square', 'triangle', 'circle', 'rectangle'], correctIndex: 0, topic: 'Alternating pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Grade 5 Patterns Medium: Expressions & Coordinates',
    description: 'Infer deeper rules from tables, pairs, and formulas.',
    questions: [
      { text: '3, 6, 11, 18, ___', options: ['27', '25', '24', '29'], correctIndex: 0, topic: 'Increasing differences' },
      { text: 'If rule is y = 2x + 1, when x = 4, y = ___', options: ['9', '8', '7', '10'], correctIndex: 0, topic: 'Algebraic rule' },
      { text: '(1,3), (2,6), (3,9), (4,___)', options: ['12', '10', '11', '13'], correctIndex: 0, topic: 'Coordinate pattern' },
      { text: '1, 4, 9, 16, 25, ___', options: ['36', '30', '35', '49'], correctIndex: 0, topic: 'Square numbers' },
      { text: 'Pattern: start at 100, subtract 7 each step. Third term is ___', options: ['86', '93', '79', '84'], correctIndex: 0, topic: 'Rule application' },
      { text: '2, -2, 2, -2, ___', options: ['2', '-4', '0', '-2'], correctIndex: 0, topic: 'Alternating signs' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 5 Memory Easy: Facts & Sequences',
    description: 'Recall key facts, ordered steps, and basic mnemonics.',
    questions: [
      { text: '8 x 9 = ?', options: ['72', '63', '81', '79'], correctIndex: 0, topic: 'Math facts' },
      { text: 'Planets near the Sun start Mercury, Venus, ___.', options: ['Earth', 'Mars', 'Jupiter', 'Saturn'], correctIndex: 0, topic: 'Space facts' },
      { text: 'Scientific method begins with ___.', options: ['observation/question', 'final conclusion', 'publishing', 'deleting data'], correctIndex: 0, topic: 'Science process' },
      { text: 'Metric prefix kilo- means ___', options: ['1000', '100', '10', '1/10'], correctIndex: 0, topic: 'Units' },
      { text: 'In a sequence: wash, cut, cook, serve. Step before serve?', options: ['cook', 'wash', 'cut', 'mix'], correctIndex: 0, topic: 'Order recall' },
      { text: 'Synonym pair: rapid = ___', options: ['fast', 'slow', 'quiet', 'tiny'], correctIndex: 0, topic: 'Vocabulary memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Grade 5 Memory Medium: Multi-Step Recall',
    description: 'Hold and retrieve linked details and ordered information.',
    questions: [
      { text: 'Remember code 4-9-2-7. What is the third digit?', options: ['2', '9', '7', '4'], correctIndex: 0, topic: 'Digit recall' },
      { text: 'Order of operations: parentheses, exponents, multiply/divide, then ___.', options: ['add/subtract', 'square roots', 'fractions only', 'rounding'], correctIndex: 0, topic: 'Math sequence' },
      { text: 'Water cycle order: evaporation, condensation, ___.', options: ['precipitation', 'photosynthesis', 'erosion', 'combustion'], correctIndex: 0, topic: 'Science cycle' },
      { text: 'If states of matter listed are solid, liquid, gas, what was second?', options: ['liquid', 'solid', 'gas', 'plasma'], correctIndex: 0, topic: 'Ordered list' },
      { text: 'Chunk memory: 305-812. Last chunk is ___.', options: ['812', '305', '312', '508'], correctIndex: 0, topic: 'Chunking' },
      { text: 'Pair recall: author-book, pilot-plane, chef-___.', options: ['kitchen', 'hospital', 'stadium', 'garage'], correctIndex: 0, topic: 'Association' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 5 Problem Solving Easy: One to Two Steps',
    description: 'Solve everyday word problems with clear operations.',
    questions: [
      { text: 'A class has 24 students in 3 equal groups. Students per group?', options: ['8', '6', '9', '7'], correctIndex: 0, topic: 'Division' },
      { text: 'A notebook costs $3. Buy 4 notebooks. Total cost?', options: ['$12', '$7', '$9', '$16'], correctIndex: 0, topic: 'Multiplication' },
      { text: 'A tank holds 50 L and currently has 18 L. Liters needed to fill?', options: ['32', '28', '22', '30'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Run 2 km each day for 5 days. Total distance?', options: ['10 km', '7 km', '12 km', '8 km'], correctIndex: 0, topic: 'Repeated addition' },
      { text: 'Recipe uses 2 cups flour for 1 batch. Flour for 3 batches?', options: ['6 cups', '5 cups', '4 cups', '3 cups'], correctIndex: 0, topic: 'Scaling' },
      { text: 'Start with 45 marbles, lose 19. Marbles left?', options: ['26', '24', '28', '30'], correctIndex: 0, topic: 'Difference' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Grade 5 Problem Solving Medium: Rates & Percents',
    description: 'Use ratio, average, and percent in multistep contexts.',
    questions: [
      { text: 'A car travels 150 miles in 3 hours. Average speed?', options: ['50 mph', '45 mph', '55 mph', '500 mph'], correctIndex: 0, topic: 'Rate' },
      { text: 'A shirt is $40 with 25% discount. Discount amount?', options: ['$10', '$15', '$8', '$12'], correctIndex: 0, topic: 'Percent discount' },
      { text: 'Scores are 18, 22, and 26. Mean score?', options: ['22', '20', '24', '66'], correctIndex: 0, topic: 'Average' },
      { text: 'Ratio of red to blue beads is 2:3. If blue is 12, red is ___', options: ['8', '6', '10', '18'], correctIndex: 0, topic: 'Ratio' },
      { text: 'A box has 60 apples. 15 are spoiled. What percent spoiled?', options: ['25%', '15%', '20%', '35%'], correctIndex: 0, topic: 'Percent' },
      { text: 'Temperature is 4 deg C and drops by 9 deg C. New temperature?', options: ['-5 deg C', '-13 deg C', '5 deg C', '13 deg C'], correctIndex: 0, topic: 'Integers' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 5 Critical Thinking Easy: Evidence Basics',
    description: 'Choose stronger evidence and clearer reasoning.',
    questions: [
      { text: 'Which is stronger evidence: measured data or a random guess?', options: ['measured data', 'random guess', 'either one', 'rumor'], correctIndex: 0, topic: 'Evidence' },
      { text: 'If only 3 people are surveyed, the sample is often ___', options: ['too small', 'always perfect', 'nationally representative', 'proof of causation'], correctIndex: 0, topic: 'Sampling' },
      { text: 'An ad uses a famous athlete to sell cereal. This is appeal to ___', options: ['fame/authority', 'scientific proof', 'math law', 'experiment control'], correctIndex: 0, topic: 'Persuasion' },
      { text: 'If statement says "all birds fly," penguins show the statement is ___', options: ['not always true', 'always true', 'a math fact', 'a measurement'], correctIndex: 0, topic: 'Counterexample' },
      { text: 'Best way to compare two plant foods is to keep everything same except ___.', options: ['plant food type', 'sunlight and water both', 'pot size and species', 'soil and light and water'], correctIndex: 0, topic: 'Fair comparison' },
      { text: 'A chart rises for 2 months. Claiming it will rise forever is ___', options: ['an overgeneralization', 'certainly correct', 'a theorem', 'a direct measurement'], correctIndex: 0, topic: 'Claims' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Grade 5 Critical Thinking Medium: Arguments & Data',
    description: 'Analyze claims, bias, and logic with structured evidence.',
    questions: [
      { text: 'Two variables move together. This proves ___', options: ['correlation, not causation', 'causation always', 'theory is final', 'no relationship'], correctIndex: 0, topic: 'Statistics reasoning' },
      { text: 'A website selling a product may be biased because it ___', options: ['profits from your choice', 'uses words', 'has pictures', 'is on the internet'], correctIndex: 0, topic: 'Source bias' },
      { text: 'Best rebuttal to "my friend liked it so it works for all" is ___', options: ['one example is not enough evidence', 'friends are always correct', 'liking equals proof', 'all users are identical'], correctIndex: 0, topic: 'Generalization' },
      { text: 'Which conclusion fits data best: test scores rose after tutoring in a large matched group?', options: ['tutoring likely helped', 'tutoring never helps', 'scores rose by luck only', 'no data was collected'], correctIndex: 0, topic: 'Inference' },
      { text: 'If an argument attacks the person instead of idea, it is ___', options: ['ad hominem style reasoning', 'strong evidence', 'controlled variable method', 'statistical certainty'], correctIndex: 0, topic: 'Argument quality' },
      { text: 'When new reliable evidence conflicts with your claim, best action is ___', options: ['revise the claim', 'ignore evidence', 'hide data', 'repeat claim louder'], correctIndex: 0, topic: 'Intellectual honesty' },
    ],
  }),
];
