import { buildQuiz } from '../utils.js';

const G = 'grade_3';

/** Easy + hard tiers for Grade 3 adaptive ladder (medium is in grade_3.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_3_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 3 Math Easy: Facts & Fractions Basics',
    description: 'Simple multiplication facts and unit-fraction understanding.',
    questions: [
      { text: '3 × 4 = ?', options: ['16', '10', '7', '12'], correctIndex: 3, topic: 'Multiplication facts' },
      { text: '2 × 6 = ?', options: ['12', '8', '14', '10'], correctIndex: 0, topic: 'Multiplication facts' },
      { text: '1/2 of 10 = ?', options: ['10', '8', '5', '2'], correctIndex: 2, topic: 'Fractions' },
      { text: 'Which is a unit fraction?', options: ['2/4', '3/5', '1/4', '4/4'], correctIndex: 2, topic: 'Unit fractions' },
      { text: '4 × 5 = ?', options: ['20', '9', '25', '18'], correctIndex: 0, topic: 'Multiplication facts' },
      { text: '1/3 of 12 = ?', options: ['3', '4', '6', '9'], correctIndex: 1, topic: 'Fractions' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 3 Math Hard: Multi-Step Multiplication & Fractions',
    description: 'Two-step operations, area/perimeter reasoning, and fraction comparison.',
    questions: [
      { text: '(6 × 4) + 8 = ?', options: ['30', '32', '28', '34'], correctIndex: 1, topic: 'Two-step operations' },
      { text: 'A rectangle is 7 by 3. Area is ___', options: ['21', '14', '24', '10'], correctIndex: 0, topic: 'Area' },
      { text: 'A rectangle is 7 by 3. Perimeter is ___', options: ['21', '10', '14', '20'], correctIndex: 3, topic: 'Perimeter' },
      { text: 'Which is greater?', options: ['3/4', 'They are equal', '2/3', '1/2'], correctIndex: 0, topic: 'Fraction comparison' },
      { text: '48 ÷ 6 + 9 = ?', options: ['15', '16', '17', '18'], correctIndex: 2, topic: 'Division then addition' },
      { text: 'Nina has 5 packs of 8 stickers and gives away 9. Left?', options: ['33', '40', '29', '31'], correctIndex: 3, topic: 'Word problem' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 3 Science Easy: Forces & Life Cycles',
    description: 'Core ideas about pushes, pulls, and living things.',
    questions: [
      { text: 'Opening a drawer is mostly a ___', options: ['magnet', 'float', 'push', 'pull'], correctIndex: 3, topic: 'Forces' },
      { text: 'Pushing a swing forward is a ___', options: ['push', 'freeze', 'friction', 'pull'], correctIndex: 0, topic: 'Forces' },
      { text: 'A butterfly starts as a ___', options: ['frog', 'egg', 'rock', 'seed'], correctIndex: 1, topic: 'Life cycle' },
      { text: 'Plants make food mostly in the ___', options: ['flowers only', 'soil', 'roots', 'leaves'], correctIndex: 3, topic: 'Plant parts' },
      { text: 'The skeleton helps your body by ___', options: ['supporting it', 'cooling food', 'changing weather', 'making rain'], correctIndex: 0, topic: 'Body systems' },
      { text: 'Friction usually makes moving objects ___', options: ['disappear', 'speed up forever', 'float', 'slow down'], correctIndex: 3, topic: 'Friction' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 3 Science Hard: Systems, Evidence & Experiments',
    description: 'Multi-step cause/effect and fair-test reasoning.',
    questions: [
      { text: 'In a fair plant test, what should you change?', options: ['only one variable', 'no measurements', 'the hypothesis only', 'every variable'], correctIndex: 0, topic: 'Fair tests' },
      { text: 'If two toy cars roll down ramps, what best shows which is faster?', options: ['car name', 'time each run', 'car color', 'driver opinion'], correctIndex: 1, topic: 'Evidence' },
      { text: 'Food gives muscles energy through the ___ system first', options: ['skeletal', 'solar', 'digestive', 'weather'], correctIndex: 2, topic: 'Body systems' },
      { text: 'If soil lacks water, most seeds will ___', options: ['multiply instantly', 'grow faster', 'turn to rocks', 'grow poorly'], correctIndex: 3, topic: 'Plant needs' },
      { text: 'Which setup best tests friction?', options: ['different toys on different ramps', 'same toy with no measuring', 'same toy on rough vs smooth surface', 'guessing by sight'], correctIndex: 2, topic: 'Experiment design' },
      { text: 'A longer shadow at noon usually means the light source is ___', options: ['at a lower angle', 'colder air', 'stronger wind', 'inside the object'], correctIndex: 0, topic: 'Light and shadows' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 3 Pattern Recognition Easy: Skip & Rule Basics',
    description: 'Identify simple number and input-output patterns.',
    questions: [
      { text: '4, 8, 12, 16, ___', options: ['24', '20', '18', '22'], correctIndex: 1, topic: 'Skip counting by 4' },
      { text: '2, 5, 8, 11, ___', options: ['13', '16', '15', '14'], correctIndex: 3, topic: '+3 pattern' },
      { text: 'Rule: +2. Input 7, output ___', options: ['14', '10', '9', '5'], correctIndex: 2, topic: 'Function rule' },
      { text: '1/4, 2/4, 3/4, ___', options: ['1/2', '2/3', '5/4', '4/4'], correctIndex: 3, topic: 'Fraction sequence' },
      { text: '30, 25, 20, 15, ___', options: ['18', '10', '12', '5'], correctIndex: 1, topic: '-5 pattern' },
      { text: '6, 12, 18, ___', options: ['30', '20', '24', '22'], correctIndex: 2, topic: 'Multiples of 6' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 3 Pattern Recognition Hard: Multi-Rule Sequences',
    description: 'Analyze alternating, multiplicative, and function-machine patterns.',
    questions: [
      { text: '2, 6, 3, 9, 4, 12, ___, ___', options: ['5, 14', '6, 18', '4, 16', '5, 15'], correctIndex: 3, topic: 'Alternating related pattern' },
      { text: 'Rule: ×2 then +1. Input 7 gives ___', options: ['15', '13', '16', '14'], correctIndex: 0, topic: 'Two-step function' },
      { text: '81, 27, 9, 3, ___', options: ['12', '0', '6', '1'], correctIndex: 3, topic: 'Divide by 3' },
      { text: '1/2, 2/3, 3/4, 4/5, ___', options: ['6/5', '1', '5/6', '4/6'], correctIndex: 2, topic: 'Fraction numerator/denominator rule' },
      { text: '5, 8, 14, 23, ___', options: ['34', '32', '30', '35'], correctIndex: 3, topic: 'Increasing differences' },
      { text: 'Input 3 -> 11 and input 5 -> 17. Rule is ___', options: ['×2 + 5', '×4 - 1', '×3 + 2', '+8'], correctIndex: 2, topic: 'Infer function rule' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 3 Memory Easy: Steps, Facts & Sequences',
    description: 'Recall short ordered information and learned facts.',
    questions: [
      { text: 'Morning steps: wake, brush, eat, pack. Third step?', options: ['brush', 'wake', 'pack', 'eat'], correctIndex: 3, topic: 'Order recall' },
      { text: 'Remember: 4, 9, 2. Which number was in the middle?', options: ['2', '4', '9', '6'], correctIndex: 2, topic: 'Short-term memory' },
      { text: '7 × 6 = ?', options: ['56', '48', '36', '42'], correctIndex: 3, topic: 'Fact recall' },
      { text: 'Water cycle order starts with evaporation, then ___', options: ['freezing', 'collection', 'melting', 'condensation'], correctIndex: 3, topic: 'Science sequence' },
      { text: 'Days: Monday, Tuesday, Wednesday, ___', options: ['Friday', 'Sunday', 'Thursday', 'Saturday'], correctIndex: 2, topic: 'Sequence memory' },
      { text: 'Code shown once: B-7-K. Last character?', options: ['7', 'K', 'BK', 'B'], correctIndex: 1, topic: 'Symbol recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 3 Memory Hard: Chunking & Multi-Step Recall',
    description: 'Hold and manipulate longer sequences and linked facts.',
    questions: [
      { text: 'Remember 3-8-1-9. Which came right after 8?', options: ['8', '9', '3', '1'], correctIndex: 3, topic: 'Sequential recall' },
      { text: 'Science steps: question -> hypothesis -> test -> data. Step before data?', options: ['hypothesis', 'question', 'test', 'conclusion'], correctIndex: 2, topic: 'Process memory' },
      { text: 'Chunk this number: 458732 as ___', options: ['4587-32', '4-5-8-7-3-2', '458-732', '45-87-32'], correctIndex: 2, topic: 'Chunking strategy' },
      { text: 'Map key says triangle=park, circle=school. Circle means ___', options: ['river', 'road', 'school', 'park'], correctIndex: 2, topic: 'Symbol mapping' },
      { text: 'List heard once: apple, pear, grape, mango. Second fruit?', options: ['apple', 'grape', 'pear', 'mango'], correctIndex: 2, topic: 'List recall' },
      { text: 'If 6×7=42 and 42-5=37, final result remembered is ___', options: ['47', '35', '42', '37'], correctIndex: 3, topic: 'Working memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 3 Problem Solving Easy: One-to-Two Step Stories',
    description: 'Use simple multiplication and subtraction in story contexts.',
    questions: [
      { text: '3 boxes with 5 pencils each. Total pencils?', options: ['15', '35', '10', '8'], correctIndex: 0, topic: 'Equal groups' },
      { text: 'There are 18 apples. 6 are eaten. Left?', options: ['24', '10', '12', '14'], correctIndex: 2, topic: 'Subtraction story' },
      { text: 'A ribbon is 20 cm. You cut off 7 cm. Remaining length?', options: ['27 cm', '12 cm', '7 cm', '13 cm'], correctIndex: 3, topic: 'Measurement' },
      { text: '4 rows of 3 chairs means ___ chairs', options: ['43', '7', '12', '8'], correctIndex: 2, topic: 'Arrays' },
      { text: 'You have $9 and spend $4. Money left?', options: ['$5', '$13', '$4', '$6'], correctIndex: 0, topic: 'Money' },
      { text: 'What do you measure to find around a shape?', options: ['volume', 'area', 'perimeter', 'mass'], correctIndex: 2, topic: 'Math vocabulary' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 3 Problem Solving Hard: Plan, Compute, Check',
    description: 'Solve multi-step situations with operation choice and verification.',
    questions: [
      { text: '7 packs of 6 markers are shared equally among 3 classes. How many markers per class?', options: ['13', '12', '42', '14'], correctIndex: 3, topic: 'Multi-step division' },
      { text: 'A 9x4 garden has area ___ and perimeter ___', options: ['26 and 36', '36 and 18', '13 and 36', '36 and 26'], correctIndex: 3, topic: 'Area and perimeter' },
      { text: 'Bus A has 24 students, Bus B has 18. 9 students leave total. Remaining?', options: ['27', '33', '31', '42'], correctIndex: 1, topic: 'Combine then subtract' },
      { text: 'A book costs $7. Mia buys 3 books and a $4 notebook. Total cost?', options: ['$18', '$24', '$25', '$21'], correctIndex: 2, topic: 'Mixed operations' },
      { text: 'A tank is filled 5 liters each hour for 6 hours, then 8 liters are used. Liters left?', options: ['28', '30', '22', '18'], correctIndex: 2, topic: 'Rate and subtraction' },
      { text: 'Which check best confirms 56 ÷ 8 = 7?', options: ['56 - 8 = 48', '8 + 7 = 15', '56 + 8 = 64', '7 × 8 = 56'], correctIndex: 3, topic: 'Reasonableness check' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 3 Critical Thinking Easy: Claims & Evidence Basics',
    description: 'Distinguish facts from opinions and choose better evidence.',
    questions: [
      { text: '"Cats are the best pets" is a ___', options: ['graph', 'opinion', 'fact', 'measurement'], correctIndex: 1, topic: 'Fact vs opinion' },
      { text: 'Best evidence that a plant grew is ___', options: ['a cartoon', 'it looks nice', 'measured height over days', 'someone guessed'], correctIndex: 2, topic: 'Evidence' },
      { text: 'A website with author and date is usually ___ than one without', options: ['less reliable', 'always fake', 'exactly equal', 'more reliable'], correctIndex: 3, topic: 'Source quality' },
      { text: 'If all squares are rectangles, then a square is a ___', options: ['circle', 'triangle', 'rectangle', 'line'], correctIndex: 2, topic: 'Logic' },
      { text: 'To compare two objects fairly, use the same ___', options: ['guesses', 'conditions', 'colors only', 'names'], correctIndex: 1, topic: 'Fair comparison' },
      { text: 'A bar graph is useful because it makes data ___', options: ['invisible', 'unnecessary', 'easy to compare', 'random'], correctIndex: 2, topic: 'Data interpretation' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 3 Critical Thinking Hard: Analyze, Infer & Justify',
    description: 'Evaluate claims, identify weak reasoning, and infer from data.',
    questions: [
      { text: 'A student says, "My plant grew because I sang to it." What is missing?', options: ['a louder voice', 'a drawing', 'controlled evidence', 'more opinions'], correctIndex: 2, topic: 'Causation vs evidence' },
      { text: 'If class data shows 18 prefer apples and 6 prefer pears, best conclusion is ___', options: ['pears are healthier', 'more students prefer apples', 'data is wrong', 'everyone likes apples'], correctIndex: 1, topic: 'Data-based inference' },
      { text: 'Which source is strongest for "Today\'s temperature"?', options: ['friend\'s guess', 'a storybook', 'thermometer reading', 'yesterday\'s weather'], correctIndex: 2, topic: 'Source strength' },
      { text: 'If A > B and B = C, then A compared with C is ___', options: ['greater than', 'less than', 'equal to', 'unknown always'], correctIndex: 0, topic: 'Logical transitivity' },
      { text: 'An ad says "100% best toy ever!" This is mainly ___', options: ['numerical data', 'a controlled trial', 'persuasive language', 'scientific proof'], correctIndex: 2, topic: 'Bias and persuasion' },
      { text: 'To test paper towel brands fairly, you should keep all but one thing ___', options: ['unmeasured', 'the same', 'randomly ignored', 'different'], correctIndex: 1, topic: 'Experiment design' },
    ],
  }),
];
