import { buildQuiz } from '../utils.js';

const G = 'grade_1';

/** Grade 1 adaptive tiers: medium + hard for all frozen categories. */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_1_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 1 Math Medium: Add and Subtract to 20',
    description: 'Single-step addition and subtraction within 20 with missing numbers.',
    questions: [
      { text: '9 + 6 = ?', options: ['15', '16', '14', '13'], correctIndex: 0, topic: 'Addition' },
      { text: '17 - 8 = ?', options: ['7', '9', '10', '8'], correctIndex: 1, topic: 'Subtraction' },
      { text: 'What number makes 12 + ? = 20?', options: ['8', '6', '7', '9'], correctIndex: 0, topic: 'Missing addend' },
      { text: '14 - 5 = ?', options: ['8', '10', '11', '9'], correctIndex: 3, topic: 'Subtract teens' },
      { text: 'Which is greater: 13 or 18?', options: ['They are equal', '18', '0', '13'], correctIndex: 1, topic: 'Compare' },
      { text: '8 + 4 + 3 = ?', options: ['13', '16', '15', '14'], correctIndex: 2, topic: 'Add three numbers' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 1 Math Hard: Two-Step Stories within 20',
    description: 'Two-step word problems and number reasoning within 20.',
    questions: [
      { text: 'Lina had 11 stickers, got 5 more, then gave away 4. How many now?', options: ['10', '11', '13', '12'], correctIndex: 3, topic: 'Two-step word problem' },
      { text: 'A box has 18 pencils. 7 are used and 3 new pencils are added. Total now?', options: ['12', '13', '15', '14'], correctIndex: 3, topic: 'Two-step with subtraction and addition' },
      { text: 'What is the missing number: ? + 9 = 20', options: ['10', '12', '9', '11'], correctIndex: 3, topic: 'Unknown addend' },
      { text: 'Sam read 6 pages in the morning and 7 in the evening. He needs 20 pages total. How many left?', options: ['9', '7', '6', '8'], correctIndex: 1, topic: 'Part-whole reasoning' },
      { text: 'There are 15 birds on a tree. 4 fly away, then 6 return. How many birds are on the tree?', options: ['17', '18', '16', '15'], correctIndex: 0, topic: 'Two-step change' },
      { text: 'Which equation matches: Start with 14, add 3, then subtract 5?', options: ['14 - 5 - 3 = 6', '14 + 5 - 3 = 16', '14 + 3 - 5 = 12', '14 - 3 + 5 = 16'], correctIndex: 2, topic: 'Modeling expressions' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Grade 1 Science Medium: Plants, Animals, and Weather',
    description: 'Classify living things, basic needs, and daily weather patterns.',
    questions: [
      { text: 'Which does a plant need to grow?', options: ['Water and sunlight', 'Only sand', 'Plastic and glue', 'Only darkness'], correctIndex: 0, topic: 'Plant needs' },
      { text: 'Which animal lives in water most of the time?', options: ['Fish', 'Cat', 'Eagle', 'Camel'], correctIndex: 0, topic: 'Habitats' },
      { text: 'Clouds become very dark. What weather is likely next?', options: ['Snow in summer always', 'No change ever', 'Rain', 'A rainbow with no rain'], correctIndex: 2, topic: 'Weather prediction' },
      { text: 'A baby chicken grows into a ___', options: ['Cloud', 'Rock', 'Hen or rooster', 'Tree'], correctIndex: 2, topic: 'Life cycles' },
      { text: 'If you place a toy in front of a lamp, a shadow forms because light is ___', options: ['frozen', 'eaten', 'painted', 'blocked'], correctIndex: 3, topic: 'Light and shadow' },
      { text: 'Which item can be recycled?', options: ['Smoke', 'Rain', 'Banana peel in backpack', 'Paper'], correctIndex: 3, topic: 'Earth care' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 1 Science Hard: Changes and Simple Systems',
    description: 'Reason about cause and effect in plants, habitats, and weather changes.',
    questions: [
      { text: 'A plant near a window grows taller than a plant in a dark closet. Why?', options: ['It has blue soil', 'It has no roots', 'It hears music', 'It gets more light'], correctIndex: 3, topic: 'Cause and effect' },
      { text: 'Pond water dries up in hot weather. What happens to fish first?', options: ['They stop needing water', 'They lose habitat', 'They turn into rocks', 'They become birds'], correctIndex: 1, topic: 'Habitat change' },
      { text: 'To test if seeds need water, what should stay the same?', options: ['Sunlight and room both change', 'Seed type and soil', 'Only pot color changes and seed type changes', 'Everything changes'], correctIndex: 1, topic: 'Fair test' },
      { text: 'Morning is cool, afternoon is warm, and evening is cool again. This is a ___', options: ['food chain', 'daily pattern', 'plant cycle', 'random event only'], correctIndex: 1, topic: 'Patterns in weather' },
      { text: 'If clouds block the sun, what often happens to the ground temperature?', options: ['It never changes', 'It freezes instantly', 'It gets cooler', 'It gets much hotter'], correctIndex: 2, topic: 'Sun and heat' },
      { text: 'A caterpillar, chrysalis, butterfly is an example of ___', options: ['a machine part', 'a weather report', 'a life cycle', 'a food label'], correctIndex: 2, topic: 'Life cycle reasoning' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Grade 1 Math Medium: Pattern Rules to 20',
    description: 'Find and continue numeric and letter patterns using simple rules.',
    questions: [
      { text: '2, 4, 6, 8, ___', options: ['10', '12', '9', '7'], correctIndex: 0, topic: 'Add 2 pattern' },
      { text: '20, 18, 16, 14, ___', options: ['13', '10', '12', '15'], correctIndex: 2, topic: 'Subtract 2 pattern' },
      { text: '3, 6, 9, 12, ___', options: ['18', '16', '14', '15'], correctIndex: 3, topic: 'Add 3 pattern' },
      { text: 'A, B, C, A, B, ___', options: ['B', 'A', 'D', 'C'], correctIndex: 3, topic: 'Repeating letters' },
      { text: '5, 10, 15, ___', options: ['18', '20', '25', '16'], correctIndex: 1, topic: 'Skip count by 5' },
      { text: 'Rule is +4. Start at 4: 4, 8, 12, ___', options: ['20', '16', '15', '14'], correctIndex: 1, topic: 'Apply given rule' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 1 Math Hard: Multi-Step Pattern Reasoning',
    description: 'Use increasing and alternating rules and explain missing terms.',
    questions: [
      { text: '1, 3, 6, 10, ___ (add 2, then 3, then 4)', options: ['14', '15', '16', '12'], correctIndex: 1, topic: 'Growing differences' },
      { text: '20, 17, 14, 11, ___', options: ['10', '9', '7', '8'], correctIndex: 3, topic: 'Subtract 3 pattern' },
      { text: '2, 5, 8, 11, ___', options: ['13', '12', '15', '14'], correctIndex: 3, topic: 'Add 3 pattern' },
      { text: '4, 8, 12, 11, 15, 19, 18, ___', options: ['20', '21', '22', '23'], correctIndex: 2, topic: 'Repeat mixed rule' },
      { text: 'B, D, F, H, ___', options: ['K', 'J', 'I', 'G'], correctIndex: 1, topic: 'Skip-letter pattern' },
      { text: 'What number is missing: 6, 9, __, 15, 18?', options: ['10', '12', '13', '11'], correctIndex: 1, topic: 'Infer missing term' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Grade 1 Memory Medium: Sequence and Recall',
    description: 'Remember order, grouped information, and short instructions.',
    questions: [
      { text: 'Morning routine: brush teeth, eat breakfast, pack bag. What comes second?', options: ['Brush teeth', 'Pack bag', 'Go to bed', 'Eat breakfast'], correctIndex: 3, topic: 'Order recall' },
      { text: 'Remember this list: red, blue, green, yellow. Which color was third?', options: ['Red', 'Yellow', 'Green', 'Blue'], correctIndex: 2, topic: 'List memory' },
      { text: 'Code: sun = 4, moon = 7. Which number matches moon?', options: ['7', '4', '3', '9'], correctIndex: 0, topic: 'Symbol mapping' },
      { text: 'Days in order: Monday, Tuesday, Wednesday, ___.', options: ['Thursday', 'Saturday', 'Sunday', 'Friday'], correctIndex: 0, topic: 'Calendar sequence' },
      { text: 'You hear: clap, clap, stomp, clap. What was the third sound?', options: ['jump', 'snap', 'stomp', 'clap'], correctIndex: 2, topic: 'Auditory sequence' },
      { text: 'If the numbers shown were 8, 3, 8, 2, which number appeared twice?', options: ['None', '3', '2', '8'], correctIndex: 3, topic: 'Repeat detection' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 1 Memory Hard: Multi-Step Recall',
    description: 'Track chunks, reversible sequences, and multi-step directions.',
    questions: [
      { text: 'Remember: 14-09-18. What is the middle chunk?', options: ['09', '18', '14', '149'], correctIndex: 0, topic: 'Chunk memory' },
      { text: 'Directions: draw a circle, color it blue, then add a star. What is the last step?', options: ['Add a star', 'Draw a circle', 'Color it blue', 'Erase everything'], correctIndex: 0, topic: 'Procedural recall' },
      { text: 'List was: cat, tree, book, drum, kite. Which word came right after tree?', options: ['drum', 'kite', 'cat', 'book'], correctIndex: 3, topic: 'Neighbor recall' },
      { text: 'Sequence: left, right, right, left, left. What was the fourth move?', options: ['left', 'jump', 'right', 'stop'], correctIndex: 0, topic: 'Position tracking' },
      { text: 'Memory pair: glove-hand, sock-foot, hat-___.', options: ['arm', 'desk', 'knee', 'head'], correctIndex: 3, topic: 'Association memory' },
      { text: 'Number order shown once: 5, 9, 2, 9, 1. Which number repeated?', options: ['1', '9', '5', '2'], correctIndex: 1, topic: 'Repeat and scan' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Grade 1 Problem Solving Medium: Story Problems to 20',
    description: 'Solve one-step and mixed operation stories within 20.',
    questions: [
      { text: 'There are 7 birds on a fence. 5 more land. How many now?', options: ['10', '12', '13', '11'], correctIndex: 1, topic: 'Addition story' },
      { text: 'A jar has 16 marbles. 6 are removed. How many left?', options: ['9', '8', '10', '11'], correctIndex: 2, topic: 'Subtraction story' },
      { text: 'Nina has 9 crayons and wants 15. How many more does she need?', options: ['5', '7', '4', '6'], correctIndex: 3, topic: 'Compare and difference' },
      { text: 'Tom has 4 red balloons and 4 blue balloons. How many balloons total?', options: ['7', '8', '6', '9'], correctIndex: 1, topic: 'Equal groups as addition' },
      { text: 'Choose the best equation for: Start with 13, take away 5.', options: ['13 + 5 = 18', '13 - 5 = 8', '13 + 8 = 5', '5 - 13 = 8'], correctIndex: 1, topic: 'Equation matching' },
      { text: 'A class needs 20 pencils. They have 14. How many more are needed?', options: ['5', '7', '8', '6'], correctIndex: 3, topic: 'Missing part' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 1 Problem Solving Hard: Two-Step Plans',
    description: 'Use two-step arithmetic reasoning and choose efficient strategies within 20.',
    questions: [
      { text: 'Eva had 10 blocks, found 7, then lost 3. How many blocks now?', options: ['12', '14', '15', '13'], correctIndex: 1, topic: 'Two-step total' },
      { text: 'There are 19 cookies. 8 are eaten and then 4 are baked. How many cookies now?', options: ['16', '13', '15', '14'], correctIndex: 2, topic: 'Two-step change' },
      { text: 'A bus has 12 kids. 5 get off, then 6 get on. How many kids are on the bus?', options: ['13', '12', '11', '14'], correctIndex: 0, topic: 'Two-step word problem' },
      { text: 'Pick the fastest way to solve 9 + 8.', options: ['Make 10: (9 + 1) + 7', 'Count back from 9', 'Guess then check', 'Subtract 8 from 9'], correctIndex: 0, topic: 'Strategy choice' },
      { text: 'Mia needs 18 beads for a necklace. She has 7 and then gets 5 more. How many still needed?', options: ['7', '5', '6', '8'], correctIndex: 2, topic: 'Goal tracking' },
      { text: 'Start at 20, subtract 6, then subtract 5. What is the result?', options: ['7', '9', '8', '10'], correctIndex: 1, topic: 'Sequential subtraction' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Grade 1 Critical Thinking Medium: Compare and Explain',
    description: 'Use clues, classify information, and choose better reasons.',
    questions: [
      { text: 'Which is the best evidence that it rained last night?', options: ['Someone said maybe', 'The clock is loud', 'Wet ground and puddles', 'A bright rainbow drawing'], correctIndex: 2, topic: 'Evidence' },
      { text: 'Which does not belong: spoon, fork, plate, pencil?', options: ['fork', 'pencil', 'spoon', 'plate'], correctIndex: 1, topic: 'Classification' },
      { text: 'If an object sinks in water, what can you say?', options: ['It is made of light', 'It is denser than water for that test', 'It can float in all liquids', 'It is always heavy in every case'], correctIndex: 1, topic: 'Observation to claim' },
      { text: 'A friend says 12 is less than 9. What is the best response?', options: ['Use a number line to show 12 is greater', 'Ignore all numbers', 'Agree to be polite', 'Say both are the same'], correctIndex: 0, topic: 'Reasoning with tools' },
      { text: 'Which question helps a fair test about plant growth?', options: ['Who likes plants more?', 'Which pot is prettier?', 'Did both plants get the same water?', 'Is green the best color?'], correctIndex: 2, topic: 'Fair test thinking' },
      { text: 'You need to carry many books safely. Best plan?', options: ['Hold all books in one hand above your head', 'Use a bag with two straps', 'Kick them forward', 'Drop some and run'], correctIndex: 1, topic: 'Practical judgment' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 1 Critical Thinking Hard: Logic and Decisions',
    description: 'Apply if-then logic, evaluate sources, and justify conclusions.',
    questions: [
      { text: 'All robins are birds. All birds have feathers. Therefore robins have ___', options: ['feathers', 'shells', 'scales', 'fur'], correctIndex: 0, topic: 'Logic chain' },
      { text: 'If the playground is wet, we play inside. The playground is wet. Where do we play?', options: ['Inside', 'On the roof', 'Outside', 'In a bus'], correctIndex: 0, topic: 'If-then reasoning' },
      { text: 'Which source is strongest for today temperature?', options: ['A thermometer reading', 'A guess from yesterday', 'A cartoon picture', 'A dream'], correctIndex: 0, topic: 'Source reliability' },
      { text: 'Two students test paper airplanes. One changes plane shape and throw strength together. Why is this weak?', options: ['Too many variables changed at once', 'It is done outdoors', 'It uses paper', 'It has one result only'], correctIndex: 0, topic: 'Experimental design' },
      { text: 'You see smoke from a toaster. What is the most reasonable first action?', options: ['Open freezer instead', 'Ignore it and keep cooking', 'Pour juice into toaster', 'Turn off and unplug toaster, then tell an adult'], correctIndex: 3, topic: 'Safety reasoning' },
      { text: 'A class graph shows more students choose apples than bananas. Best conclusion?', options: ['Fruit choices never change', 'All schools prefer apples', 'Apples are more popular in this class', 'Bananas are unhealthy for everyone'], correctIndex: 2, topic: 'Data-based conclusion' },
    ],
  }),
];
