import { buildQuiz } from '../utils.js';

const G = 'grade_2';

/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_2_PILOT_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 2 Science Easy: My World',
    description: 'Simple solids, liquids, and what plants need.',
    questions: [
      { text: 'Water at room temperature is a ___', options: ['liquid', 'solid', 'gas', 'rock'], correctIndex: 0, topic: 'States' },
      { text: 'A rock is a ___', options: ['solid', 'liquid', 'gas', 'sound'], correctIndex: 0, topic: 'States' },
      { text: 'Plants need sunlight and ___', options: ['water', 'candy', 'shoes', 'paint'], correctIndex: 0, topic: 'Plants' },
      { text: 'Daytime sky is often ___', options: ['bright', 'always green', 'underground', 'made of metal'], correctIndex: 0, topic: 'Sky' },
      { text: 'Fish live in ___', options: ['water', 'sand only', 'clouds', 'ice only'], correctIndex: 0, topic: 'Habitats' },
      { text: 'We use eyes to ___', options: ['see', 'smell', 'hop', 'dig'], correctIndex: 0, topic: 'Senses' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 2 Science Hard: Matter & Systems',
    description: 'Food chains, magnets, and the water cycle.',
    questions: [
      { text: 'Grass → rabbit → fox. Fox is a ___', options: ['consumer', 'producer', 'sun', 'soil'], correctIndex: 0, topic: 'Food chain' },
      { text: 'Evaporation then ___ forms clouds', options: ['condensation', 'burning', 'magnetism', 'gravity only'], correctIndex: 0, topic: 'Water cycle' },
      { text: 'Which is attracted to a magnet?', options: ['Iron nail', 'Wooden block', 'Paper cup', 'Plastic spoon'], correctIndex: 0, topic: 'Magnets' },
      { text: 'Sunlight is ___ energy for plants', options: ['light', 'sound', 'magnetic', 'plastic'], correctIndex: 0, topic: 'Energy' },
      { text: 'Ice melting to water is a ___ change', options: ['physical', 'eating', 'sleeping', 'counting'], correctIndex: 0, topic: 'Change' },
      { text: 'A fair test changes ___ variable', options: ['one', 'ten', 'zero', 'all at once'], correctIndex: 0, topic: 'Investigation' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Grade 2 Math Medium: Add & Subtract',
    description: 'Two-digit addition and subtraction within 100.',
    questions: [
      { text: '45 + 23 = ?', options: ['68', '58', '78', '48'], correctIndex: 0, topic: 'Addition' },
      { text: '70 − 28 = ?', options: ['42', '52', '32', '98'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Which equals 100?', options: ['10 tens', '5 tens', '2 tens', '100 ones only wrong'], correctIndex: 0, topic: 'Place value' },
      { text: '4 × 5 = ?', options: ['20', '9', '15', '45'], correctIndex: 0, topic: 'Multiply' },
      { text: 'Half of 24 is ___', options: ['12', '10', '14', '48'], correctIndex: 0, topic: 'Equal parts' },
      { text: 'Compare: 56 ___ 65', options: ['<', '>', '=', '≠ only'], correctIndex: 0, topic: 'Compare' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 2 Math Hard: Stretch to 100',
    description: 'Regrouping, equal groups, and two-step problems.',
    questions: [
      { text: '58 + 37 = ?', options: ['95', '85', '75', '91'], correctIndex: 0, topic: 'Regrouping' },
      { text: '100 − 46 = ?', options: ['54', '64', '44', '146'], correctIndex: 0, topic: 'Subtract' },
      { text: '7 × 3 = ?', options: ['21', '10', '18', '73'], correctIndex: 0, topic: 'Multiply' },
      { text: '36 stickers shared by 4 friends. Each gets ___', options: ['9', '8', '10', '40'], correctIndex: 0, topic: 'Division' },
      { text: 'Had 50, spent 18, earned 5. Now ___', options: ['37', '27', '47', '33'], correctIndex: 0, topic: 'Two-step' },
      { text: 'Quarter + quarter + dime = ___ cents', options: ['60', '50', '35', '25'], correctIndex: 0, topic: 'Money' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 2 Patterns Easy: What Comes Next?',
    description: 'Simple repeating and growing patterns.',
    questions: [
      { text: '2, 4, 6, 8, ___', options: ['10', '9', '12', '7'], correctIndex: 0, topic: '+2' },
      { text: '🔴 🟢 🔴 🟢 ___', options: ['🔴', '🟢', '🟡', '⬛'], correctIndex: 0, topic: 'Repeat' },
      { text: '5, 10, 15, ___', options: ['20', '16', '18', '25'], correctIndex: 0, topic: 'Skip 5' },
      { text: 'A, B, C, D, ___', options: ['E', 'A', 'F', 'B'], correctIndex: 0, topic: 'Letters' },
      { text: '10, 9, 8, ___', options: ['7', '6', '9', '11'], correctIndex: 0, topic: 'Count back' },
      { text: 'Rule +1: 3, 4, 5, ___', options: ['6', '5', '7', '4'], correctIndex: 0, topic: 'Growing' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 2 Patterns Hard: Rules & Tables',
    description: '×2, +10, and two-rule patterns.',
    questions: [
      { text: '12, 22, 32, ___', options: ['42', '33', '40', '52'], correctIndex: 0, topic: '+10' },
      { text: '×2: 5, 10, 20, ___', options: ['40', '30', '25', '15'], correctIndex: 0, topic: 'Double' },
      { text: '3, 7, 11, 15, ___ (+4)', options: ['19', '18', '17', '16'], correctIndex: 0, topic: 'Rule' },
      { text: '100, 90, 80, 70, ___', options: ['60', '50', '85', '110'], correctIndex: 0, topic: 'Decrease' },
      { text: '2, 6, 18, ___ (×3 each step)', options: ['54', '24', '36', '20'], correctIndex: 0, topic: 'Multiply pattern' },
      { text: '🔵🔵🔴 🔵🔵🔴 ___', options: ['🔵🔵🔴', '🔴🔴🔵', '🟢', '⬛'], correctIndex: 0, topic: 'Block repeat' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 2 Memory Easy: Remember & Match',
    description: 'Short lists, pairs, and what comes next.',
    questions: [
      { text: 'Cat, dog, bird. Which is a pet bird?', options: ['Bird', 'Rock', 'Car', 'Desk'], correctIndex: 0, topic: 'Recall' },
      { text: 'Red, blue, red, blue, ___', options: ['Red', 'Green', 'Yellow', 'Black'], correctIndex: 0, topic: 'Pattern' },
      { text: 'Monday, Tuesday, ___', options: ['Wednesday', 'Sunday', 'Friday', 'March'], correctIndex: 0, topic: 'Days' },
      { text: '1, 2, 3 — number after 3 is ___', options: ['4', '2', '5', '1'], correctIndex: 0, topic: 'Count' },
      { text: 'Hat goes with ___', options: ['Head', 'Foot', 'Sky', 'Water'], correctIndex: 0, topic: 'Pairs' },
      { text: 'First, second, third. Next is ___', options: ['Fourth', 'First', 'Last', 'Zero'], correctIndex: 0, topic: 'Order' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 2 Memory Hard: Chunks & Sequences',
    description: 'Phone chunks, symbols, and multi-step recall.',
    questions: [
      { text: 'Phone 55-12-90 — middle chunk?', options: ['12', '55', '90', '551'], correctIndex: 0, topic: 'Chunking' },
      { text: '🔺=3, 🔺🔺=___', options: ['6', '3', '9', '2'], correctIndex: 0, topic: 'Symbols' },
      { text: 'Plan: mix → bake → cool. Third step?', options: ['Cool', 'Mix', 'Bake', 'Eat'], correctIndex: 0, topic: 'Procedure' },
      { text: '9, 7, 5, 3, ___', options: ['1', '2', '4', '5'], correctIndex: 0, topic: 'Count back' },
      { text: 'Saw A, B, C, B, A. Letter in middle?', options: ['C', 'A', 'B', 'D'], correctIndex: 0, topic: 'Scan' },
      { text: 'Zip code 20-45 — second part?', options: ['45', '20', '25', '204'], correctIndex: 0, topic: 'Chunks' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 2 Problems Easy: Stories & Drawings',
    description: 'Join, take apart, and compare within 20.',
    questions: [
      { text: '5 apples + 3 apples = ___', options: ['8', '7', '9', '2'], correctIndex: 0, topic: 'Join' },
      { text: '10 − 4 = ?', options: ['6', '5', '7', '14'], correctIndex: 0, topic: 'Take apart' },
      { text: 'Which has more: 7 or 4?', options: ['7', '4', 'Same', '0'], correctIndex: 0, topic: 'Compare' },
      { text: '2 groups of 3 stickers = ___', options: ['6', '5', '7', '3'], correctIndex: 0, topic: 'Groups' },
      { text: 'Sam has 9, gives 2. Left?', options: ['7', '6', '8', '11'], correctIndex: 0, topic: 'Give' },
      { text: 'Need 12, have 8. More needed?', options: ['4', '3', '5', '20'], correctIndex: 0, topic: 'Missing' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 2 Problems Hard: Multi-Step',
    description: 'Money, time, perimeter, and two-step logic.',
    questions: [
      { text: 'Had 45, spent 18, got 10. Now?', options: ['37', '27', '47', '73'], correctIndex: 0, topic: 'Two-step' },
      { text: 'Rectangle 6×4 — perimeter?', options: ['20', '24', '10', '8'], correctIndex: 0, topic: 'Perimeter' },
      { text: '72 − 28 = ?', options: ['44', '54', '46', '100'], correctIndex: 0, topic: 'Subtract' },
      { text: '30 ÷ 5 = ?', options: ['6', '5', '7', '35'], correctIndex: 0, topic: 'Divide' },
      { text: '3 dimes = ___ cents', options: ['30', '20', '15', '3'], correctIndex: 0, topic: 'Money' },
      { text: 'Start 1:15, wait 45 min. Time ___', options: ['2:00', '1:45', '2:15', '1:30'], correctIndex: 0, topic: 'Time' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 2 Thinking Easy: Ask Why',
    description: 'Compare choices, notice clues, and fair questions.',
    questions: [
      { text: 'Rainy day — best clue is ___', options: ['Clouds and rain', 'Hot sun only', 'Snow only', 'Wind only'], correctIndex: 0, topic: 'Clues' },
      { text: 'Which helps you decide: guess or measure?', options: ['Measure', 'Guess only', 'Close eyes', 'Skip'], correctIndex: 0, topic: 'Evidence' },
      { text: 'All dogs are animals. A puppy is a ___', options: ['Dog', 'Plant', 'Rock', 'Car'], correctIndex: 0, topic: 'Logic' },
      { text: 'Two answers — pick the one with a ___', options: ['Reason', 'Joke', 'Song', 'Color only'], correctIndex: 0, topic: 'Reason' },
      { text: 'Test plants with same water but different ___', options: ['Light', 'Shoes', 'Music', 'Names'], correctIndex: 0, topic: 'Fair test' },
      { text: 'Story says hero was brave. Brave means ___', options: ['Not afraid to try', 'Always sleeping', 'Very loud', 'Tiny'], correctIndex: 0, topic: 'Words' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 2 Thinking Hard: Evidence & Logic',
    description: 'Sources, if-then reasoning, and fair tests.',
    questions: [
      { text: 'Measured length beats a ___', options: ['Wild guess', 'Ruler', 'Desk', 'Pencil'], correctIndex: 0, topic: 'Evidence' },
      { text: 'Fair test changes ___ thing at a time', options: ['One', 'Ten', 'Zero', 'All'], correctIndex: 0, topic: 'Fair test' },
      { text: 'All squares are rectangles. Every rectangle a square?', options: ['No', 'Yes', 'Always', 'Never'], correctIndex: 0, topic: 'Logic' },
      { text: 'Dark sky at 8 pm suggests ___', options: ['Night', 'Noon', 'Lunch', 'Morning'], correctIndex: 0, topic: 'Infer' },
      { text: 'Strongest weather fact comes from ___', options: ['Station data', 'A dream', 'A cartoon', 'A guess'], correctIndex: 0, topic: 'Sources' },
      { text: 'If A > B and B > C, then A ___ C', options: ['>', '<', '=', '≠'], correctIndex: 0, topic: 'Chain' },
    ],
  }),
];
