import { buildQuiz } from '../utils.js';

const G = 'grade_4';

/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const GRADE_4_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'easy',
    title: 'Grade 4 Math Easy: Core Operations',
    description: 'Basic multiplication, fractions, and place value review.',
    questions: [
      { text: '6 x 7 = ?', options: ['48', '36', '56', '42'], correctIndex: 3, topic: 'Multiply' },
      { text: 'Which fraction is equal to 1/2?', options: ['1/3', '2/4', '2/3', '3/4'], correctIndex: 1, topic: 'Fractions' },
      { text: '900 + 80 + 6 = ?', options: ['986', '896', '968', '980'], correctIndex: 0, topic: 'Place value' },
      { text: '48 - 19 = ?', options: ['31', '39', '29', '27'], correctIndex: 2, topic: 'Subtract' },
      { text: 'Which is greater?', options: ['0.7', 'They are equal', '0.6', '0.06'], correctIndex: 0, topic: 'Decimals' },
      { text: 'Perimeter of a square with side 5 is ___', options: ['15', '25', '20', '10'], correctIndex: 2, topic: 'Perimeter' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Grade 4 Math Hard: Multi-Step Reasoning',
    description: 'Advanced fraction and multi-step number challenges.',
    questions: [
      { text: '3/4 + 2/8 = ?', options: ['1', '3/8', '7/8', '5/8'], correctIndex: 0, topic: 'Fraction addition' },
      { text: 'A number is 6 times 9, then minus 17. Result?', options: ['45', '29', '37', '41'], correctIndex: 2, topic: 'Order of operations' },
      { text: '1.25 + 0.8 = ?', options: ['1.33', '2.05', '2.5', '2.13'], correctIndex: 1, topic: 'Decimal sum' },
      { text: 'LCM of 6 and 8 is ___', options: ['12', '24', '48', '18'], correctIndex: 1, topic: 'Multiples' },
      { text: 'A rectangle has area 54 and width 6. Length?', options: ['9', '10', '8', '7'], correctIndex: 0, topic: 'Area inverse' },
      { text: 'Round 4,786 to nearest hundred.', options: ['4,700', '4,790', '4,800', '5,000'], correctIndex: 2, topic: 'Rounding' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'easy',
    title: 'Grade 4 Science Easy: Earth Basics',
    description: 'Simple concepts in energy, matter, and Earth systems.',
    questions: [
      { text: 'The Sun is our main source of ___', options: ['plastic', 'soil', 'light and heat', 'wind only'], correctIndex: 2, topic: 'Energy' },
      { text: 'Water vapor is water in ___ state', options: ['liquid', 'solid', 'metal', 'gas'], correctIndex: 3, topic: 'States of matter' },
      { text: 'Plants make food using sunlight in ___', options: ['friction', 'photosynthesis', 'erosion', 'condensation'], correctIndex: 1, topic: 'Plants' },
      { text: 'Rocks broken into smaller pieces by wind is ___', options: ['melting', 'weathering', 'evaporation', 'orbiting'], correctIndex: 1, topic: 'Earth changes' },
      { text: 'An animal that eats plants and animals is an ___', options: ['decomposer only', 'omnivore', 'herbivore', 'producer'], correctIndex: 1, topic: 'Food relationships' },
      { text: 'A closed electric path is called a ___', options: ['circuit', 'magnet', 'battery', 'switch'], correctIndex: 0, topic: 'Electricity' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Grade 4 Science Hard: Systems & Evidence',
    description: 'Apply scientific ideas to cycles, forces, and experiments.',
    questions: [
      { text: 'In the water cycle, vapor cools into clouds by ___', options: ['evaporation', 'condensation', 'collection', 'precipitation'], correctIndex: 1, topic: 'Water cycle' },
      { text: 'If two objects have equal mass, stronger force gives ___ acceleration', options: ['no', 'negative', 'greater', 'less'], correctIndex: 2, topic: 'Forces' },
      { text: 'A producer in a forest food web is likely a ___', options: ['wolf', 'tree', 'fungus', 'owl'], correctIndex: 1, topic: 'Ecosystems' },
      { text: 'Best way to test fertilizer effect is to change only the ___', options: ['weather outside', 'fertilizer amount', 'measurement tool each day', 'pot size, seed type, and water too'], correctIndex: 1, topic: 'Fair test' },
      { text: 'The Moon appears to change shape because of ___', options: ['Earth shadow every night', 'cloud shapes', 'its position with Earth and Sun', 'Moon spinning faster'], correctIndex: 2, topic: 'Moon phases' },
      { text: 'A material that is attracted to magnets is often ___', options: ['wood', 'iron', 'glass', 'rubber'], correctIndex: 1, topic: 'Magnetism' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'easy',
    title: 'Grade 4 Patterns Easy: Number Rules',
    description: 'Identify simple arithmetic and geometric patterns.',
    questions: [
      { text: '7, 12, 17, 22, ___', options: ['27', '28', '25', '26'], correctIndex: 0, topic: '+5' },
      { text: '3, 6, 12, 24, ___', options: ['42', '48', '36', '30'], correctIndex: 1, topic: 'x2' },
      { text: '0.1, 0.2, 0.3, ___', options: ['0.13', '0.5', '1.0', '0.4'], correctIndex: 3, topic: 'Decimals' },
      { text: '25, 20, 15, 10, ___', options: ['8', '0', '12', '5'], correctIndex: 3, topic: '-5' },
      { text: 'Input 2 -> 6 and input 5 -> 15. Rule is ___', options: ['add 3', 'multiply by 3', 'square', 'subtract 3'], correctIndex: 1, topic: 'Function rule' },
      { text: '4, 9, 16, 25, ___', options: ['49', '35', '30', '36'], correctIndex: 3, topic: 'Square numbers' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Grade 4 Patterns Hard: Multi-Rule Sequences',
    description: 'Analyze alternating and structured sequence behavior.',
    questions: [
      { text: '2, 5, 11, 23, ___', options: ['44', '47', '46', '35'], correctIndex: 1, topic: 'x2 +1' },
      { text: '1, 4, 9, 16, 25, ___', options: ['36', '49', '30', '35'], correctIndex: 0, topic: 'Square sequence' },
      { text: '64, 32, 16, 8, ___', options: ['4', '2', '12', '6'], correctIndex: 0, topic: 'Halving' },
      { text: 'Term rule: 3n + 2. For n=6, term is ___', options: ['18', '14', '24', '20'], correctIndex: 3, topic: 'Algebraic pattern' },
      { text: 'Alternating pattern 10, 7, 14, 11, 22, 19, ___', options: ['26', '38', '21', '30'], correctIndex: 1, topic: 'Alternate operations' },
      { text: 'A shape adds 3 sides each step: 4, 7, 10, ___', options: ['13', '11', '12', '14'], correctIndex: 0, topic: 'Geometric growth' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'easy',
    title: 'Grade 4 Memory Easy: Facts & Order',
    description: 'Recall lists, definitions, and simple ordered information.',
    questions: [
      { text: 'Order the water cycle: evaporation, condensation, ___', options: ['rotation', 'erosion', 'photosynthesis', 'precipitation'], correctIndex: 3, topic: 'Cycle order' },
      { text: 'A right angle measures ___ degrees', options: ['60', '180', '45', '90'], correctIndex: 3, topic: 'Math fact' },
      { text: 'The largest planet in our solar system is ___', options: ['Mars', 'Venus', 'Jupiter', 'Earth'], correctIndex: 2, topic: 'Space facts' },
      { text: 'In a food chain, plants are called ___', options: ['producers', 'consumers', 'predators', 'prey'], correctIndex: 0, topic: 'Vocabulary' },
      { text: 'Compass directions go N, E, S, ___', options: ['S', 'N', 'W', 'E'], correctIndex: 2, topic: 'Geography recall' },
      { text: 'Mean of 4 and 8 is ___', options: ['4', '8', '12', '6'], correctIndex: 3, topic: 'Data recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Grade 4 Memory Hard: Multi-Part Recall',
    description: 'Remember precise facts, sequences, and linked details.',
    questions: [
      { text: 'Prime numbers under 10 are 2, 3, 5, and ___', options: ['9', '11', '7', '1'], correctIndex: 2, topic: 'Number facts' },
      { text: 'Order planets from Sun starts Mercury, Venus, ___', options: ['Saturn', 'Jupiter', 'Mars', 'Earth'], correctIndex: 3, topic: 'Space order' },
      { text: 'A triangle has angle sum of ___ degrees', options: ['90', '270', '180', '360'], correctIndex: 2, topic: 'Geometry recall' },
      { text: '1 kilometer equals ___ meters', options: ['100', '10,000', '1,000', '100,000'], correctIndex: 2, topic: 'Measurement facts' },
      { text: 'In place value, digit 6 in 36,482 is worth ___', options: ['600', '60', '6,000', '6'], correctIndex: 2, topic: 'Place value memory' },
      { text: 'A sentence with a command ends with ___ most often', options: ['a comma', 'quotation marks', 'a question mark', 'a period'], correctIndex: 3, topic: 'Language recall' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'easy',
    title: 'Grade 4 Problem Solving Easy: One- and Two-Step',
    description: 'Solve practical arithmetic and measurement situations.',
    questions: [
      { text: 'A box has 24 pencils. 8 are used. How many left?', options: ['12', '14', '16', '18'], correctIndex: 2, topic: 'Subtract in context' },
      { text: '3 bags with 6 apples each means ___ apples total', options: ['18', '24', '9', '12'], correctIndex: 0, topic: 'Equal groups' },
      { text: 'A rope is 15 m. Cut off 4 m. Remaining?', options: ['19 m', '11 m', '9 m', '10 m'], correctIndex: 1, topic: 'Measurement' },
      { text: 'A movie starts 2:30 PM and lasts 1 hour. Ends at ___', options: ['3:00 PM', '3:30 PM', '4:30 PM', '2:31 PM'], correctIndex: 1, topic: 'Elapsed time' },
      { text: '$20 buys 4 notebooks equally. One notebook costs ___', options: ['$8', '$5', '$6', '$4'], correctIndex: 1, topic: 'Unit rate' },
      { text: 'Rectangle 7 by 3 has area ___', options: ['14', '28', '10', '21'], correctIndex: 3, topic: 'Area' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Grade 4 Problem Solving Hard: Strategy Challenges',
    description: 'Tackle multi-step, ratio-like, and logical word problems.',
    questions: [
      { text: 'A store sells 3 pens for $6. Cost of 8 pens?', options: ['$12', '$14', '$16', '$18'], correctIndex: 2, topic: 'Proportional reasoning' },
      { text: 'A runner does 250 m per lap. How far in 7 laps?', options: ['1,750 m', '2,000 m', '1,500 m', '1,250 m'], correctIndex: 0, topic: 'Multiply and convert' },
      { text: 'Class has 28 students. 3/4 are present. Present students?', options: ['18', '24', '20', '21'], correctIndex: 3, topic: 'Fraction of set' },
      { text: 'A tank holds 90 L. It is filled at 15 L/hour. Time to fill?', options: ['7 hours', '5 hours', '6 hours', '4 hours'], correctIndex: 2, topic: 'Rate' },
      { text: 'Perimeter 30 with width 6. Rectangle length?', options: ['9', '12', '6', '15'], correctIndex: 0, topic: 'Perimeter equation' },
      { text: 'Number puzzle: think of 8, double it, subtract 5, divide by 3. Result?', options: ['9', '7', '11/3', '5'], correctIndex: 2, topic: 'Multi-step operations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'easy',
    title: 'Grade 4 Critical Thinking Easy: Claims & Clues',
    description: 'Distinguish facts, opinions, and stronger evidence.',
    questions: [
      { text: '"This backpack weighs 2 kg" is a ___', options: ['question', 'opinion', 'guess', 'fact'], correctIndex: 3, topic: 'Fact vs opinion' },
      { text: 'Best evidence for rainfall yesterday is ___', options: ['a friend guessing', 'a drawing', 'a joke', 'weather record'], correctIndex: 3, topic: 'Evidence sources' },
      { text: 'If all squares have 4 sides, a square has ___ sides', options: ['5', '3', '6', '4'], correctIndex: 3, topic: 'Deduction' },
      { text: 'In an experiment, changing one thing at a time makes it ___', options: ['fair', 'unfair', 'impossible', 'random'], correctIndex: 0, topic: 'Fair test' },
      { text: 'Which question is strongest for research?', options: ['Who is louder?', 'Do I like this?', 'Is it colorful?', 'What evidence supports this?'], correctIndex: 3, topic: 'Question quality' },
      { text: 'A map with scale helps estimate real ___', options: ['taste', 'distance', 'smell', 'temperature'], correctIndex: 1, topic: 'Tool use' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Grade 4 Critical Thinking Hard: Logic & Evaluation',
    description: 'Evaluate arguments, detect weak reasoning, and infer correctly.',
    questions: [
      { text: 'Claim: "Plants grow faster with light." Best support is ___', options: ['one photo', 'a single guess', 'data from controlled experiments', 'a story without measurements'], correctIndex: 2, topic: 'Argument strength' },
      { text: 'If A > B and B > C, then ___', options: ['A > C', 'A < C', 'A = C', 'cannot tell'], correctIndex: 0, topic: 'Transitive logic' },
      { text: 'A survey asks only basketball fans about best sport. This is ___', options: ['double checking', 'fair testing', 'biased sampling', 'random sampling'], correctIndex: 2, topic: 'Bias' },
      { text: 'Which conclusion is valid? "All mammals breathe air. Whales are mammals."', options: ['All air breathers are whales', 'Whales are fish', 'Whales breathe air', 'Mammals live only on land'], correctIndex: 2, topic: 'Syllogism' },
      { text: 'When two explanations fit, choose the one with ___', options: ['shorter sentence', 'louder voice', 'more colors', 'more reliable evidence'], correctIndex: 3, topic: 'Evidence weighting' },
      { text: 'A graph axis starts at 90 instead of 0 and exaggerates change. This is ___', options: ['invalid graph type', 'exactly neutral display', 'perfectly random', 'misleading presentation'], correctIndex: 3, topic: 'Data interpretation' },
    ],
  }),
];
