import { buildQuiz } from '../utils.js';

const G = 'kindergarten';

/** Medium + hard tiers for Kindergarten adaptive pilot. */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const KINDERGARTEN_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Kindergarten Math Medium: Numbers to 15',
    description: 'Add and subtract within 15, compare numbers.',
    questions: [
      { text: '8 + 4 = ?', options: ['12', '11', '13', '10'], correctIndex: 0, topic: 'Addition' },
      { text: '14 − 3 = ?', options: ['11', '10', '12', '17'], correctIndex: 0, topic: 'Subtraction' },
      { text: 'Which is less: 9 or 12?', options: ['9', '12', 'Same', '15'], correctIndex: 0, topic: 'Compare' },
      { text: '10 + 5 = ?', options: ['15', '14', '16', '5'], correctIndex: 0, topic: 'Teen numbers' },
      { text: 'How many sides on a hexagon?', options: ['6', '5', '8', '3'], correctIndex: 0, topic: 'Shapes' },
      { text: '7 + 7 = ?', options: ['14', '13', '15', '77'], correctIndex: 0, topic: 'Doubles' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Kindergarten Math Hard: Stories to 20',
    description: 'Two-step stories and numbers to 20.',
    questions: [
      { text: 'Had 12 crayons, lost 4. Left?', options: ['8', '7', '9', '16'], correctIndex: 0, topic: 'Take away' },
      { text: '9 + 6 + 2 = ?', options: ['17', '16', '18', '15'], correctIndex: 0, topic: 'Add three' },
      { text: '18 − 5 = ?', options: ['13', '12', '14', '23'], correctIndex: 0, topic: 'Subtract teens' },
      { text: 'Which number is between 11 and 13?', options: ['12', '10', '14', '11'], correctIndex: 0, topic: 'Between' },
      { text: '4 tens and 2 ones make ___', options: ['42', '24', '6', '402'], correctIndex: 0, topic: 'Place value' },
      { text: '5 + ? = 20', options: ['15', '10', '14', '25'], correctIndex: 0, topic: 'Missing addend' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Kindergarten Science Medium: Habitats & Change',
    description: 'Where animals live and how things change.',
    questions: [
      { text: 'Frogs live near ___', options: ['water', 'only snow', 'only sand', 'the moon'], correctIndex: 0, topic: 'Habitats' },
      { text: 'A seed needs water, soil, and ___', options: ['light', 'shoes', 'paint', 'ice cream'], correctIndex: 0, topic: 'Plants' },
      { text: 'Ice melts when it gets ___', options: ['warmer', 'colder forever', 'darker', 'louder'], correctIndex: 0, topic: 'Change' },
      { text: 'Day and night happen because Earth ___', options: ['spins', 'stops', 'melts', 'shrinks'], correctIndex: 0, topic: 'Earth' },
      { text: 'Wood comes from ___', options: ['trees', 'rocks', 'clouds', 'metal only'], correctIndex: 0, topic: 'Materials' },
      { text: 'We taste sweet foods with our ___', options: ['tongue', 'elbows', 'knees', 'hair'], correctIndex: 0, topic: 'Senses' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Kindergarten Science Hard: Systems & Cycles',
    description: 'Food chains, weather patterns, and fair tests.',
    questions: [
      { text: 'Sun → plant → rabbit → ___', options: ['fox', 'rock', 'water', 'moon'], correctIndex: 0, topic: 'Food chain' },
      { text: 'Clouds bring rain. Rain fills ___', options: ['lakes and rivers', 'only shoes', 'only desks', 'the sun'], correctIndex: 0, topic: 'Water cycle' },
      { text: 'To test if plants need light, change only the ___', options: ['light', 'child name', 'color of shirt', 'everything'], correctIndex: 0, topic: 'Fair test' },
      { text: 'A caterpillar becomes a ___', options: ['butterfly', 'fish', 'tree', 'car'], correctIndex: 0, topic: 'Life cycle' },
      { text: 'Wind can move ___', options: ['leaves and kites', 'only rocks underground', 'only metal inside', 'nothing'], correctIndex: 0, topic: 'Weather' },
      { text: 'Recycling paper helps the ___', options: ['Earth', 'moon', 'clock', 'shoes'], correctIndex: 0, topic: 'Care for Earth' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Kindergarten Patterns Medium: Growing Rules',
    description: 'Skip counting and ABB patterns.',
    questions: [
      { text: '5, 10, 15, ___', options: ['20', '16', '18', '25'], correctIndex: 0, topic: 'Skip 5' },
      { text: '🔴 🔵 🔵 🔴 🔵 ___', options: ['🔵', '🔴', '🟢', '⬛'], correctIndex: 0, topic: 'ABB' },
      { text: '2, 4, 6, 8, 10, ___', options: ['12', '11', '9', '14'], correctIndex: 0, topic: 'Even numbers' },
      { text: 'A, B, C, D, ___', options: ['E', 'A', 'F', 'B'], correctIndex: 0, topic: 'Letters' },
      { text: '10, 9, 8, 7, ___', options: ['6', '5', '9', '11'], correctIndex: 0, topic: 'Count back' },
      { text: 'Clap, clap, stomp repeats. Fourth sound is ___', options: ['clap', 'stomp', 'jump', 'sing'], correctIndex: 0, topic: 'Rhythm' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Kindergarten Patterns Hard: Find the Rule',
    description: '+3 patterns and two-attribute patterns.',
    questions: [
      { text: '3, 6, 9, 12, ___', options: ['15', '13', '14', '18'], correctIndex: 0, topic: '+3 rule' },
      { text: '🔺🔻🔺🔻🔺 ___', options: ['🔻', '🔺', '⬜', '🔴'], correctIndex: 0, topic: 'Shape rule' },
      { text: '1, 3, 5, 7, ___', options: ['9', '8', '10', '6'], correctIndex: 0, topic: 'Odd numbers' },
      { text: 'Red, blue, red, blue, red, ___', options: ['Blue', 'Red', 'Green', 'Yellow'], correctIndex: 0, topic: 'Color pattern' },
      { text: '20, 18, 16, ___', options: ['14', '15', '12', '17'], correctIndex: 0, topic: 'Subtract 2' },
      { text: 'Rule: add 2. 4, 6, 8, ___', options: ['10', '9', '11', '7'], correctIndex: 0, topic: 'State rule' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Kindergarten Memory Medium: Lists & Steps',
    description: 'Remember order in stories and short lists.',
    questions: [
      { text: 'Wash hands → eat snack → read. Third step?', options: ['Read', 'Wash', 'Eat', 'Sleep'], correctIndex: 0, topic: 'Procedure' },
      { text: 'Cat, dog, fish, bird. Which was second?', options: ['Dog', 'Cat', 'Fish', 'Bird'], correctIndex: 0, topic: 'List order' },
      { text: '★=star, ♥=heart. ♥ means ___', options: ['heart', 'star', 'square', 'tree'], correctIndex: 0, topic: 'Symbols' },
      { text: 'Spring, summer, fall, ___', options: ['Winter', 'Spring', 'Monday', 'Rain'], correctIndex: 0, topic: 'Seasons' },
      { text: 'Saw 3, 8, 3, 8. Number that repeated?', options: ['3 and 8', 'Only 3', 'Only 8', 'None'], correctIndex: 0, topic: 'Scan' },
      { text: 'Left, right, left, right — fifth move?', options: ['Left', 'Right', 'Both', 'Stop'], correctIndex: 0, topic: 'Pattern memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Kindergarten Memory Hard: Chunks & Recall',
    description: 'Phone chunks and multi-step recall.',
    questions: [
      { text: 'Phone 22-15-09 — first chunk?', options: ['22', '15', '09', '221'], correctIndex: 0, topic: 'Chunking' },
      { text: 'Mix → pour → bake → cool. Step before bake?', options: ['Pour', 'Mix', 'Cool', 'Eat'], correctIndex: 0, topic: 'Recipe' },
      { text: 'A, C, E, G — letter after E was ___', options: ['G', 'C', 'A', 'B'], correctIndex: 0, topic: 'Skip letters' },
      { text: '🔴🟡🔵 shown once. Color in middle?', options: ['Yellow', 'Red', 'Blue', 'Green'], correctIndex: 0, topic: 'Order' },
      { text: 'Monday, Tuesday, Wednesday, ___', options: ['Thursday', 'Friday', 'Sunday', 'March'], correctIndex: 0, topic: 'Days' },
      { text: 'Pair: sock ↔ shoe. Glove ↔ ___', options: ['Hand', 'Foot', 'Hat', 'Book'], correctIndex: 0, topic: 'Pairs' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Kindergarten Problems Medium: Two Steps',
    description: 'Join and take apart within 15.',
    questions: [
      { text: '6 birds land, 4 more come. Total?', options: ['10', '9', '11', '2'], correctIndex: 0, topic: 'Join' },
      { text: '12 − 5 = ?', options: ['7', '6', '8', '17'], correctIndex: 0, topic: 'Subtract' },
      { text: 'Had 9, got 4 more, then lost 2. Now?', options: ['11', '10', '12', '15'], correctIndex: 0, topic: 'Two-step' },
      { text: 'Longer fence needs ___ posts', options: ['more', 'fewer', 'zero', 'one'], correctIndex: 0, topic: 'Reasoning' },
      { text: 'Share 10 crackers with 2 friends equally. Each gets ___', options: ['5', '4', '6', '10'], correctIndex: 0, topic: 'Fair share' },
      { text: 'Which tool measures how long?', options: ['Ruler', 'Ball', 'Crayon box', 'Book'], correctIndex: 0, topic: 'Tools' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Kindergarten Problems Hard: Plan & Solve',
    description: 'Missing parts, time, and money intro.',
    questions: [
      { text: 'Need 15 stickers, have 9. How many more?', options: ['6', '5', '7', '24'], correctIndex: 0, topic: 'Compare' },
      { text: '2 dimes = ___ cents', options: ['20', '10', '12', '2'], correctIndex: 0, topic: 'Money' },
      { text: 'Start 2:00, wait 1 hour. Time is ___', options: ['3:00', '2:01', '1:00', '4:30'], correctIndex: 0, topic: 'Time' },
      { text: '8 + 4 + 3 = ?', options: ['15', '14', '16', '12'], correctIndex: 0, topic: 'Add three' },
      { text: 'Rectangle 4 long and 2 wide — how many squares inside if each is 1?', options: ['8', '6', '4', '2'], correctIndex: 0, topic: 'Area intro' },
      { text: 'Train has 5 cars, add 3 cars. Total cars?', options: ['8', '7', '9', '2'], correctIndex: 0, topic: 'Story' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Kindergarten Thinking Medium: Why & How',
    description: 'Predict, sort, and choose better ideas.',
    questions: [
      { text: 'Wet floor sign warns us to ___', options: ['walk carefully', 'run fast', 'jump', 'ignore it'], correctIndex: 0, topic: 'Safety' },
      { text: 'Which melts in warm sun: ice or rock?', options: ['Ice', 'Rock', 'Both', 'Neither'], correctIndex: 0, topic: 'Compare' },
      { text: 'Dark clouds often mean rain ___', options: ['soon', 'never', 'only at night always', 'only in winter always'], correctIndex: 0, topic: 'Predict' },
      { text: 'Which does NOT belong: spoon, fork, plate, shoe?', options: ['Shoe', 'Spoon', 'Fork', 'Plate'], correctIndex: 0, topic: 'Sort' },
      { text: 'Measure with a ruler is better than ___', options: ['guessing length', 'singing', 'dancing', 'sleeping'], correctIndex: 0, topic: 'Evidence' },
      { text: 'If you want shade, stand under a ___', options: ['tree', 'puddle', 'mirror', 'drum'], correctIndex: 0, topic: 'Plan' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Kindergarten Thinking Hard: Decide & Explain',
    description: 'Sources, fair tests, and if-then thinking.',
    questions: [
      { text: 'Story says character was kind. Kind means ___', options: ['Helpful and caring', 'Always loud', 'Always sleeping', 'Angry only'], correctIndex: 0, topic: 'Words' },
      { text: 'Fair test changes ___ thing', options: ['one', 'ten', 'zero', 'all'], correctIndex: 0, topic: 'Fair test' },
      { text: 'Thermometer tells ___', options: ['temperature', 'color of shirt', 'your name', 'time always'], correctIndex: 0, topic: 'Tools' },
      { text: 'If it rains, we need an ___', options: ['umbrella', 'skateboard', 'kite only', 'nothing'], correctIndex: 0, topic: 'If-then' },
      { text: 'Which source is stronger: thermometer or guess?', options: ['Thermometer', 'Guess', 'Dream', 'Song'], correctIndex: 0, topic: 'Sources' },
      { text: 'All dogs are animals. A puppy is a ___', options: ['Dog', 'Plant', 'Rock', 'Car'], correctIndex: 0, topic: 'Logic' },
    ],
  }),
];
