import { buildQuiz } from '../utils.js';

const G = 'kindergarten';

/** Medium + hard tiers for Kindergarten adaptive pilot. */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const KINDERGARTEN_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Kindergarten Math Medium: Numbers to 15',
    description: 'Add and subtract within 15, compare numbers.',
    questions: [
      { text: '8 + 4 = ?', options: ['13', '10', '12', '11'], correctIndex: 2, topic: 'Addition' },
      { text: '14 − 3 = ?', options: ['17', '11', '12', '10'], correctIndex: 1, topic: 'Subtraction' },
      { text: 'Which is less: 9 or 12?', options: ['15', 'Same', '12', '9'], correctIndex: 3, topic: 'Compare' },
      { text: '10 + 5 = ?', options: ['16', '15', '5', '14'], correctIndex: 1, topic: 'Teen numbers' },
      { text: 'How many sides on a hexagon?', options: ['5', '3', '6', '8'], correctIndex: 2, topic: 'Shapes' },
      { text: '7 + 7 = ?', options: ['77', '14', '13', '15'], correctIndex: 1, topic: 'Doubles' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Kindergarten Math Hard: Stories to 20',
    description: 'Two-step stories and numbers to 20.',
    questions: [
      { text: 'Had 12 crayons, lost 4. Left?', options: ['16', '9', '8', '7'], correctIndex: 2, topic: 'Take away' },
      { text: '9 + 6 + 2 = ?', options: ['16', '18', '17', '15'], correctIndex: 2, topic: 'Add three' },
      { text: '18 − 5 = ?', options: ['14', '23', '12', '13'], correctIndex: 3, topic: 'Subtract teens' },
      { text: 'Which number is between 11 and 13?', options: ['14', '11', '12', '10'], correctIndex: 2, topic: 'Between' },
      { text: '4 tens and 2 ones make ___', options: ['6', '42', '402', '24'], correctIndex: 1, topic: 'Place value' },
      { text: '5 + ? = 20', options: ['15', '14', '25', '10'], correctIndex: 0, topic: 'Missing addend' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Kindergarten Science Medium: Habitats & Change',
    description: 'Where animals live and how things change.',
    questions: [
      { text: 'Frogs live near ___', options: ['water', 'only snow', 'the moon', 'only sand'], correctIndex: 0, topic: 'Habitats' },
      { text: 'A seed needs water, soil, and ___', options: ['paint', 'ice cream', 'shoes', 'light'], correctIndex: 3, topic: 'Plants' },
      { text: 'Ice melts when it gets ___', options: ['darker', 'colder forever', 'warmer', 'louder'], correctIndex: 2, topic: 'Change' },
      { text: 'Day and night happen because Earth ___', options: ['shrinks', 'spins', 'melts', 'stops'], correctIndex: 1, topic: 'Earth' },
      { text: 'Wood comes from ___', options: ['metal only', 'clouds', 'rocks', 'trees'], correctIndex: 3, topic: 'Materials' },
      { text: 'We taste sweet foods with our ___', options: ['tongue', 'knees', 'hair', 'elbows'], correctIndex: 0, topic: 'Senses' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Kindergarten Science Hard: Systems & Cycles',
    description: 'Food chains, weather patterns, and fair tests.',
    questions: [
      { text: 'Sun → plant → rabbit → ___', options: ['water', 'rock', 'moon', 'fox'], correctIndex: 3, topic: 'Food chain' },
      { text: 'Clouds bring rain. Rain fills ___', options: ['lakes and rivers', 'only shoes', 'the sun', 'only desks'], correctIndex: 0, topic: 'Water cycle' },
      { text: 'To test if plants need light, change only the ___', options: ['color of shirt', 'child name', 'everything', 'light'], correctIndex: 3, topic: 'Fair test' },
      { text: 'A caterpillar becomes a ___', options: ['car', 'tree', 'fish', 'butterfly'], correctIndex: 3, topic: 'Life cycle' },
      { text: 'Wind can move ___', options: ['leaves and kites', 'only metal inside', 'only rocks underground', 'nothing'], correctIndex: 0, topic: 'Weather' },
      { text: 'Recycling paper helps the ___', options: ['Earth', 'clock', 'shoes', 'moon'], correctIndex: 0, topic: 'Care for Earth' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Kindergarten Patterns Medium: Growing Rules',
    description: 'Skip counting and ABB patterns.',
    questions: [
      { text: '5, 10, 15, ___', options: ['25', '18', '16', '20'], correctIndex: 3, topic: 'Skip 5' },
      { text: '🔴 🔵 🔵 🔴 🔵 ___', options: ['🔴', '⬛', '🔵', '🟢'], correctIndex: 2, topic: 'ABB' },
      { text: '2, 4, 6, 8, 10, ___', options: ['14', '11', '9', '12'], correctIndex: 3, topic: 'Even numbers' },
      { text: 'A, B, C, D, ___', options: ['A', 'F', 'E', 'B'], correctIndex: 2, topic: 'Letters' },
      { text: '10, 9, 8, 7, ___', options: ['6', '5', '9', '11'], correctIndex: 0, topic: 'Count back' },
      { text: 'Clap, clap, stomp repeats. Fourth sound is ___', options: ['stomp', 'jump', 'clap', 'sing'], correctIndex: 2, topic: 'Rhythm' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Kindergarten Patterns Hard: Find the Rule',
    description: '+3 patterns and two-attribute patterns.',
    questions: [
      { text: '3, 6, 9, 12, ___', options: ['15', '13', '18', '14'], correctIndex: 0, topic: '+3 rule' },
      { text: '🔺🔻🔺🔻🔺 ___', options: ['🔺', '⬜', '🔻', '🔴'], correctIndex: 2, topic: 'Shape rule' },
      { text: '1, 3, 5, 7, ___', options: ['9', '8', '6', '10'], correctIndex: 0, topic: 'Odd numbers' },
      { text: 'Red, blue, red, blue, red, ___', options: ['Green', 'Blue', 'Yellow', 'Red'], correctIndex: 1, topic: 'Color pattern' },
      { text: '20, 18, 16, ___', options: ['12', '15', '17', '14'], correctIndex: 3, topic: 'Subtract 2' },
      { text: 'Rule: add 2. 4, 6, 8, ___', options: ['11', '9', '7', '10'], correctIndex: 3, topic: 'State rule' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Kindergarten Memory Medium: Lists & Steps',
    description: 'Remember order in stories and short lists.',
    questions: [
      { text: 'Wash hands → eat snack → read. Third step?', options: ['Eat', 'Sleep', 'Read', 'Wash'], correctIndex: 2, topic: 'Procedure' },
      { text: 'Cat, dog, fish, bird. Which was second?', options: ['Fish', 'Bird', 'Cat', 'Dog'], correctIndex: 3, topic: 'List order' },
      { text: '★=star, ♥=heart. ♥ means ___', options: ['tree', 'square', 'star', 'heart'], correctIndex: 3, topic: 'Symbols' },
      { text: 'Spring, summer, fall, ___', options: ['Monday', 'Rain', 'Spring', 'Winter'], correctIndex: 3, topic: 'Seasons' },
      { text: 'Saw 3, 8, 3, 8. Number that repeated?', options: ['None', '3 and 8', 'Only 3', 'Only 8'], correctIndex: 1, topic: 'Scan' },
      { text: 'Left, right, left, right — fifth move?', options: ['Stop', 'Left', 'Right', 'Both'], correctIndex: 1, topic: 'Pattern memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Kindergarten Memory Hard: Chunks & Recall',
    description: 'Phone chunks and multi-step recall.',
    questions: [
      { text: 'Phone 22-15-09 — first chunk?', options: ['15', '221', '09', '22'], correctIndex: 3, topic: 'Chunking' },
      { text: 'Mix → pour → bake → cool. Step before bake?', options: ['Pour', 'Mix', 'Cool', 'Eat'], correctIndex: 0, topic: 'Recipe' },
      { text: 'A, C, E, G — letter after E was ___', options: ['C', 'A', 'G', 'B'], correctIndex: 2, topic: 'Skip letters' },
      { text: '🔴🟡🔵 shown once. Color in middle?', options: ['Green', 'Red', 'Blue', 'Yellow'], correctIndex: 3, topic: 'Order' },
      { text: 'Monday, Tuesday, Wednesday, ___', options: ['Sunday', 'March', 'Thursday', 'Friday'], correctIndex: 2, topic: 'Days' },
      { text: 'Pair: sock ↔ shoe. Glove ↔ ___', options: ['Hand', 'Book', 'Foot', 'Hat'], correctIndex: 0, topic: 'Pairs' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Kindergarten Problems Medium: Two Steps',
    description: 'Join and take apart within 15.',
    questions: [
      { text: '6 birds land, 4 more come. Total?', options: ['10', '2', '11', '9'], correctIndex: 0, topic: 'Join' },
      { text: '12 − 5 = ?', options: ['6', '7', '17', '8'], correctIndex: 1, topic: 'Subtract' },
      { text: 'Had 9, got 4 more, then lost 2. Now?', options: ['15', '11', '12', '10'], correctIndex: 1, topic: 'Two-step' },
      { text: 'Longer fence needs ___ posts', options: ['one', 'more', 'fewer', 'zero'], correctIndex: 1, topic: 'Reasoning' },
      { text: 'Share 10 crackers with 2 friends equally. Each gets ___', options: ['10', '6', '5', '4'], correctIndex: 2, topic: 'Fair share' },
      { text: 'Which tool measures how long?', options: ['Book', 'Ruler', 'Ball', 'Crayon box'], correctIndex: 1, topic: 'Tools' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Kindergarten Problems Hard: Plan & Solve',
    description: 'Missing parts, time, and money intro.',
    questions: [
      { text: 'Need 15 stickers, have 9. How many more?', options: ['6', '5', '7', '24'], correctIndex: 0, topic: 'Compare' },
      { text: '2 dimes = ___ cents', options: ['2', '10', '20', '12'], correctIndex: 2, topic: 'Money' },
      { text: 'Start 2:00, wait 1 hour. Time is ___', options: ['4:30', '3:00', '2:01', '1:00'], correctIndex: 1, topic: 'Time' },
      { text: '8 + 4 + 3 = ?', options: ['12', '15', '16', '14'], correctIndex: 1, topic: 'Add three' },
      { text: 'Rectangle 4 long and 2 wide — how many squares inside if each is 1?', options: ['4', '6', '2', '8'], correctIndex: 3, topic: 'Area intro' },
      { text: 'Train has 5 cars, add 3 cars. Total cars?', options: ['9', '7', '2', '8'], correctIndex: 3, topic: 'Story' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Kindergarten Thinking Medium: Why & How',
    description: 'Predict, sort, and choose better ideas.',
    questions: [
      { text: 'Wet floor sign warns us to ___', options: ['ignore it', 'walk carefully', 'run fast', 'jump'], correctIndex: 1, topic: 'Safety' },
      { text: 'Which melts in warm sun: ice or rock?', options: ['Rock', 'Ice', 'Both', 'Neither'], correctIndex: 1, topic: 'Compare' },
      { text: 'Dark clouds often mean rain ___', options: ['only at night always', 'only in winter always', 'soon', 'never'], correctIndex: 2, topic: 'Predict' },
      { text: 'Which does NOT belong: spoon, fork, plate, shoe?', options: ['Plate', 'Spoon', 'Fork', 'Shoe'], correctIndex: 3, topic: 'Sort' },
      { text: 'Measure with a ruler is better than ___', options: ['singing', 'dancing', 'guessing length', 'sleeping'], correctIndex: 2, topic: 'Evidence' },
      { text: 'If you want shade, stand under a ___', options: ['puddle', 'drum', 'mirror', 'tree'], correctIndex: 3, topic: 'Plan' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Kindergarten Thinking Hard: Decide & Explain',
    description: 'Sources, fair tests, and if-then thinking.',
    questions: [
      { text: 'Story says character was kind. Kind means ___', options: ['Angry only', 'Always sleeping', 'Always loud', 'Helpful and caring'], correctIndex: 3, topic: 'Words' },
      { text: 'Fair test changes ___ thing', options: ['one', 'zero', 'ten', 'all'], correctIndex: 0, topic: 'Fair test' },
      { text: 'Thermometer tells ___', options: ['color of shirt', 'your name', 'time always', 'temperature'], correctIndex: 3, topic: 'Tools' },
      { text: 'If it rains, we need an ___', options: ['skateboard', 'kite only', 'nothing', 'umbrella'], correctIndex: 3, topic: 'If-then' },
      { text: 'Which source is stronger: thermometer or guess?', options: ['Guess', 'Song', 'Thermometer', 'Dream'], correctIndex: 2, topic: 'Sources' },
      { text: 'All dogs are animals. A puppy is a ___', options: ['Dog', 'Car', 'Plant', 'Rock'], correctIndex: 0, topic: 'Logic' },
    ],
  }),
];
