import { buildQuiz } from '../utils.js';

const G = 'pre_k';

/** Medium + hard tiers for Pre-K adaptive pilot (easy quizzes remain in pre_k.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const PRE_K_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Pre-K Math Medium: Numbers to 10',
    description: 'Count, compare, and solve simple number stories to 10.',
    questions: [
      { text: '4 + 2 = ?', options: ['6', '8', '5', '7'], correctIndex: 0, topic: 'Addition to 10' },
      { text: 'Which is greater: 7 or 5?', options: ['7', 'They are equal', '3', '5'], correctIndex: 0, topic: 'Comparing numbers' },
      { text: '10 − 3 = ?', options: ['6', '13', '7', '8'], correctIndex: 2, topic: 'Subtraction to 10' },
      { text: 'How many corners does a rectangle have?', options: ['4', '2', '3', '5'], correctIndex: 0, topic: 'Shapes' },
      { text: '5, 6, 7, ___', options: ['9', '5', '8', '6'], correctIndex: 2, topic: 'Number order' },
      { text: 'There are 3 red blocks and 3 blue blocks. How many blocks total?', options: ['7', '6', '3', '5'], correctIndex: 1, topic: 'Add groups' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Pre-K Math Hard: Stories to 12',
    description: 'Solve multi-step and missing-number stories within 12.',
    questions: [
      { text: 'Lina has 5 stickers and gets 4 more. Then she gives away 2. How many now?', options: ['6', '11', '9', '7'], correctIndex: 3, topic: 'Two-step story' },
      { text: 'What number makes 3 + __ = 8?', options: ['6', '5', '3', '4'], correctIndex: 1, topic: 'Missing addend' },
      { text: 'Which number is between 8 and 10?', options: ['7', '8', '11', '9'], correctIndex: 3, topic: 'Number sequence' },
      { text: '12 − 5 = ?', options: ['7', '8', '9', '6'], correctIndex: 0, topic: 'Subtraction to 12' },
      { text: 'Mia has 6 toy cars. Sam has 2 more than Mia. Sam has ___ cars.', options: ['8', '7', '6', '9'], correctIndex: 0, topic: 'Compare amounts' },
      { text: 'Which shows an equal pair?', options: ['4 + 4 and 8', '2 + 2 and 5', '3 + 1 and 6', '5 + 2 and 9'], correctIndex: 0, topic: 'Number relationships' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Pre-K Science Medium: Living Things and Weather',
    description: 'Understand needs of plants/animals and common weather changes.',
    questions: [
      { text: 'A plant needs water, light, and ___', options: ['paint', 'shoes', 'music', 'air'], correctIndex: 3, topic: 'Plant needs' },
      { text: 'Which animal likely lives in a pond?', options: ['Polar bear', 'Frog', 'Monkey', 'Camel'], correctIndex: 1, topic: 'Habitats' },
      { text: 'If dark clouds gather, what weather may come?', options: ['No weather', 'Rain', 'Only wind forever', 'Snow in summer always'], correctIndex: 1, topic: 'Weather clues' },
      { text: 'Ice left outside on a warm day will ___', options: ['melt', 'bounce', 'freeze harder', 'grow'], correctIndex: 0, topic: 'Matter changes' },
      { text: 'Which body part helps you hear a bell?', options: ['Hands', 'Ears', 'Nose', 'Eyes'], correctIndex: 1, topic: 'Senses' },
      { text: 'Baby birds often eat food brought by their ___', options: ['parents', 'toys', 'rocks', 'clouds'], correctIndex: 0, topic: 'Animal families' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Pre-K Science Hard: Cycles and Simple Experiments',
    description: 'Predict changes in nature and reason through simple fair tests.',
    questions: [
      { text: 'A caterpillar changes into a ___', options: ['butterfly', 'rabbit', 'fish', 'tree'], correctIndex: 0, topic: 'Life cycle' },
      { text: 'To test if a plant needs light, keep water the same and change only ___', options: ['everything at once', 'light', 'the plant name', 'soil and pot and water'], correctIndex: 1, topic: 'Fair test basics' },
      { text: 'Sun warms water, then tiny drops rise into the air. This is called ___', options: ['freezing', 'sleeping', 'evaporation', 'digging'], correctIndex: 2, topic: 'Water cycle intro' },
      { text: 'Why do we wear boots in puddles?', options: ['To run indoors', 'To jump higher always', 'To make rain stop', 'To keep feet dry'], correctIndex: 3, topic: 'Cause and effect' },
      { text: 'If we recycle paper, we help save ___', options: ['puddles', 'sand toys', 'stars', 'trees'], correctIndex: 3, topic: 'Earth care' },
      { text: 'An animal with thick fur is likely ready for ___ weather', options: ['cold', 'hot desert only', 'rainbow', 'no weather'], correctIndex: 0, topic: 'Adaptations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Pre-K Pattern Recognition Medium: Repeat and Grow',
    description: 'Find repeating patterns and continue simple growing patterns.',
    questions: [
      { text: '🔴 🔵 🔴 🔵 🔴 ___', options: ['🟢', '🔵', '🔴', '🟡'], correctIndex: 1, topic: 'AB pattern' },
      { text: '2, 4, 2, 4, ___', options: ['1', '6', '2', '4'], correctIndex: 2, topic: 'Number repeat' },
      { text: 'Clap, clap, stomp, clap, clap, ___', options: ['jump', 'clap', 'stomp', 'sit'], correctIndex: 2, topic: 'Sound pattern' },
      { text: '1, 2, 3, 1, 2, ___', options: ['2', '1', '4', '3'], correctIndex: 3, topic: 'Cycle pattern' },
      { text: 'Big circle, small circle, big circle, ___', options: ['big circle', 'square', 'small circle', 'triangle'], correctIndex: 2, topic: 'Size pattern' },
      { text: '⭐, ⭐⭐, ⭐⭐⭐, ___', options: ['⭐⭐', '⭐', '⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'], correctIndex: 2, topic: 'Growing pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Pre-K Pattern Recognition Hard: Rules and Predictions',
    description: 'Identify pattern rules with mixed shapes, actions, and numbers.',
    questions: [
      { text: '3, 5, 7, ___', options: ['6', '8', '9', '10'], correctIndex: 2, topic: 'Add 2 rule' },
      { text: '🔺 🔺 🔵 🔺 🔺 🔵 ___', options: ['🔺', '⭐', '⬛', '🔵'], correctIndex: 0, topic: 'AAB pattern' },
      { text: 'Hop, turn, clap, hop, turn, ___', options: ['sit', 'hop', 'turn', 'clap'], correctIndex: 3, topic: 'Action sequence' },
      { text: '10, 8, 6, ___', options: ['4', '3', '5', '7'], correctIndex: 0, topic: 'Subtract 2 rule' },
      { text: 'Square, circle, triangle, square, circle, ___', options: ['circle', 'square', 'triangle', 'star'], correctIndex: 2, topic: 'Shape cycle' },
      { text: 'Rule: add 1 more each time. 2 blocks, 3 blocks, 4 blocks, ___', options: ['2 blocks', '5 blocks', '6 blocks', '3 blocks'], correctIndex: 1, topic: 'Rule language' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Pre-K Memory Medium: Order and Recall',
    description: 'Remember short lists, positions, and multi-step directions.',
    questions: [
      { text: 'You hear: apple, bus, cat. Which word was second?', options: ['bus', 'apple', 'dog', 'cat'], correctIndex: 0, topic: 'List order' },
      { text: 'First put on socks, then shoes. What comes second?', options: ['socks', 'shoes', 'coat', 'hat'], correctIndex: 1, topic: 'Sequence memory' },
      { text: '🔵 means blue and 🔴 means red. What does 🔴 mean?', options: ['green', 'blue', 'yellow', 'red'], correctIndex: 3, topic: 'Symbol recall' },
      { text: 'If the teddy was under the chair, where was it?', options: ['outside', 'under the chair', 'on the table', 'in the sink'], correctIndex: 1, topic: 'Location memory' },
      { text: 'Clap, stomp, clap. What was the middle action?', options: ['wave', 'clap', 'stomp', 'jump'], correctIndex: 2, topic: 'Action order' },
      { text: 'Remember this pair: spoon with bowl. Spoon goes with ___', options: ['pencil', 'bowl', 'shoe', 'door'], correctIndex: 1, topic: 'Association' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Pre-K Memory Hard: Multi-Step Recall',
    description: 'Track longer sequences and remember key details after delays.',
    questions: [
      { text: 'Listen: red, blue, green, red. Which color came third?', options: ['green', 'red', 'yellow', 'blue'], correctIndex: 0, topic: 'Color sequence' },
      { text: 'Steps: wash hands, open lunchbox, eat. What step is before eat?', options: ['wash hands', 'open lunchbox', 'close lunchbox', 'drink water'], correctIndex: 1, topic: 'Step recall' },
      { text: 'Numbers shown: 4, 1, 4, 2. Which number repeated?', options: ['3', '2', '1', '4'], correctIndex: 3, topic: 'Repeated item memory' },
      { text: 'Morning routine: brush teeth, get dressed, pack bag. What is first?', options: ['pack bag', 'get dressed', 'eat dinner', 'brush teeth'], correctIndex: 3, topic: 'Routine memory' },
      { text: 'Pair to remember: key -> door. Which matches key?', options: ['book', 'window', 'plate', 'door'], correctIndex: 3, topic: 'Paired recall' },
      { text: 'Right, left, right, left. What move is fourth?', options: ['left', 'jump', 'right', 'stop'], correctIndex: 0, topic: 'Pattern memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Pre-K Problem Solving Medium: Plan and Try',
    description: 'Use simple strategies to solve classroom and play problems.',
    questions: [
      { text: 'You need 6 blocks for a bridge and have 4. What should you do?', options: ['Get 2 more blocks', 'Stop building', 'Throw blocks away', 'Start with 10 blocks'], correctIndex: 0, topic: 'Find missing amount' },
      { text: 'Two friends both want the same toy. Best plan?', options: ['Take turns with a timer', 'Hide the toy', 'Break the toy', 'Grab it and run'], correctIndex: 0, topic: 'Social problem solving' },
      { text: 'Your puzzle piece does not fit. Next smart step?', options: ['Force it hard', 'Tear the puzzle', 'Give up', 'Turn the piece and try another spot'], correctIndex: 3, topic: 'Try a new strategy' },
      { text: 'Juice spilled on table. What should happen first?', options: ['Wipe it with a towel', 'Add more juice', 'Run away', 'Ignore it'], correctIndex: 0, topic: 'Safety action' },
      { text: 'A tower keeps falling. Which change may help?', options: ['Shake it more', 'Build on a pillow', 'Only use one block', 'Build a wider bottom'], correctIndex: 3, topic: 'Test and improve' },
      { text: 'You cannot reach the top shelf. Safe choice?', options: ['Throw things at it', 'Climb the shelf', 'Ask an adult for help', 'Jump from a chair'], correctIndex: 2, topic: 'Help-seeking' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Pre-K Problem Solving Hard: Multi-Step Challenges',
    description: 'Solve two-step stories, choose tools, and evaluate better plans.',
    questions: [
      { text: 'There are 8 crayons. 3 break. Then 2 new crayons are added. How many now?', options: ['10', '5', '7', '6'], correctIndex: 2, topic: 'Two-step quantity' },
      { text: 'You need to carry water to plants. Best tool?', options: ['A small watering can', 'A pillow', 'A toy car', 'A paper book'], correctIndex: 0, topic: 'Choose tool' },
      { text: 'Snack has 10 crackers to share with 2 children equally. Each gets ___', options: ['6', '4', '10', '5'], correctIndex: 3, topic: 'Fair sharing' },
      { text: 'To cross a muddy area safely, better plan is to ___', options: ['walk around on dry path', 'run through fast', 'sit in mud', 'close eyes and jump'], correctIndex: 0, topic: 'Evaluate choices' },
      { text: 'A train has 4 cars. Add 3 cars, then remove 1. Total?', options: ['5', '8', '7', '6'], correctIndex: 3, topic: 'Change over time' },
      { text: 'If scissors are not cutting paper, first check if they are ___', options: ['under the table', 'painted blue', 'closed correctly and held right', 'thrown away'], correctIndex: 2, topic: 'Troubleshooting' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Pre-K Critical Thinking Medium: Compare and Explain',
    description: 'Use clues to sort, predict, and choose safer or better options.',
    questions: [
      { text: 'Which does NOT belong with fruit: apple, banana, shoe, grape?', options: ['banana', 'apple', 'grape', 'shoe'], correctIndex: 3, topic: 'Classification' },
      { text: 'If the sky is dark and windy, what might happen next?', options: ['snow indoors', 'nothing ever changes', 'the sun gets brighter', 'rain may start'], correctIndex: 3, topic: 'Prediction' },
      { text: 'Which is a safer way to carry scissors?', options: ['wave them around', 'hide them in pocket open', 'run with them up high', 'point down while walking slowly'], correctIndex: 3, topic: 'Safety reasoning' },
      { text: 'A coat helps in cold weather because it keeps your body ___', options: ['warm', 'wet', 'smaller', 'invisible'], correctIndex: 0, topic: 'Cause and effect' },
      { text: 'Which source tells temperature better: thermometer or guess?', options: ['thermometer', 'toy', 'guess', 'song'], correctIndex: 0, topic: 'Evidence' },
      { text: 'If a toy car has no wheels, it will likely ___', options: ['grow bigger', 'turn into a train', 'not roll well', 'fly high'], correctIndex: 2, topic: 'Reasoning from features' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Pre-K Critical Thinking Hard: Decide and Justify',
    description: 'Apply if-then reasoning, stronger evidence, and logical sorting.',
    questions: [
      { text: 'If a plant turns yellow, what is a good first check?', options: ['its shoes', 'whether it got enough water', 'its favorite song', 'its toy box'], correctIndex: 1, topic: 'Cause investigation' },
      { text: 'Which choice gives stronger evidence about rain: looking outside or guessing?', options: ['closing eyes', 'looking outside', 'guessing', 'asking a toy'], correctIndex: 1, topic: 'Evidence quality' },
      { text: 'All puppies are dogs. Max is a puppy. Max is a ___', options: ['cat', 'dog', 'bird', 'fish'], correctIndex: 1, topic: 'Simple logic' },
      { text: 'If the floor is wet, what should you do first?', options: ['ignore it', 'run quickly', 'walk carefully and tell an adult', 'slide on it'], correctIndex: 2, topic: 'If-then safety' },
      { text: 'Which item best measures length: ruler, spoon, pillow, or hat?', options: ['spoon', 'hat', 'pillow', 'ruler'], correctIndex: 3, topic: 'Tool selection' },
      { text: 'You want to know which paper airplane flies farther. Fair test means you change only ___', options: ['nothing ever', 'the child’s name', 'everything at once', 'one thing at a time'], correctIndex: 3, topic: 'Fair testing' },
    ],
  }),
];
