import { buildQuiz } from '../utils.js';

const G = 'pre_k';

/** Medium + hard tiers for Pre-K adaptive pilot (easy quizzes remain in pre_k.js). */
/** @type {import('../../catalogTypes.js').QuizCatalogEntry[]} */
export const PRE_K_TIER_QUIZZES = [
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'medium',
    title: 'Pre-K Math Medium: Numbers to 10',
    description: 'Count, compare, and solve simple number stories to 10.',
    questions: [
      { text: '4 + 2 = ?', options: ['6', '5', '7', '8'], correctIndex: 0, topic: 'Addition to 10' },
      { text: 'Which is greater: 7 or 5?', options: ['7', '5', 'They are equal', '3'], correctIndex: 0, topic: 'Comparing numbers' },
      { text: '10 − 3 = ?', options: ['7', '6', '8', '13'], correctIndex: 0, topic: 'Subtraction to 10' },
      { text: 'How many corners does a rectangle have?', options: ['4', '3', '2', '5'], correctIndex: 0, topic: 'Shapes' },
      { text: '5, 6, 7, ___', options: ['8', '9', '6', '5'], correctIndex: 0, topic: 'Number order' },
      { text: 'There are 3 red blocks and 3 blue blocks. How many blocks total?', options: ['6', '5', '7', '3'], correctIndex: 0, topic: 'Add groups' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'math',
    difficultyLevel: 'hard',
    title: 'Pre-K Math Hard: Stories to 12',
    description: 'Solve multi-step and missing-number stories within 12.',
    questions: [
      { text: 'Lina has 5 stickers and gets 4 more. Then she gives away 2. How many now?', options: ['7', '9', '6', '11'], correctIndex: 0, topic: 'Two-step story' },
      { text: 'What number makes 3 + __ = 8?', options: ['5', '4', '6', '3'], correctIndex: 0, topic: 'Missing addend' },
      { text: 'Which number is between 8 and 10?', options: ['9', '7', '11', '8'], correctIndex: 0, topic: 'Number sequence' },
      { text: '12 − 5 = ?', options: ['7', '6', '8', '9'], correctIndex: 0, topic: 'Subtraction to 12' },
      { text: 'Mia has 6 toy cars. Sam has 2 more than Mia. Sam has ___ cars.', options: ['8', '7', '6', '9'], correctIndex: 0, topic: 'Compare amounts' },
      { text: 'Which shows an equal pair?', options: ['4 + 4 and 8', '5 + 2 and 9', '3 + 1 and 6', '2 + 2 and 5'], correctIndex: 0, topic: 'Number relationships' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'medium',
    title: 'Pre-K Science Medium: Living Things and Weather',
    description: 'Understand needs of plants/animals and common weather changes.',
    questions: [
      { text: 'A plant needs water, light, and ___', options: ['air', 'shoes', 'music', 'paint'], correctIndex: 0, topic: 'Plant needs' },
      { text: 'Which animal likely lives in a pond?', options: ['Frog', 'Camel', 'Polar bear', 'Monkey'], correctIndex: 0, topic: 'Habitats' },
      { text: 'If dark clouds gather, what weather may come?', options: ['Rain', 'Snow in summer always', 'No weather', 'Only wind forever'], correctIndex: 0, topic: 'Weather clues' },
      { text: 'Ice left outside on a warm day will ___', options: ['melt', 'grow', 'bounce', 'freeze harder'], correctIndex: 0, topic: 'Matter changes' },
      { text: 'Which body part helps you hear a bell?', options: ['Ears', 'Eyes', 'Nose', 'Hands'], correctIndex: 0, topic: 'Senses' },
      { text: 'Baby birds often eat food brought by their ___', options: ['parents', 'toys', 'clouds', 'rocks'], correctIndex: 0, topic: 'Animal families' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'science',
    difficultyLevel: 'hard',
    title: 'Pre-K Science Hard: Cycles and Simple Experiments',
    description: 'Predict changes in nature and reason through simple fair tests.',
    questions: [
      { text: 'A caterpillar changes into a ___', options: ['butterfly', 'fish', 'tree', 'rabbit'], correctIndex: 0, topic: 'Life cycle' },
      { text: 'To test if a plant needs light, keep water the same and change only ___', options: ['light', 'soil and pot and water', 'everything at once', 'the plant name'], correctIndex: 0, topic: 'Fair test basics' },
      { text: 'Sun warms water, then tiny drops rise into the air. This is called ___', options: ['evaporation', 'sleeping', 'freezing', 'digging'], correctIndex: 0, topic: 'Water cycle intro' },
      { text: 'Why do we wear boots in puddles?', options: ['To keep feet dry', 'To jump higher always', 'To run indoors', 'To make rain stop'], correctIndex: 0, topic: 'Cause and effect' },
      { text: 'If we recycle paper, we help save ___', options: ['trees', 'puddles', 'stars', 'sand toys'], correctIndex: 0, topic: 'Earth care' },
      { text: 'An animal with thick fur is likely ready for ___ weather', options: ['cold', 'hot desert only', 'rainbow', 'no weather'], correctIndex: 0, topic: 'Adaptations' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'medium',
    title: 'Pre-K Pattern Recognition Medium: Repeat and Grow',
    description: 'Find repeating patterns and continue simple growing patterns.',
    questions: [
      { text: '🔴 🔵 🔴 🔵 🔴 ___', options: ['🔵', '🔴', '🟢', '🟡'], correctIndex: 0, topic: 'AB pattern' },
      { text: '2, 4, 2, 4, ___', options: ['2', '4', '6', '1'], correctIndex: 0, topic: 'Number repeat' },
      { text: 'Clap, clap, stomp, clap, clap, ___', options: ['stomp', 'clap', 'jump', 'sit'], correctIndex: 0, topic: 'Sound pattern' },
      { text: '1, 2, 3, 1, 2, ___', options: ['3', '2', '4', '1'], correctIndex: 0, topic: 'Cycle pattern' },
      { text: 'Big circle, small circle, big circle, ___', options: ['small circle', 'big circle', 'triangle', 'square'], correctIndex: 0, topic: 'Size pattern' },
      { text: '⭐, ⭐⭐, ⭐⭐⭐, ___', options: ['⭐⭐⭐⭐', '⭐⭐', '⭐⭐⭐⭐⭐', '⭐'], correctIndex: 0, topic: 'Growing pattern' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'pattern_recognition',
    difficultyLevel: 'hard',
    title: 'Pre-K Pattern Recognition Hard: Rules and Predictions',
    description: 'Identify pattern rules with mixed shapes, actions, and numbers.',
    questions: [
      { text: '3, 5, 7, ___', options: ['9', '8', '10', '6'], correctIndex: 0, topic: 'Add 2 rule' },
      { text: '🔺 🔺 🔵 🔺 🔺 🔵 ___', options: ['🔺', '🔵', '⬛', '⭐'], correctIndex: 0, topic: 'AAB pattern' },
      { text: 'Hop, turn, clap, hop, turn, ___', options: ['clap', 'hop', 'turn', 'sit'], correctIndex: 0, topic: 'Action sequence' },
      { text: '10, 8, 6, ___', options: ['4', '5', '7', '3'], correctIndex: 0, topic: 'Subtract 2 rule' },
      { text: 'Square, circle, triangle, square, circle, ___', options: ['triangle', 'square', 'circle', 'star'], correctIndex: 0, topic: 'Shape cycle' },
      { text: 'Rule: add 1 more each time. 2 blocks, 3 blocks, 4 blocks, ___', options: ['5 blocks', '3 blocks', '6 blocks', '2 blocks'], correctIndex: 0, topic: 'Rule language' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'medium',
    title: 'Pre-K Memory Medium: Order and Recall',
    description: 'Remember short lists, positions, and multi-step directions.',
    questions: [
      { text: 'You hear: apple, bus, cat. Which word was second?', options: ['bus', 'apple', 'cat', 'dog'], correctIndex: 0, topic: 'List order' },
      { text: 'First put on socks, then shoes. What comes second?', options: ['shoes', 'socks', 'hat', 'coat'], correctIndex: 0, topic: 'Sequence memory' },
      { text: '🔵 means blue and 🔴 means red. What does 🔴 mean?', options: ['red', 'blue', 'green', 'yellow'], correctIndex: 0, topic: 'Symbol recall' },
      { text: 'If the teddy was under the chair, where was it?', options: ['under the chair', 'on the table', 'in the sink', 'outside'], correctIndex: 0, topic: 'Location memory' },
      { text: 'Clap, stomp, clap. What was the middle action?', options: ['stomp', 'clap', 'jump', 'wave'], correctIndex: 0, topic: 'Action order' },
      { text: 'Remember this pair: spoon with bowl. Spoon goes with ___', options: ['bowl', 'shoe', 'pencil', 'door'], correctIndex: 0, topic: 'Association' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'memory',
    difficultyLevel: 'hard',
    title: 'Pre-K Memory Hard: Multi-Step Recall',
    description: 'Track longer sequences and remember key details after delays.',
    questions: [
      { text: 'Listen: red, blue, green, red. Which color came third?', options: ['green', 'blue', 'red', 'yellow'], correctIndex: 0, topic: 'Color sequence' },
      { text: 'Steps: wash hands, open lunchbox, eat. What step is before eat?', options: ['open lunchbox', 'wash hands', 'close lunchbox', 'drink water'], correctIndex: 0, topic: 'Step recall' },
      { text: 'Numbers shown: 4, 1, 4, 2. Which number repeated?', options: ['4', '1', '2', '3'], correctIndex: 0, topic: 'Repeated item memory' },
      { text: 'Morning routine: brush teeth, get dressed, pack bag. What is first?', options: ['brush teeth', 'get dressed', 'pack bag', 'eat dinner'], correctIndex: 0, topic: 'Routine memory' },
      { text: 'Pair to remember: key -> door. Which matches key?', options: ['door', 'window', 'plate', 'book'], correctIndex: 0, topic: 'Paired recall' },
      { text: 'Right, left, right, left. What move is fourth?', options: ['left', 'right', 'jump', 'stop'], correctIndex: 0, topic: 'Pattern memory' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'medium',
    title: 'Pre-K Problem Solving Medium: Plan and Try',
    description: 'Use simple strategies to solve classroom and play problems.',
    questions: [
      { text: 'You need 6 blocks for a bridge and have 4. What should you do?', options: ['Get 2 more blocks', 'Start with 10 blocks', 'Throw blocks away', 'Stop building'], correctIndex: 0, topic: 'Find missing amount' },
      { text: 'Two friends both want the same toy. Best plan?', options: ['Take turns with a timer', 'Grab it and run', 'Hide the toy', 'Break the toy'], correctIndex: 0, topic: 'Social problem solving' },
      { text: 'Your puzzle piece does not fit. Next smart step?', options: ['Turn the piece and try another spot', 'Force it hard', 'Tear the puzzle', 'Give up'], correctIndex: 0, topic: 'Try a new strategy' },
      { text: 'Juice spilled on table. What should happen first?', options: ['Wipe it with a towel', 'Ignore it', 'Add more juice', 'Run away'], correctIndex: 0, topic: 'Safety action' },
      { text: 'A tower keeps falling. Which change may help?', options: ['Build a wider bottom', 'Only use one block', 'Shake it more', 'Build on a pillow'], correctIndex: 0, topic: 'Test and improve' },
      { text: 'You cannot reach the top shelf. Safe choice?', options: ['Ask an adult for help', 'Climb the shelf', 'Jump from a chair', 'Throw things at it'], correctIndex: 0, topic: 'Help-seeking' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'problem_solving',
    difficultyLevel: 'hard',
    title: 'Pre-K Problem Solving Hard: Multi-Step Challenges',
    description: 'Solve two-step stories, choose tools, and evaluate better plans.',
    questions: [
      { text: 'There are 8 crayons. 3 break. Then 2 new crayons are added. How many now?', options: ['7', '5', '10', '6'], correctIndex: 0, topic: 'Two-step quantity' },
      { text: 'You need to carry water to plants. Best tool?', options: ['A small watering can', 'A paper book', 'A pillow', 'A toy car'], correctIndex: 0, topic: 'Choose tool' },
      { text: 'Snack has 10 crackers to share with 2 children equally. Each gets ___', options: ['5', '4', '6', '10'], correctIndex: 0, topic: 'Fair sharing' },
      { text: 'To cross a muddy area safely, better plan is to ___', options: ['walk around on dry path', 'run through fast', 'close eyes and jump', 'sit in mud'], correctIndex: 0, topic: 'Evaluate choices' },
      { text: 'A train has 4 cars. Add 3 cars, then remove 1. Total?', options: ['6', '7', '5', '8'], correctIndex: 0, topic: 'Change over time' },
      { text: 'If scissors are not cutting paper, first check if they are ___', options: ['closed correctly and held right', 'thrown away', 'painted blue', 'under the table'], correctIndex: 0, topic: 'Troubleshooting' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'medium',
    title: 'Pre-K Critical Thinking Medium: Compare and Explain',
    description: 'Use clues to sort, predict, and choose safer or better options.',
    questions: [
      { text: 'Which does NOT belong with fruit: apple, banana, shoe, grape?', options: ['shoe', 'apple', 'banana', 'grape'], correctIndex: 0, topic: 'Classification' },
      { text: 'If the sky is dark and windy, what might happen next?', options: ['rain may start', 'the sun gets brighter', 'snow indoors', 'nothing ever changes'], correctIndex: 0, topic: 'Prediction' },
      { text: 'Which is a safer way to carry scissors?', options: ['point down while walking slowly', 'run with them up high', 'wave them around', 'hide them in pocket open'], correctIndex: 0, topic: 'Safety reasoning' },
      { text: 'A coat helps in cold weather because it keeps your body ___', options: ['warm', 'wet', 'smaller', 'invisible'], correctIndex: 0, topic: 'Cause and effect' },
      { text: 'Which source tells temperature better: thermometer or guess?', options: ['thermometer', 'guess', 'song', 'toy'], correctIndex: 0, topic: 'Evidence' },
      { text: 'If a toy car has no wheels, it will likely ___', options: ['not roll well', 'fly high', 'grow bigger', 'turn into a train'], correctIndex: 0, topic: 'Reasoning from features' },
    ],
  }),
  buildQuiz({
    gradeLevel: G,
    category: 'critical_thinking',
    difficultyLevel: 'hard',
    title: 'Pre-K Critical Thinking Hard: Decide and Justify',
    description: 'Apply if-then reasoning, stronger evidence, and logical sorting.',
    questions: [
      { text: 'If a plant turns yellow, what is a good first check?', options: ['whether it got enough water', 'its favorite song', 'its toy box', 'its shoes'], correctIndex: 0, topic: 'Cause investigation' },
      { text: 'Which choice gives stronger evidence about rain: looking outside or guessing?', options: ['looking outside', 'guessing', 'asking a toy', 'closing eyes'], correctIndex: 0, topic: 'Evidence quality' },
      { text: 'All puppies are dogs. Max is a puppy. Max is a ___', options: ['dog', 'cat', 'bird', 'fish'], correctIndex: 0, topic: 'Simple logic' },
      { text: 'If the floor is wet, what should you do first?', options: ['walk carefully and tell an adult', 'run quickly', 'slide on it', 'ignore it'], correctIndex: 0, topic: 'If-then safety' },
      { text: 'Which item best measures length: ruler, spoon, pillow, or hat?', options: ['ruler', 'spoon', 'pillow', 'hat'], correctIndex: 0, topic: 'Tool selection' },
      { text: 'You want to know which paper airplane flies farther. Fair test means you change only ___', options: ['one thing at a time', 'everything at once', 'nothing ever', 'the child’s name'], correctIndex: 0, topic: 'Fair testing' },
    ],
  }),
];
